### ISSUE TITLE
Clarification: On How to Create Custom Validators

### ISSUE THREAD

**Issue by alexhernandez** [monterail/vuelidate#100]
Was wondering if i could get clarification on how i may be doing this wrong. Want to make sure a input field is a valid date.

```
export default (date) => {
  withParams({type: 'isDate', date}, value => moment(date).isValid());
}
```

```
validations: {
      effectiveDate: { required, isDate },
}
```

**Comment by Frizi** [comment]
First thing, if you are not using $params, you can drop `withParams` altogether.
Second is that you want to use `value` passed to the function and you don't need another closure around it.
```javascript
export default withParams({type: 'isDate'}, value => moment(value).isValid());
```

**Comment by alexhernandez** [comment]
Awesome your Feedback helped.

```
import Vue from 'vue';
import moment from 'moment';
import Vuelidate from 'vuelidate';

Vue.use(Vuelidate);

export const isDate = (value) => moment(value, 'YYYY-MM-DD', true).isValid();
```

**Comment by Cmrickels** [comment]
Can you guys add an explanation for the simplistic way of doing this in VUE. 

export default{
    validations: {
        password: {
          required,
          minLength: minLength(8),
          validatePassword
        }
    },
}

function validatePassword(value){
  //do logic on password value and return boolean on if meets standards
  return value;
}
