### ISSUE TITLE
Mixin doesn't support SSR

### ISSUE THREAD

**Issue by jonaskuiler** [monterail/vuelidate#104]
Hey all,

I'm using your plugin (which is really nice) in a SSR setup and the latest version (0.4.1) will break when rendering in the server.

It will break here https://github.com/monterail/vuelidate/blob/master/src/index.js#L455 because it's accessing refs of a Vue instance which will not be rendered in a server environment.

I will try to resolve this issue myself and will do a pull request accordingly.

**Comment by Frizi** [comment]
The whole vuelidate is based on assumption of `$refs` being accessible, I even slightly alter the rendering process to make it lazy. I never tried SSR in Vue before, just recently started playing with Nuxt. I'll try that soon too. What's probably missing is a forced rerender like in https://github.com/monterail/vuelidate/blob/master/src/index.js#L221-L226

First guess would be to add similar mechanism to the vuelidate's top-level _root_ Vue instance
https://github.com/monterail/vuelidate/blob/master/src/index.js#L428

**Comment by Frizi** [comment]
This is fixed in v0.5.0
