### ISSUE TITLE
window is undefined

### ISSUE THREAD

**Issue by shyamchandranmec** [monterail/vuelidate#106]
I switched to version 0.4.1. I am using nuxt js for server side rendering. Now I am getting this error.
'window is undefined' 
This issue was not there in version 0.2.0.

**Comment by Frizi** [comment]
I'll improve on SSR support in next version. Please use previous ones for time being.

**Comment by shyamchandranmec** [comment]
Cool. Will wait for it :)

**Comment by Frizi** [comment]
This is fixed in v0.5.0

**Comment by shyamchandranmec** [comment]
@Frizi  Thanks 👍
