### ISSUE TITLE
Async validators

### ISSUE THREAD

**Issue by shentao** [monterail/vuelidate#11]
Support for promise-based async validators.

**Comment by pohnean** [comment]
Is this being worked on currently? This is an important feature.

**Comment by shentao** [comment]
Actually yes! ETA is around next week. :)

**Comment by pohnean** [comment]
fantastic! looking forward to it!

**Comment by pohnean** [comment]
btw, will the async validator be able to do bulk validation of multiple attributes at the same time? i would imagine sending multiple requests to validate the whole form is not good.

**Comment by shentao** [comment]
Validators are called when the data changes, thus if you want to delay the validation, you have to delay the data change. For example by using debounce on your inputs.
In other words – multiple values will be validated at the same time only if you change all of those values at the same time.

**Comment by pohnean** [comment]
the fields are validated immediately right? 

for example, if you started with a blank form and you have 5 required fields, each with async (server-side) validators, and the user clicks on the submit button without filling any field...

would it trigger the async calls 5 times, or just once?

normally for server side validation, it will be just 1 ajax call to validate the entire form.

**Comment by Frizi** [comment]
@pohnean  There currently is no builtin way to do it, but as the only requirement is that you return a promise, it's doable. You have to create a promise that debounces the call internally and collets the data from multiple fields at the same time. I will think of creating such helper functions, as it seems to be pretty important usecase.

Another problem is triggering only on submit. It's also possible, but you would have to abuse computed to accomplish this by adding something like `data: {isSubmitted: false}` and relying on this value changing inside your validators. Similar to $dirty flag, but affecting computation. I have to think about how to avoid that. Please share your ideas if you have anything.

**Comment by shentao** [comment]
Merged! Great job @Frizi! :)
