### ISSUE TITLE
Issue when component data is an object from a Vuex store.

### ISSUE THREAD

**Issue by byrd1089** [monterail/vuelidate#110]
Hi guys,

This may be similar to other issues I'm seeing so I'll just add mine to the list. :-)

Here is my repo with a very simple app demonstrating my problem. Just edit and an "Author" and you'll see.

https://github.com/byrd1089/vueauthors

I'm having trouble getting Vuelidate to work when my component data is an object from a Vuex store. It seems no matter what I do, the inputs are flagged as invalid.

I really want to use your library in a much larger app, but I can't seem to get past this. I'm sure it's something simple that I'm missing.

Thanks for your help!

-- Jeff

**Comment by Frizi** [comment]
You are defining validations in a wrong way.

```javascript
    validations: {
      'person.fname': {
        required,
        minLength: minLength(2)
      },
      'person.lname': {
        required,
        minLength: minLength(2)
      },
      'person.email': {
        required,
        email
      }
    }
```

What you probably want to do is to validate the nested field instead.

```javascript
validations: {
  person: {
    fname: {
      required,
      minLength: minLength(2)
    },
    lname: {
      required,
      minLength: minLength(2)
    },
    email: {
      required,
      email
    }
  }
}
```

Now instead of using `$v['person.fname']`, you should do `$v.person.fname`.

**Comment by byrd1089** [comment]
That fixed it!  I never would have figured it out.
