### ISSUE TITLE
Reset $dirty when creating new object for validation

### ISSUE THREAD

**Issue by eminos** [monterail/vuelidate#122]
I'm trying to reset the $dirty flag (all the $dirty flags?) each time I create a new object for validation.
I guess I'm doing it wrong.

I've created a jsfiddle to show what I'm trying to do.
https://jsfiddle.net/aasuw7yn/3/

**Comment by Frizi** [comment]
This should work and look's like a potential bug to me. I'll take a closer look soon.

**Comment by Frizi** [comment]
I believe it works with v0.5.0 now. :)
