### ISSUE TITLE
Is there a way to programmatically force an error?

### ISSUE THREAD

**Issue by doginthehat** [monterail/vuelidate#124]
Hi,

First, great library, love it. Also great idea to provide a base fiddle, that's awesome 👍 

I'm trying to do something which is either not possible, or I'm not aware of how to do it.

I'm hoping you can either guide me or confirm if it's not possible.

Basically I would need to be able to programmatically set some validation errors based on some reply from the server.

It's not the documented case of an async validation of a single field, I'm submitting the whole form data and need to highlight some of the field errors based on the server logic applied. 

For example, image a credit card processing. If the credit card payment fails, i'd like to highlight the fields with particular validation error status (it's not precisely my case but similar).

The problem I'm running into is that the error status booleans are apparently just getters, so if I try to force them, I get told off.

See this jsfiddle based on the sample you provided (again, great idea!) 

https://jsfiddle.net/doginthehat/qc343jrd/

The result is: `"Error: TypeError: Cannot set property required of #<Object> which has only a getter"`

Is there a way to do this?

**Comment by doginthehat** [comment]
I'm slowly coming to the conclusion that no, because all those booleans are really just like proxies to functions.. am I on the right path?

**Comment by Frizi** [comment]
@doginthehat It's definitely possible, but simply not the direct way you tried to do it. Imagine that validators are computed values. Now you could add a server-side bulk validation as a single action, assign the promise to the `data` and build a validator that uses this promise and takes a part of it.

```javascript
function validateFromServer(getter) {
  return this.validationPromise
    ? this.validationPromise.then(getter)
    : true // mark as valid until server side validations is not performed
}
```

Observe that `this` here is always your component's instance. That's how validators work.

now you can use it something like that
```javascript
methods: {
  async onSubmit () {
    const response = await fetch('/api/submitForm', {
      method: 'POST',
      data: this.form
    })
    this.validationPromise = await response.json()
  }
},

validations: {
  form: {
    myField: {
      required,
      serverSaidOK: validateFromServer(R.path(['path','to','myField','status'])
    }
  }
}
```

Helper `R.path` from Ramda used as an example and it's clearly not necessary.

**Comment by doginthehat** [comment]
Hi @Frizi 

Thanks for getting back to me (apologies for the delays getting back, I was away).

That sounds like it could work, I'll have to give it a spin..

**Comment by doginthehat** [comment]
Hi @Frizi 

I've been playing with this idea for a bit but I'm running into an issue.

First, I tweaked the validateFromServer function to this:

```
export const validateFromServer = getter => function (value) {
    console.log("validateFromServer(%o,%o)",getter, this.validationPromise)
    return this.validationPromise
        ? this.validationPromise.then(getter)
        : true
}
```

(I think that's what you intended in the example..?)

The problem I'm running into is that the validateFromServer function doesn't seem to run again when I get back from the server.

I've tried explicitly running $touch shortly after the response but that doesn't trigger the function either.

Interestingly though, if I change the value of the field after the return, the whole thing kicks in and the function is called.

What am I missing?

**Comment by doginthehat** [comment]
I've made a jsfiddle based on the original to illustrate this:

https://jsfiddle.net/doginthehat/4zcpzk7g/

I've used getsandbox as the remote.

If you click submit it sends the request, but nothing happens to the server validation. 

Type something in the field and it kicks in.

**Comment by Frizi** [comment]
You should add validationPromise to data field, so it can be observable. Then the validator will kick in when you assign it and rerun when the promise state changes.

**Comment by doginthehat** [comment]
@Frizi 

Yes! That's the bit I was missing! 😄 

And reading back to your original suggestion, you did mention it.. my mistake.

Working fiddle for anyone coming across this thread 

https://jsfiddle.net/doginthehat/LoLbfsoe/

Help much appreciated

**Comment by Seraf** [comment]
Hello,

I'm also interested setup something like that: my backend is giving me error message (from json) I would like to display.
Any idea how to inject the result of my submit promise into the $v structure to be able to know which error to display ?

Thanks !

**Comment by Frizi** [comment]
@Seraf I believe "withParams" isn't currently properly handled inside async callbacks, but you still can use the same technique i described above and simply directly reference the data returned by your backend inside the template.

I also believe the original issue is fixed now. If you need anything more here, please open a new issue. Thanks :)

**Comment by SirLamer** [comment]
I would just like to add/endorse that formal support for this action of accepting error messages from the server would be super awesome. When doing an AJAX form submit, there's always the chance of a validation test failure, even if they are all intended to be checked first client-side a programming error might mean a server-side check catches in. In particular, doing form submissions to a public JSON API interface. The main reasons are:
- The error condition should be considered as cleared when the field is next edited, so such errors should be cleared when "$dirty()" occurs. Of course this can be done externally to the validation package but I am just figuring this would be a common use case, or at least would be if offered.
- The API response may provide multiple error conditions for a given form field and it may be desired to display them all. This makes it unique from other test cases, which will always only evaluate one test condition.

The technique here is a good patch solution but probably not quite robust enough. I don't just mean to be Mr. Negative Nelly... I am going to poke at solutions for this, and if I hit on something which might work well in a PR I will share, but beforehand just want to share my thoughts in case there are different opinions about this.

**Comment by Seraf** [comment]
I finally ended with a `errors` object in my data populated by my promise error callback. As my API return an error json object containing fields errors, it allows me to have custom validator which will check in this `errors` object if the field exist to return a true or false. And then, it's easy to display the message associated in the `v-if` that display error messages.

**Comment by SirLamer** [comment]
@Seraf Yeah that totally makes sense but then it means two separate validation layers... not evil, just not the best for deploying a project with many such forms. I am assuming that anyone who is interested in client-side form validation is doing it for a form which is being submitted via an API and thus will be subject to two separate, mostly redundant but still different, validation test sets.

In particular, a common logic check will be "disable form submit button when an error is present",  so now we're talking about checking and managing two separate but very similar error collections.

I intend to conform to the JSON API spec so, admittedly, the error response might not follow the pattern of how the form is designed because of how relationships are handled, so... I'll try to work on that.

**Comment by Seraf** [comment]
It's not really a different validation layer : you still use the validators which is the mind spirit of vuelidate.

It's just that you aren't checking the value itself but the answer of the API. So yes, that means you have to manage a json object by yourself, but that also means you can adapt every API answers to your needs.

If vuelidate handle it "out of the box", that means you'll have to write a specific answer on your API and most of the project won't be compatible with the vuelidate standard.

**Comment by SirLamer** [comment]
No, it just has to expect an error response. The 'pointer' will be populated when a validation test fails.

http://jsonapi.org/format/#errors

**Comment by SirLamer** [comment]
So... I have been working very hard at a set of building blocks tools for building web forms in a way which handles very intuitively for the user, including graceful handling of various edge cases including field validation errors from various sources.

For handling error messages from the API response, I had to cave and just settled with handling them totally separately from Vuelidate. Ultimately I am using a Vue computed property which collects the error messages from the various sources available, which are:
- Vuelidate
- POST method form response with an error message bag (handled via a Vuex store which manages my session state client-side)
- JSON API response with an error message bag

I was hoping for a slick combo solution for Vuelidate + JSON response error messages, but I cannot come to a conclusion on a design which is robust and also simple enough to warrant any special implementation effort for each case, so I am just passing JSON API error messages to the form components I have prepared in an "errors" property. It's ugly but functional.

**Comment by shrpne** [comment]
@Frizi there is SirLamer's [intent](https://github.com/monterail/vuelidate/issues/124#issuecomment-297857395). Maybe we can reopen this issue or create a new feature request with it? I think such feature could be useful for a lot of people

**Comment by SirLamer** [comment]
I ended up handling it as a component wrapped around each input field and it works well. It functions the same as though Vuelidate was doing it itself.

**Comment by Frizi** [comment]
I agree, but I'd also argue that it's already possible and pretty easy to do. You just have to create a validator that pulls data from your local state, and that state should be populated by errors from server response.

This is legit every time you have a separate "submit" action that can still produce errors. It is not a separate async validator for any particular field, but rather a state known after certain response associated with potentially multiple form fields.

If you have any other pattern in mind (or how to make applying that pattern more obvious), i'd be grateful for sharing.

**Comment by duleorlovic** [comment]
I iterated on @doginthehat example and added server errors for two fields separately.

https://jsfiddle.net/duleorlovic/0tdpu32a

Based on error response from server we show error on specific fields.
Server errors are checked in `.catch` response for validationPromise and we clear validationPromise on update for those fields which can produce server errors.
