### ISSUE TITLE
Checkbox: $dirty is always false

### ISSUE THREAD

**Issue by DragonI** [monterail/vuelidate#127]
Issue: When a checkbox is checked or unchecked , $dirty is never triggered /set. $dirty is always false.

Tested with nested and non nested. Also tried
- @input="$v.checky.$touch()"
- @input="$v.account.cb2.$dirty()"

Here is the code, https://codepen.io/DragonI/pen/BRoaoy. Using Vue 2.2.6 and Vuelidate 0.4.3.

Found these issues, as well, when using global $touch and global $reset
- clicking on global $touch will enable $dirty. The checkbox messages will display as expected. Not ideal since it's global.
- if a checkbox is checked and global $reset is used, the checkbox will remained checked

Or am I missing something?

**Comment by Frizi** [comment]
I believe that's because you are using a wrong event. `input` works on `text` fields, but for checkboxes you should use `change` event. Try `@change="$v.checky.$touch()"` and it all works well.

**Comment by DragonI** [comment]
:new_moon_with_face: thx

**Comment by joshikeerti** [comment]
I am having a similar issue with dirty for a checkbox always being false. I am using the @change event.
<b-checkbox v-model="formData.platforms" native-value="test" @change="$v.restrictionsFormData.platforms.$touch()">test</b-checkbox>

**Comment by patrickcate** [comment]
@joshikeerti I'm having the same issue. I'm also using the @change event. The event is being triggered, but the validation (a simple required in my case) never changes.

**Template:**
`<input type="checkbox" id="terms" v-model="agreeToTerms" @change="$v.agreeToTerms.$touch()">`

**Script:**
`validations: { 
agreeToTerms: {
required
}
}`

All my other validations are working fine (include other required validations). Did you find an answer?

**Comment by ghodgey** [comment]
Check out: 
[](https://github.com/monterail/vuelidate/issues/332)

Need to use:
myCb : { sameAs: sameAs( () => true ) }
