### ISSUE TITLE
Vuex in strict mode and handing @input

### ISSUE THREAD

**Issue by travisfisher** [monterail/vuelidate#130]
In Vuex, manipulating state outside of mutations is not good:

https://vuex.vuejs.org/en/forms.html

Using the first recommendation from the link, I bind "value" and trigger my own "update" method on @input:

````
<input type="text" :class="{ 'form-control': true, 'form-control-danger': $v.first_name.$error }" id="first_name" name="first_name" placeholder="first name" :value="player.first_name" @input="update" required>
````

````
  methods: {
    ...mapActions([
      'setBusyStatus',
      'updatePlayerProperty',
      'requestUpdatePlayer'
    ]),
    update (e) {
      this.updatePlayerProperty([ e.target.name, e.target.value ]).then(() => {
        this.$v[e.target.name].$touch(e)
      })
    },
````

I'm trying to trigger the "touch" method for vuelidate once the mutation is successful, but the field always shows an error when it shouldn't be.

I thought if I passed the event into touch it would all work properly but that doesn't appear to be the case.

What am I doing wrong?

**Comment by Frizi** [comment]
I don't see any issue in the snippet here. Are you using `$error`, or  `$dirty` property inside your template? Only those two are actually using the flag set by `$touch` in any way.

**Comment by travisfisher** [comment]
The template snippet is the first snippet above. In that example I'm using:

`$v.first_name.$error`

$dirty and $error both are set to true after I run $touch().

**Comment by Frizi** [comment]
Yes, sorry, I missed that. I believe that your validation doesn't really follow the model. Your input is connected to ` player.first_name`, but your validation is done on `first_name`. Make sure to align them. You can use nesting on validations to accomplish that

**Comment by travisfisher** [comment]
That fixed it. Thank you.
