### ISSUE TITLE
How to reset validation inside methods?

### ISSUE THREAD

**Issue by lavezzi1** [monterail/vuelidate#132]
Hello,

To reproduce the problem, please type something to make form invalid and then hit the submit button, the validation of text input should be reset. 
https://jsfiddle.net/0Lq2cvrm/4/

In my case I need to reset form validation inside some methods, how I can do that?

Thanks!

**Comment by llavre** [comment]
Same problem here. It's not reacting to $v.$reset() method.
Same use-case as in jsfiddle below my post.

Any suggestions?

**Comment by FrancescoMussi** [comment]
I use `this.$v.$reset();` and it works fine for me

**Comment by petr0001** [comment]
I will leave this here - it took me a while to figure out.

You might need to do this in component method:
```this.$nextTick(() => { this.$v.$reset() })```

There is an method to handle form submit (applies to both sync and async methods, example is async but that's irrelevant):
```
async onFormSubmit() {
  // let's do one HTTP request to the API with "name" from the form
  // this is irrelevant, just for the feeling of real-world example
  await this.createFoo({ this.foo this.bar })
  
  // let's reset form values first
  this.foo = null
  this.bar = null
  
  // NOW let's reset vuelidate validator
  // because we need $dirty = FALSE

  // this doesn't work now (after resetting the form values in the previous lines)
  //this.$v.$reset()

  // this works
  //setTimeout(() => { this.$v.$reset() }, 0)

  // this works even better - using Vue.nextTick method
  this.$nextTick(() => { this.$v.$reset() })
}
```

Hope this helps someone.

Not sure if this is intended behaviour or something that could be fixed?

**Comment by invshakil** [comment]
> I use `this.$v.$reset();` and it works fine for me

thanks, worked for me.

**Comment by khairahscorner** [comment]
> I use `this.$v.$reset();` and it works fine for me

This worked for me too, thanks!

**Comment by donutDonut123** [comment]
But not for me, well maybe partially it did.
When I use `this.$v.$reset()` on my form, I get:
```
$anyDirty: false
$anyError: false
$dirty: false
$error: false
```
reset properly, but:
```
$invalid: true
```
still false.

How to reset `$invalid`, both in children and parent, to be `false` again?
I also null my form's inputs, but the $invalid is still true...

**Comment by shentao** [comment]
You can’t reset `$invalid`. It is the internal state of the validators that is always updated, no matter the `$dirty` state. Use `$error` for showing errors if you care about `$dirty` because: `$error = $invalid && $dirty`.

**Comment by Zeng95** [comment]
> I will leave this here - it took me a while to figure out.
> 
> You might need to do this in component method:
> `this.$nextTick(() => { this.$v.$reset() })`
> 
> There is a method to handle form submit (applies to both sync and async methods, example is async but that's irrelevant):
> 
> ```
> // the component
> export default {
> 	data() {
> 		return {
> 			foo: null,
> 			bar: null
> 		}
> 	},
> 	validations: {
> 		foo: {
> 			required,
> 			minLength: minLength(5),
> 			maxLength: maxLength(15)
> 		},
> 		bar: {
> 			required
> 		}
> 	},
> 	methods: {
> 		...mapActions('storeModule', ['createSomething']),
> 
> 		async onFormSubmit() {
> 			// let's do one HTTP request to the API with "name" from the form
> 			// this is irrelevant, just for the feeling of real-world example
> 			await this.createSomething({
> 				this.foo,
> 				this.bar
> 			})
> 			
> 			// let's reset form values first
> 			this.foo = null
> 			this.bar = null
> 	
> 			// NOW let's reset vuelidate validator
> 			// because we need $dirty = FALSE
> 	
> 			// this doesn't work now (after resetting the form values in the previous lines)
> 			//this.$v.$reset()
> 	
> 			// this works
> 			//setTimeout(() => { this.$v.$reset() }, 0)
> 	
> 			// this works even better - using Vue.nextTick method
> 			this.$nextTick(() => { this.$v.$reset() })
> 		}
> 	}
> }
> ```
> 
> Hope this helps someone.
> 
> I am not sure why it happens. I have tried the above jsfiddle and it doesn't seem to require nextTick, so I'm not sure what is the difference between that and my app.
> 
> My setup is:
> "vue": "^2.5.13",
> "vuelidate": "^0.7.4"

Thank you! "setTimeout(() => { this.$v.$reset() }, 0)" this way works for me. I'm resetting a form object and I don't know why somehow it works for me and the other two ways don't work.

**Comment by lucasrs97** [comment]
> I use `this.$v.$reset();` and it works fine for me

it helped me. Thank you!

**Comment by miko866** [comment]
`this.$v.$reset();`

Is still working. Thank you.

**Comment by llbarr1** [comment]
Using the composition-api:

```
import { nextTick } from "vue";

const clearForm = async () => {
 // reset your field to defaults
  await nextTick()
  v$.value.$reset()
};
```

**Comment by Bilal-Abbas-Gigalabs** [comment]
this.v$.$reset() works fine but the validation got break after one time.
the first time it works fine but if I rest the validation stopped working.


```
onSubmit() {
      this.v$.$validate();
      if (!this.v$.$error) {
        this.$toast.success(`Product created successfully`);
      } else {
        console.log("unsucessfull");
      }
 },
 
 onClear(){
      const data = initialState();
      Object.keys(data).forEach(k => {
        if(this[k])
          this[k] = data[k]
      })
      this.v$.$reset();
 },
 
 function initialState (){
  return {
      v$: useValidate(),
      name: null,
      reference: null,
      price: null,
      shippingDate: null,
  }
}
```

**Comment by tinyfly** [comment]
If you are using Vuelidate 2.x with the composition api make sure you use the ref value: `v$.value.$reset()`
