### ISSUE TITLE
no understand install this repo

### ISSUE THREAD

**Issue by gitcoffee** [monterail/vuelidate#133]
I want to install this repository, but I do not understand if after cloning the repository you have to follow the installation steps described, or how to start to run this project, thanks.

**Comment by Frizi** [comment]
If you want to use this library in your project, just use `npm` as described in the docs.

If you want to download the source and contribute, simply clone and `npm install`. Then you can run tests via `npm run test` or start a web server with docs using `npm run docs`. More scripts are specified in `package.json`.

**Comment by gitcoffee** [comment]
no functions instructions!!! No no and nooo, if you share or create code, you can make a video or screenshots of installation steps, do not forget that we are not all experts in vue or node, and we are Learning, thank you.
