### ISSUE TITLE
dynamic validation - ts question

### ISSUE THREAD

**Issue by Jack85** [monterail/vuelidate#134]
Hi, 
im trying too bostrap vuelidate dynamic validations in typescript using av-ts. For static validation bootstraping works, for dynamic I get error. 
Im using require or mixin, however it always ends with
`Property` or method "$v" is not defined`

Do you have an idea how to bootstrap it manually other way?
this is my compiled output of component..
```
let login = class login extends ext1_1.Vue {
	    //import Vue = require('vue')
	    // Declare the component's type
	    constructor() {
	        super(...arguments);
	        //	  @Data data() {
	        //return {
	        this.name = 'login';
	        this.username = '';
	        this.password = '';
	        this.failed = false;
	      
	    }
	
	    //dynamic validations as computed prop, can be used with if else
	    validations() {
	        return {
	            username: {
	                required,
	                minLength: minLength(4)
	            }
	            // ,password: {
	            // required,
	            // minLength: minLength(4)
	            // }
	        };
	    }
```

**Comment by Frizi** [comment]
This is due to the fact that your `validation` function is treated as a method instead of an option directly. I don't know the details of `av-ts`, as I'm personally using `vue-class-component`, but in it's case it's a matter of putting the function into the `@Component(..)` options. You have to find an analogue to that in your typing library.

**Comment by scellige** [comment]
I have a similar problem. When I use `dynamic validations` all my `.vue` file works wrong, it loses props, data values, and methods.
My dynamic validations are used for showing additional server validation errors (for example user's login is already used).

Workaround (it contains lot's of `any`, but only this way it works in my case):
```js
validations(): any {
    const list = {
        form: {
            some_prop: { required },
        },
    };

    return (this as any).serverValidationAdd(list);
},
```

```js
serverValidationAdd(list: any): any {
    //some code
}
```
