### ISSUE TITLE
no understand install this repo #2

### ISSUE THREAD

**Issue by gitcoffee** [monterail/vuelidate#135]
no functions instructions!!! No no and nooo, if you share or create code, you can make a video or screenshots of installation steps, do not forget that we are not all experts in vue or node, and we are Learning, thank you.

**Comment by SirLamer** [comment]
*ahem*

https://monterail.github.io/vuelidate/

**Comment by vip30** [comment]
I think the installation guide in readme is quite clear for the user currently

https://github.com/monterail/vuelidate/blob/master/README.md
