### ISSUE TITLE
Watch on $v throw an error

### ISSUE THREAD

**Issue by thibremy** [monterail/vuelidate#138]
When you watch $v, vue throws a  `Type error:Cannot read property '$refs' of undefined`.
You can reproduce this at [jsfiddle](https://jsfiddle.net/b5v4faqf/78/).

We can bypass this error with a custom hight order function on `touch()` or other stuff but it's sometime easy to manage that on a watcher.

**Comment by Ethaan** [comment]
did you get something here?

**Comment by thibremy** [comment]
This error came because `$v` is a computed prop, defined during `beforeCreate` handler.
When you declare your component `watch` try to get value of `$v`, but at this time `this` is not defined and you have this `Type error`.

What you can do it's to call `$watch` inside the `created` handler.

```
new Vue({
  ...

  created(){
    this.$watch('$v', () => {
      console.log('$v changed')
    })
  },

  validations: {
    ...
  }
})
```

**Comment by furey** [comment]
@thibremy: Was pulling my hair out all afternoon because of this. Thanks for your solution! 😀

**Comment by Frizi** [comment]
Hi, sorry for not comenting on that earlier. The original code should now just work as expected on `v0.5.0`. Fixed :)
