### ISSUE TITLE
Edge browser, intermittent error

### ISSUE THREAD

**Issue by comfytoday** [monterail/vuelidate#139]
I've come across a difficult error using multiple validators in Microsoft Edge v25 & v38.

I haven't been able to replicate in jsFiddle...

The error is intermittent, and often opening the console fixes the issue. 

I did catch it one time in v38, with the following output:

> description: Unable to get property 'rule' of undefined or null reference
> name: TypeError
> number: -2146823281

The error repeated on each keystroke.

I'm using webpack. 

Without the console open, the validations "fail" to validate on certain fields, but the field is not always the same: Sometimes the 'email' filed, other times the 'password' field. 

Below is an example of a custom validator that I'm using. 

```
import withParams from 'vuelidate/lib/withParams'

// Validate a password to:
// Contain atleast 1 number

export default withParams({type: 'required'}, value => {
  if (Array.isArray(value)) return !!value.length

  let pattern = /((?=\d))/g
  
  return value === undefined || value === null
    ? false
    : pattern.test(value) || value === ''
})

```

Any suggestions on how I can get closer to tracking this error down?

**Comment by Frizi** [comment]
Oh, lovely Edge. Is this issue also happening on any builtin validators?
You may try writing things to the screen or via network to separate console if devtools are enough to keep the bug away. Is there any detailed callstack attached to this error?

**Comment by comfytoday** [comment]
I suspect this is related:
https://github.com/Microsoft/ChakraCore/issues/1415

On browserstack I can only reproduce it in Edge 14, not 15, which aligns with that issue.

There is a possible workaround here:

https://github.com/Microsoft/ChakraCore/issues/1415#issuecomment-287888807

Happy to close this off, as I expect Edge users can just update.

**Comment by Frizi** [comment]
Right, this workaround looks very sketchy and that's not something to be included in a library. Anybody with intent to support that specific browser version will have to put it as a shim inside his own application, it will work globally anyway. Thanks for tracking that down :)
