### ISSUE TITLE
Feature request: "require()"

### ISSUE THREAD

**Issue by furey** [monterail/vuelidate#14]
E.g.

> import { validationMixin } from 'vuelidate';

…is awesome!

> const validationMixin = require('vuelidate');

…would also be awesome!

✌️ 😎 ✌️

**Comment by Frizi** [comment]
You can just do
```
const validationMixin = require('vuelidate').validationMixin;
```

**Comment by Frizi** [comment]
I actually added that approach to the docs just now. Thanks!

**Comment by furey** [comment]
@Frizi Thank you! JS n00b here, so apologies if the question was a little silly. 😊
