### ISSUE TITLE
Ensure Previous Validation is Valid Before Continuing

### ISSUE THREAD

**Issue by DragonI** [monterail/vuelidate#140]
Is there a way to ensure that a previous validation is valid before proceeding to the next?

Example: isLegalAge should only be performed if isDate is valid. If '1900-00-09' is entered, 2 error messages are displayed: invalid date and Must be 18 Years old
```
<input type="text" v-model="date"
    v-on:input="delayTouch($v.date)"
    v-bind:class="{error: $v.date.$error, valid: $v.date.$dirty && !$v.date.$invalid}"
    placeholder="YYYY-MM-DD"
>
<div class="errors">
  <p v-if="$v.date.$error && !$v.date.required">birthdate required.</p>
  <p v-if="$v.date.$error && !$v.date.isDate">Enter a valid birthdate</p>
  <p v-if="$v.date.$error && !$v.date.isLegalAge">Must be 18 Years old</p>
</div>
```
```
validations: {
  date: {
      required,
      isDate (value) {
        return isDate(value)
      },
      isLegalAge (value) {
        // always executed
        if (value.length < 10) return true
      	return isLegalAge(value, 18)
      }
    }
}`
```

https://jsfiddle.net/dragoni/jsjzej7m/3/

Thx

**Comment by DragonI** [comment]
Never mind. Found the solution in issue #20 - using 'and'

```
      isLegalAge (value) {
	return and('isDate', value => isLegalAge(value, 18))
      }
```
updated fiddle https://jsfiddle.net/dragoni/jsjzej7m/5/

**Comment by SirLamer** [comment]
Heads-up, the "isLegalAge" validation test doesn't work because it always returns true. I didn't dig in to figuring out why. So future readers should make sure to understand this before implementing this solution.
