### ISSUE TITLE
Created a helper for showing error messages easier. Need advice.

### ISSUE THREAD

**Issue by dobromir-hristov** [monterail/vuelidate#145]
So I created for a project of mine a really nice error message extractor that saved tons of boilerplate and I want to share it with everyone. I started making it into a plugin but I'm a bit stuck at how to actually publish it. 
I want it to be flexible for the developers, so all my logic is in a mixin and I have templates for Foundation, Bootstrap, Boolma etc... But How should I present it to the end user? 
Should it be all packed in a single file (good for browser env) and depending on the chosen config `Vue.use(extractor, {type:'foundation'})` something like this, to init the appropriate element, or should I just give it as a component that each developer should extend for them selves?
Please give me your thoughts. I can share my code later today if that helps, but its pretty much a walker to walk the validator tree and map each error to a validation message on your current input.

**Comment by Frizi** [comment]
First of all, great news and good job 👍

How to release it, depends on your API really. Think about how You would like to use it as a library. Also think what you would possibly like to be able to change, in case default setup doesn't fully work for you. Make that possible where it's necessary.

For packaging, you can release both really. Use a `src` library for original files and `lib` for built package files. Also make sure to properly treat CSS if you have any. Nobody likes to include `sass` just to use a specific dependency, so compile it down into a separate file.

I actually wanted to write my own helpers for that and include them into Vuelidate, but those would really be only components with slots inside, to not limit anyone in terms of templates. It's likely that some people will like to use ready-made components as you are preparing, so maybe you simply shouldn't bother _too much_ about flexibility in the end if you target those users.

And remember than __Done is better than perfect__. Will there be any issues, people will tell you about or even help you fix them. Good luck!

**Comment by dobromir-hristov** [comment]
Yes. You are right. I was concerned about publishing it to both users (with bundlers and without), but those without a bundler would make things allot harder. So I will most probably release it as a mixin and provide some simple templates along with it for anyone to use, if they desire. If they dont fit them, they can just use the mixin or use it as a guideline I guess.

**Comment by Frizi** [comment]
Looking forward for your release :)
