### ISSUE TITLE
Load vuelidate on unit tests

### ISSUE THREAD

**Issue by ferllings** [monterail/vuelidate#146]
Hello,

I have difficulties to load vuelidate for my karma unit testings.
It works fine on my component, but I can't access the $v object on the unit tests, to trigger and check the validation.

vuelidate is correctly imported on my index.js
```
import Vue from 'vue'
import Vuelidate from 'vuelidate'

Vue.use(Vuelidate)

Vue.config.productionTip = false

// require all test files (files that ends with .spec.js)
const testsContext = require.context('./specs', true, /\.spec$/)
testsContext.keys().forEach(testsContext)

// require all src files except main.js for coverage.
// you can also change this to match only the subset of files that
// you want coverage for.
const srcContext = require.context('../../src', true, /^\.\/(?!main(\.js)?$)/)
srcContext.keys().forEach(srcContext)
```

But I can't access $v on my specs
```
import Vue from 'vue'
import Login from '@/components/pages/Login'

describe('Login.vue', () => {
  it('validator should be loaded', () => {
    const vm = new Vue({
      el: document.createElement('div'),
      render: (h) => h(Login)
    })
    expect(vm.$v).to.exist
  })
})
```

how can I access the $v object?

Thanks for your help

**Comment by Frizi** [comment]
Vuelidate itself is unit tested that way, so it shouldn't be a problem. What you are missing here is `validations` property on your Vue instance. $v is not present when you don't configure any validations.

**Comment by ferllings** [comment]
Thanks for the answer, but I do have a validations property in my vue, and it's working fine in live mode

```
...
<script>
import { required, minLength, email } from 'vuelidate/lib/validators'

export default {
  data () {
    return {
      error: null,
      email: '',
      password: ''
    }
  },
  validations: {
    email: {
      required,
      email
    },
    password: {
      required,
      minLength: minLength(6)
    }
  },
  computed: {},
  methods: {
    submit () {
      if (!this.$v.invalid) {
        var credentials = {
          email: this.email,
          password: this.password
        }
        auth.login(this, credentials, '/')
      }
    }
  },
  components: {}
}
</script>
```

**Comment by Frizi** [comment]
In your test, you are actually not rendering the `Login` component. You are simply creating an instance of Vue component, which in your case will render into an unpinned div. The `$v` property will be accessible only on your child component, not the `vm` you are referring to.

Try this one:

```javascript
import Vue from 'vue'
import Login from '@/components/pages/Login'

describe('Login.vue', () => {
  it('validator should be loaded', () => {
    const vm = new Vue({
      el: document.createElement('div'),
      render: (h) => h(Login, {ref: 'child'})
    })
    expect(vm.$refs.child.$v).to.exist
  })
})
```

**Comment by ferllings** [comment]
Thanks @Frizi It's working fine now.

**Comment by johndatserakis** [comment]
To anyone else that comes across this - when using [vue-test-utils](https://github.com/vuejs/vue-test-utils) - I had to add:

```
import Vuelidate from 'vuelidate'
Vue.use(Vuelidate)
```

directly into my test file, then it worked.

**Comment by therealchiko** [comment]
thanks @johndatserakis, your solution worked for me too!

**Comment by ykhorzon** [comment]
Big Thanks to @johndatserakis . You save me from sticking on how to make vuelidate work in Jest for 4 hours.

**Comment by FloryanFilip** [comment]
If you are a Typescript user and registered a validation hook on your components, the only way I found is working is to declare validations like so:
`@Component({
    mixins: [validationMixin],
    validations: {
        yourData: {
            //
        }
    }
})
export default class YourComponent extends mixins(Vue, validationMixin) {`
