### ISSUE TITLE
TypeError: Cannot read property 'email/userData' of undefined

### ISSUE THREAD

**Issue by lukasborawski** [monterail/vuelidate#147]
Using with Nuxt.js.

Added as a normal vendor plugin at the nuxt config:

```
build: {
    vendor: ['axios', 'vuelidate'],
```

importing dependencies in `.vue` file and go this:

`TypeError: Cannot read property 'email' of undefined`

My data:

```
...
    data () {
      return {
        userData: {
          name: '',
          email: '',
          password: '',
          nickname: ''
        },
        submitted: false,
        errors: []
      }
    },
    validations: {
      email: {
        required, email
      }
    },
...
```
and template:

```
<input v-model.trim="userData.email" @input="$v.userData.email.$touch()" type="email" name="email" value="" placeholder="type your e-mail adress">
<span v-if="!$v.userData.email.required" class="error text-color_bred">Error</span>
```

**Comment by Frizi** [comment]
Can you check if it works for you on `ssr` branch? I'm planning to release it soon, but I have to know if that's fixed already.

**Comment by Frizi** [comment]
I just release it, so you can just try `v0.5.0`.

**Comment by michaelpumo** [comment]
I am getting a similar issues:

**Component:**

```
import { required, number } from 'vuelidate/lib/validators'
export default {
  name: 'AgeGate',
  data () {
    return ({
      day: '',
      month: '',
      year: '',
      isBrowser: false
    })
  },
  mounted () {
    this.isBrowser = process.browser
  },
  validations: {
    day: {
      required,
      number
    },
    month: {
      required,
      number
    },
    year: {
      required,
      number
    }
  }
}
```

**Plugin:**

```
import Vue from 'vue'
import Vuelidate from 'vuelidate'
Vue.use(Vuelidate)
```

**nuxt.config.js:**

```
plugins: [
  { src: '~plugins/vuelidate', ssr: false }
]
```

...

```
build: {
  vendor: [
    'vuelidate'
  ]
}
```

In my **Component Template**, I'm doing something like:

```
<div v-if="isBrowser">
  <input @input="$v.day.$touch()" v-model="day" type="text" placeholder="DD" name="day" id="day" value="" maxlength="2">
  <input @input="$v.month.$touch()" v-model="month"  type="text" placeholder="MM" name="month" id="month" value="" maxlength="2">
  <input @input="$v.year.$touch()" v-model="year"  type="text" placeholder="YYYY" name="year" id="year" value="" maxlength="4">
</div>
```

When a field is touched, the validation updates, but I get errors in the console:

> Uncaught TypeError: Cannot convert undefined or null to object
>     at Function.keys (<anonymous>)
>     at VueComponent.keys (index.js:289)
>     at Watcher.get (vue.runtime.esm.js:2877)
>     at Watcher.evaluate (vue.runtime.esm.js:2984)
>     at VueComponent.computedGetter [as keys] (vue.runtime.esm.js:3261)
>     at VueComponent.proxy (index.js:296)
>     at Watcher.get (vue.runtime.esm.js:2877)
>     at Watcher.evaluate (vue.runtime.esm.js:2984)
>     at VueComponent.computedGetter [as proxy] (vue.runtime.esm.js:3261)
>     at Object.get [as number] (index.js:301)

This doesn't happen on projects built without Nuxt...i.e. just the Vue Cli.

Any ideas what's going on? Or, where _I'm going wrong_?

Is this something to do with `$v` in the templates?

**Comment by Human-Connection** [comment]
had some one any success?

**Comment by syamkumarkk** [comment]
Is the $v will work in NuxtJs ?

**Comment by syamkumarkk** [comment]
> plugins: [
>   { src: '~plugins/vuelidate', ssr: false }
> ]

**$v** should be render from server.  Hence, should use SSR "true" ...
```
plugins: [
  { src: '~plugins/vuelidate', ssr: true }
]
```
