### ISSUE TITLE
Cannot add plugin with browser bundle

### ISSUE THREAD

**Issue by pohnean** [monterail/vuelidate#15]
Says 'Cannot read property 'installed' of undefined'.

Also how do you add custom validations at runtime? It's not described in the documentation.

btw, excellent idea, i was looking for a validation library that works on models as well.

**Comment by Frizi** [comment]
Hi, I'll take a look into the browser bundle issue in a second.

You don't have to register your validators in any special way, as those are simply just functions. Use them directly in your validation object.

```
// custom validator function, can by anything
const myCustomValidator = (value) =>
  typeof value === 'string' && value.startsWith('custom')

// validation object in your Vue component
validation: {
  field: {
    myCustomValidator
  }
}
```

**Comment by Frizi** [comment]
Right, we've got the names in docs wrong. It should be
```javascript
Vue.use(window.vuelidate.default)
```

Please check if it works for you, and I will update docs shortly.

**Comment by pohnean** [comment]
works now, thanks!

just a note though: the documentation wasnt clear that you need to load validators.min.js too (if you are not using a module loader)

**Comment by shentao** [comment]
Good point! We’ll add it to the docs :)
