### ISSUE TITLE
Validate required and numeric unless other_field = true

### ISSUE THREAD

**Issue by mickiii** [monterail/vuelidate#151]
Can't seem to find any examples of validations referencing other fields. Basically what I am trying to accomplish is validate a model (nested), unless another field is set to true. Is this even possible? I though I could use requiredId or requiredUnless, but I cannot find any example of this. 

Thanks in advance!

**Comment by Frizi** [comment]
There are many many ways to do it. Starting from the most obvious one, you can simply ignore the validation on your UI if the field is not set. The more consistent way would be using `requiredIf` indeed, like
```javascript
const requiredIfMyField = requiredIf(function () { return this.myField === true })
...
validations: {
  nested: {
    fieldA: { requiredIfMyField },
    fieldB: { requiredIfMyField, email }
  }
}
```

Third option is to make `validations` dynamic, like
```javascript
const alwaysOK = { OK: () => true }
...
validations () {
  return {
    nested: {
      fieldA: this.myField ? { required } : alwaysOK,
      fieldB: this.myField ? { required, email } : alwaysOK
    }
  }
}
```

There are probably many more than that anyway. Vuelidate lives you many options and you are free to use anything that fits you the most.

Personally I'd probably go with modified third option to make it a bit more concise, but I'm biassed.
