### ISSUE TITLE
Cannot scroll down on the website navigation.

### ISSUE THREAD

**Issue by mesqueeb** [monterail/vuelidate#152]
I use Macbook 10 inch. And I cannot scroll down far enough on the docs + the text of the nav and the body overlap...
I usually browse half screen size.

See screenshot:
<img width="750" alt="2017-06-12 21 35 07" src="https://user-images.githubusercontent.com/3253920/27046846-056f984e-4fb7-11e7-9987-4109ec0dece6.png">

**Comment by Frizi** [comment]
Should be fixed now
