### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by mesqueeb** [monterail/vuelidate#153]
How can I use the CSS your website uses for the inputs? it's beautiful.

**Comment by shentao** [comment]
Most of the CSS is based on my old css-framework-like library that we intended to open-source. Not sure if that’s possible right now (the web already moved past bootstrap like css-frameworks with BEM class names).

However, if you would like to create your own documentation based on this one, we have a vue-cli template that makes it able to bootstrap the docs. It still needs some tuning after the recent migration to webpack 2 before we’re able to publish it.

**Comment by Frizi** [comment]
Glad you like it 😄 (thanks @shentao :+1:) There is no separate repository with all the components openly published right now unfortunately. But you could just grab it as it is from the docs in this repo. Keep in mind it's written in SASS, you will have to compile it.

**Comment by FrancescoMussi** [comment]
Completely agree!
Already it is a very useful component!
With that style included it would be amazing!
