### ISSUE TITLE
Required validator returns "false" for date objects

### ISSUE THREAD

**Issue by troxler** [monterail/vuelidate#158]
I work on a form that uses vuelidate to validate computed properties. They are used to get date objects from the form input and perform some custom validators. I also tried to use the `required` validator, but it (or more specific, `req`) returns `false` for date objects.

See here for a demo https://jsfiddle.net/82b3fLrv/1/

I do realize that I can just implement another custom validator that also handles date objects. But maybe this is something that might be interesting for others as well. I guess some date pickers rely on date objects and validating them as objects might thus be easier.

**Comment by Frizi** [comment]
Your demo is broken (bad way of using computed), but you are right. Here is a fixed demo: https://jsfiddle.net/82b3fLrv/2/

I think `required` should treat any valid date object as OK, for date ranges I'd expect a separate validator would be good to. I'll add the date object support.

**Comment by Frizi** [comment]
Fixed, will be relased with next version.

**Comment by troxler** [comment]
@Frizi Awesome, thank you :)
