### ISSUE TITLE
need help, about Custom validators with .vue

### ISSUE THREAD

**Issue by hasbug** [monterail/vuelidate#159]
i Want to make sure a input field is a valid phone，but it  make some wrong。
```base
Confirm.vue?d755:17 named exports are not supported in *.vue files.
```

```javascript

    import { required, minLength, between, withParams } from 'vuelidate/lib/validators'
    export default withParams({type: 'isPhone'}, value => /^(\d{15}$|^\d{18}$|^\d{17}(\d|X|x))$/.test(value));
export default {
  data () {
    return {
      phone: '',
    }
  },
  validations: {
    phone: {
    phoneValid:isPhone
    },
  }
}
```

**Comment by hasbug** [comment]
sorry ,i got it.
do it like this
```javascript

    import { required, minLength, between,withParams } from 'vuelidate/lib/validators'
   const isPhone = (value) => /^1(3|4|5|7|8)\d{9}$/.test(value);  //phone valid
export default {
  data () {
    return {
      phone: '',
    }
  },
  validations: {
    phone: {
    phoneValid:isPhone
    },
  }
}
```

**Comment by hasbug** [comment]
1.

**Comment by Stetzon** [comment]
Can I use `isPhone` as part of the `methods` object?  I have tried a few variations of the following and I can't get it to work correctly:
```
methods: {
  isPhone() { ... }
},
validations: {
  phone: {
    phoneValid:isPhone
  },
}
```

**Comment by peoray** [comment]
> sorry ,i got it.
> do it like this
> 
> ```js
>     import { required, minLength, between,withParams } from 'vuelidate/lib/validators'
>    const isPhone = (value) => /^1(3|4|5|7|8)\d{9}$/.test(value);  //phone valid
> export default {
>   data () {
>     return {
>       phone: '',
>     }
>   },
>   validations: {
>     phone: {
>     phoneValid:isPhone
>     },
>   }
> }
> ```

How do I use this in my template to check for error and display the error message?

**Comment by dobromir-hristov** [comment]
Use the error extractor plugin for template error display

**Comment by mhmmdrzkh9977** [comment]
const isPhone = (value) => /^\+?[0-9]+$/.test(value)
