### ISSUE TITLE
how to trigger validation in a single step

### ISSUE THREAD

**Issue by rifaideen** [monterail/vuelidate#162]
how to validate all the fields? let say I am in a form wizard and I want to validate all the input when user clicks next step., how to do that?

**Comment by Frizi** [comment]
Validation happens automatically when you try to read it state. Simply check `$v.$invalid` in your method before redirecting to the next step.

**Comment by rifaideen** [comment]
ok, what about custom error message based on type of validation failed.

Thanks & Regards,
- Rifaudeen

**Comment by Frizi** [comment]
Use any translation lib and use `$params` key as it's input.

**Comment by luisfpc91** [comment]
How do I validate the fields of the step alone?
when using $ v. $ invalid it marks me error because the fields of the other step are empty.
