### ISSUE TITLE
Question: Is it possible to run the validation engine in node.js for server-side model validation?

### ISSUE THREAD

**Issue by Nick-Riggs** [monterail/vuelidate#165]
I like vuelidate but I wonder if I can gain some code reuse by using the model validation rules on both the client and the server. Is there a way to use vuelidate's validation engine in a node.js environment without a dependency on Vue?

**Comment by autumnwoodberry** [comment]
Vuelidate uses the vue instance heavily so I doubt this would ever be possible.

**Comment by Frizi** [comment]
Without the dependency on Vue, not really. You could reuse the validators, as those are pure functions, but the whole engine has a hard dependency on vue.

But, if you don't mind the dependency, it should work just fine for your backend as well.

There actually is nothing preventing you from using Vue just for model. Recent versions of vuelidate are working perfectly fine in any SSR solution, which means it can just run on node. You don't have to actually invest into full backend-on-Vue solution to make use of it though. Vue instances are very useful as a standalone thing too anyway.

You could define a model for validation just fine without using any render logic.
```javascript
Vue.use(window.vuelidate.default)
const { required, minLength } = window.validators

const validate = (data, validations) =>
  new Vue({ data, validations }).$v

// ... somewhere in your backend logic
const validationTree = validate(
  {someData: 'hello'},
  {someData: { minLength: minLength(2) }}
)

console.log(JSON.stringify(validationTree, null, 2))
```

This code will run just fine in the browser and in node server. https://jsfiddle.net/9m1bwcyh/

Notice that validators are lazily evaluated. That means if you don't ever read out `validationTree.someData.$invalid`, the `minLength` validator will not run.
