### ISSUE TITLE
Auto touching validation properties

### ISSUE THREAD

**Issue by robodude** [monterail/vuelidate#167]
A very common use case, is I need to validate a text field but I only want to show the validation messages on $error. What I find myself doing, is writing a validations statement and and a watch statement that is 1 to 1.

```
        watch: {
            date() {
                this.$v.date.$touch()
            },
            time() {
                this.$v.time.$touch()
            },
            url() {
                this.$v.url.$touch()
            }
        },
        validations: {
            date: {
                required
            },
            time: {
                required
            },
            url: {
                required,
                url
            }
        },

```

It would be great if I could set something up like:

```
        validations: {
            date: {
                required,
                autoTouch: true
            },
```

**Comment by Frizi** [comment]
You don't want to do that really, as any external data change (like preloading data from backend) would touch the field too. What you can write instead for your special case is either a custom mixin that autogenerates both `watch` and `validators` objects from common config or a form component that gets both data and it's validator, then handles displaying errors and abstract aways the `@input` binding.
