### ISSUE TITLE
Custom Validator: req, withParams use in project file

### ISSUE THREAD

**Issue by franz-josef-kaiser** [monterail/vuelidate#168]
We just had a situation where one of our designers needed to add a custom validator. The [`src/common.js`](https://github.com/monterail/vuelidate/blob/1f21cf649e56bed942c891c464276196e14fd240/src/validators/index.js) does not export what is shown in the [_"Custom Validators"_ Section](https://monterail.github.io/vuelidate/#sub-custom-validators) in the documentation:

```js
import {withParams, req} from './common'
export default withParams({type: 'required'}, req)
```

The `withParams` and `req` object get imported from the module with a _local_ path. How would one import it inside a project when adding validators to the project folder? Thanks!

**Comment by Frizi** [comment]
Sure, that's a fail on documentation part. I never intended to make those `common` building blocks public, as those are not validators really. I refactored them out once and forgot that docs are autogenerated from the source. As you can see in the code you pasted in, `required` is an public equivalent of `req`. Also `withParams` is exported from `vuelidate/lib/validators`.

First of all, if you are not using `$params` in your application, you can skip this altogether and simply write a JS function.
```javascript
export const isHello = value => value === 'hello'
```

If you want to use meaningful `$params` with that, you have to wrap it in `withParams`.

```javascript
import {withParams} from 'vuelidate/lib/validators'
export const isHello = withParams({type: 'isHello'}, value => value === 'hello')
```

**Comment by franz-josef-kaiser** [comment]
Shall we leave this open as commit and PR target until the doku is fixed?

**Comment by shanemgrey** [comment]
I've looked at the example in #31 but that doesn't seem to work for me. I was able to follow the "with_params" example in #137 and get it to work, but don't really understand the need for withParams and can't find any instruction on it in the docs. 

For this one I just have a simple case where I want to check is a string is a valid date.  (This works)

```import { withParams } from 'vuelidate/lib'
import isValid from 'date-fns/is_valid'

export default withParams({ type: 'isValidDate' }, dateValue => {
  if (dateValue) {
    return dateValue.length === 10 ? isValid(new Date(dateValue)) : dateValue.length === 0
  }
  return true
})
```

But for my next validation, I need to check that the date given is after a date in another field.  

How can I pass both values to the function to be compared?  

A specific solution would be great, but even better would be a more generalized writeup on how to make custom validators that have access to values in the data model. 

I'm not trying to take over this thread, but it seems like the right place to post about the docs being unclear on custom validators.

**Comment by pjar** [comment]
Just wanted to leave a note that I'm wandering in issues tab to get more understanding of how custom validators should be written. Good to see I'm not the only one confused about them.

**Comment by Frizi** [comment]
@pjar I do see that trend, but I also notice that people simply expect certain things to be more complicated than really required. Just write a plain old function. Anything that takes a value and returns a boolean (or Promise<Boolean>) will do just fine. The only necessary complication arises when you plan to use `$params` feature. In that case `withParams` wrapper will help you. I bet thought that this feature is rarely used.

**Comment by vinstah** [comment]
It looks like you can now use `import { withParams } from 'vuelidate'` instead of `'vulidate/lib/validators'`

**Comment by phcoliveira** [comment]
I can't `import { withParams }` from nowhere. Places I tried:
- `"vuelidate"`
- `"vuelidate/lib/validators"`
- `"vuelidate/lib/params"`
- `"vuelidate/lib/withParams"`
- `"vuelidate/lib/withParamsBrowser"`
- `"vuelidate/lib/validators/common"`

I got a reference error for `process` is `undefined`.

Here is the call stack:
```
index.js?ca99:3 Uncaught ReferenceError: process is not defined
    at eval (index.js?ca99:3)
    at Object../node_modules/process-nextick-args/index.js (app.js:3153)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
    at Object.eval (_stream_readable.js?46dd:26)
    at eval (_stream_readable.js:1016)
    at Object../node_modules/readable-stream/lib/_stream_readable.js (app.js:3215)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
    at eval (readable-browser.js?7125:1)
```

**Comment by Frizi** [comment]
I don't have much time lately to improve the docs on my own, but If anyone would make a PR I'll find a moment to review it and release.

**Comment by agriboz** [comment]
thank you @vinstah for clarifying us :)

**Comment by Frizi** [comment]
@ AlexandreBonneau I'm not sure if this is on purpose, but you pointed out two solutions that actually are implemented :D  Validators are both bound to component instance and it's also passed as a second argument for convenience. Remember that arrow functions doesn't carry context, you have to use full functions (or second param). You've got a point on docs though :) I'll soon have some time budget to work on vuelidate again, so I'll might address that. PRs are always welcome too!
