### ISSUE TITLE
How pass data object value to validators?

### ISSUE THREAD

**Issue by R00118189** [monterail/vuelidate#169]
amount: {
                required,
                between: between(this.min, this.max),
            },

I am new to JS so probably this is some fundamental mistake
I want dynamically set validation numbers the amount is to be between 

https://jsfiddle.net/bjurgxnw/1/

**Comment by jfis** [comment]
I think Dynamic Validation Schema is what you're looking for.
https://monterail.github.io/vuelidate/#sub-dynamic-validation-schema

https://jsfiddle.net/bjurgxnw/4/
