### ISSUE TITLE
Provide documentation for no-ECMAScript enviroment

### ISSUE THREAD

**Issue by sekys** [monterail/vuelidate#170]
Hello guys,

i am using Vuelidate with RequireJs, but without ECMAScript. I spent 3 hours trying to install and init this library. So i think it is good idea to enhance documentation for this type of installation.

First i tried make your example compatible without ECMAScript. So i added value "true" to "required" rule. Bad decision. Actually this create new attribute, not a validator rule.
```
email: {
	required: true
},
```

The proper way to install:
```
vuelidate = require('vuelidate/dist/vuelidate.min.js');
validators = require('vuelidate/dist/validators.min.js');
Vue.use(vuelidate.default);
```
The proper way to define rule:
```
validations = {
	email: {
		required: validators.required,
		minLength: validators.minLength(4),
		email: validators.email
	},
	password: {
		required: validators.required,
		minLength: validators.minLength(4)
	}
};
```
Thank you for a great library.

Lukas

**Comment by michaelsogos** [comment]
@sekys  I guess there is a misunderstanding about what is ECMAScript, what you done in your example is exactly an ES5 (or ECMAScript 5) code.
ES5 is actually the browser standard javascript language (from javascript 1.8) since 2010 (if i'm not wrong).

However i agree with you, i had the same exactly needs to work in pure browser environment, and the example supplied was not compatible.

Thanks for your help!

Can i suggest you to change issue title in something like "Provide documentation for standard browser javascript"?

**Comment by michaelsogos** [comment]
@Frizi Do you have plan to add ES5 example? Is time wasting open validators.js file all the time to remember which is the name of the function  :)

**Comment by Frizi** [comment]
@sekys I'm glad you managed to run that, though I think ES2015 syntax for imports and shorthand object values is considered standard today, and in case you still need some help understanding it, this libraries docs are surely not a place for that. If you will be facing similar problems in the future, I can advice you to paste the code to http://babeljs.io/repl, so you can understand it better and learn how to translate it manually.

BTW, docs do use custom validator rules in a few places as an example. There are some methods even. This should give you a hint that the key name in validation object is something that you choose as a library user. It is not constrained in any way.

**Comment by clemsontiger** [comment]
@sekys, do you have a working example of using Vuelidate with RequireJs?

**Comment by clemsontiger** [comment]
@sekys nevermind, I have it all working.
