### ISSUE TITLE
An error message is always displayed

### ISSUE THREAD

**Issue by VilmantasSaulys** [monterail/vuelidate#173]
Hello, 

I am new in VueJS and I am stuck with error messages of form validation. 
In my form error message always displayed. I want to make that error message will be display after keyup. 
How can I make it? My code: http://prntscr.com/g91qy5

**Comment by Frizi** [comment]
You have to check for `$dirty` flag. Normally `$error` does that for you, but it checks for all errors in given context, not specific ones. What you could do now is to wrap all your errors into a template and do `v-if="$v.email.$error"` on it.
