### ISSUE TITLE
between is not working!

### ISSUE THREAD

**Issue by bichikim** [monterail/vuelidate#174]
https://jsfiddle.net/bichi/b5v4faqf/237/

between is not working!

**Comment by Frizi** [comment]
What's not working for you? It works perfectly for me in your fiddle.

**Comment by Frizi** [comment]
I'm closing this not seeing any problems. If you still can see a bug, please descrive it and reopen.

**Comment by anieruddha** [comment]
While developing, I am facing same issue. I tried fiddle link, between also not working for me.  I am using Mac, tested on safari & chrome.

**Comment by kevinkneifel** [comment]
I am also having this problem.

**Comment by immortalx** [comment]
The fiddle link is working for me on a Mac, tested on firefox and chrome.

**Comment by ijklim** [comment]
Guess there was a confusion between (sorry for the pun) **number of characters** and a **number between min and max**. I was thinking the number of characters in the beginning, then I realize <code>between</code> should be used to validate number only, not the number of characters.

**Comment by Frizi** [comment]
@ijklim This might indeed be true, though i specifically state in the docs that `between` is designed to work with numbers and dates.

**Comment by ijklim** [comment]
@Frizi Nothing wrong with the code or the documentation, just user error mainly. As a habit, I tend to start using a new plugin base on examples without reading all the documentation. Hit a problem, start googling.

Hopefully threads like this will give users who use the function with incorrect expectation an 'ah-hah' moment. In this case, I just use minLength and maxLength instead.

Great plugin btw, appreciate it.
