### ISSUE TITLE
Wait for async validations to finish

### ISSUE THREAD

**Issue by d-levin** [monterail/vuelidate#179]
Is there a straight-forward way to wait for async validations to finish before continuing in a function? For example, if I hit a submit button in a form I want to first validate and submit only if valid. But $touch() doesn't return a promise so I can't wait for the async validations to finish.

An ugly workaround I wrote polls $pending on a fixed interval and returns a resolved Promise once $pending is false.

**Comment by Frizi** [comment]
As the validation is simply a computed value, you can use watches to do this.
```javascript
methods: {
  validPromise () {
    return new Promise((resolve) => {
      const unwatch = this.$watch(() => this.$v.$valid, (isValid) => {
        if (isValid) {
          unwatch()
          resolve()
        }
      }
    })
  },

  async myButtonClicked () {
    this.$v.$touch()
    await this.validPromise()
    doSomethingWhenValidationPasses()
  }
}
```

You can possibly cache that promise too, which would create just one watcher when function is called multiple times.

**Comment by d-levin** [comment]
Genius! Thanks!

**Comment by d-levin** [comment]
Actually I can't seem to get that to work either.

I'd love to be able to do something like this:
`
async submit () {
  const isValid = await this.validate()
  if (!isValid) {
    return console.log('validation failed')
  }

  // else keep going
`

**Comment by Frizi** [comment]
Just change your watch to `!this.$v.$progress`

**Comment by hooblei** [comment]
For the record - `unwatch` is undefined when using `{immediate: true}` since the callback is called before the `unwatchFn` is returned - see [$watch](https://github.com/vuejs/vue/blob/94512f3e8cee4030a1096121700ed49afab48073/dist/vue.runtime.common.js#L3423)

**Comment by d-levin** [comment]
The issue with that solution is that `myButtonClicked()` will continue immediately after the user fixes the validation issues which I think results in a really strange user experience. I simply want this flow to be possible:

1. Fill out form
2. Click Submit button
3. Disable button
4. Wait for async validations to complete
5. Submit form-data to API
6. Wait for API to respond
7. Enable button

**Comment by flybayer** [comment]
I totally agree with @d-levin. It'd be ideal for `touch()` to return a promise.

**Comment by archSeer** [comment]
Agreed with the other commenters, please consider reopening this issue.

**Comment by pkraus109** [comment]
Agreed this seems like a really normal workflow.
Fill out form,
submit, 
validate,
send to server

touch() returning a promise would be very useful.

**Comment by jnarowski** [comment]
Is there any updates on this? I am struggling to figure out how to allow my form to be submitted with async validations. huge +1 for touch() returning a promise here, or adding another method that does return a promise. 

What's the cleanest way to solve this problem now as it stands?

**Comment by Marivint** [comment]
@d-levin Thank you for your solution, I used it for a company that has not yet updated the library.
