### ISSUE TITLE
Production?

### ISSUE THREAD

**Issue by daslicious** [monterail/vuelidate#18]
Can this be used in production?

**Comment by shentao** [comment]
We’re yet to release the 1.0 version. We started from 0.1 to have the flexibility to make some breaking changes if needed before we reach 1.0, but I hope this won’t be necessary.
After that we will try to stick to semver.

**Comment by Frizi** [comment]
There are no planned API changes, but anyway we wanted to make sure we haven't missed any crucial usecases. We also want to add Async validators before going 1.0, but it is expected to be mostly additive change. There should be no breaking changes in the process.

**Comment by daslicious** [comment]
Thanks
