### ISSUE TITLE
alphaNum validation is not working?

### ISSUE THREAD

**Issue by emjimadhu** [monterail/vuelidate#180]
i have a problem, im not sure whther the problem from my end or the component itself. It seems the `alphaNum` validator is not triggering error?

heres the codepen 

'https://codepen.io/emjimadhu/pen/xLBYyp?editors=0010'

in that codepen, if you change the validators to `alpha` or `numeric`, it does trigger the error message. but for `alphaNum` it doesnt trigger the error message.

And one more additional question, how can i add a custom validation with exsisting validation. say for example, i wwant to use `alphaNum` with one letter to be Uppercase. how can i achieve that?

**Comment by Frizi** [comment]
Hi, I tried and it triggers for me, of course when the input is not alphanumeric. Try inputing any symbol, like `!` and it should trigger.

As for usage of custom validations, it's simply a function so you can call it.
```javascript
const capitalized = (value) => {
  return (
    typeof value === 'string' &&
    (value.length === 0 || value[0] === value[0].toUpperCase())
  )
}

const capitalAlphanum = (value) =>
  return alphaNum(value) && capitalized(value)
```
Though it's probably better to keep them separated and just use both.

```javascript
myField: {
  capitalized,
  alphaNum
}
```

**Comment by emjimadhu** [comment]
@Frizi  hey thank you for the clarification.. now i understand it.. i thought it will force user to enter atleast one alphabet and one numeric.. but basically what it does is, it will not let user to enter anything except alpha numeric character.. thank you..

is thier a way i can force user to enter atleast one alphbet and one numeric?

**Comment by Frizi** [comment]
You can write a validator that checks exactly that condition 😉

**Comment by emjimadhu** [comment]
@Frizi hey thank you so much man.. you can close it now..
