### ISSUE TITLE
[Suggestion] Other validators / contrib?

### ISSUE THREAD

**Issue by robcresswell** [monterail/vuelidate#184]
Had a couple of suggestions for common validators in an corporate setting:

* IP fields (v4 / v6)
* MAC address

I'd imagine these are common enough in usage that a common implementation would be helpful; however, I can understand not wanting to bloat the core library. If it's unacceptable to have these in the core library, would you consider a wiki or other piece of documentation that links to external open source validators? For example, if I could push something like `vuelidate-ip-validator` to GitHub, it would seen sensible to have that referred to here to prevent others writing their own implementations.

Thanks

**Comment by Frizi** [comment]
Sure, though you are free to use any exiting library that provide validation functions, treating the vuelidate only as a validation engine. The only additional thing that could be added specifically for vuelidate is `withParams` usage, so you can get the feedback from validator function about it's configuration. This is optional though, useful only when you plan to use `$params` property.

Validators are already separate from the core anyway. The only problem is that "web" bundle contains them all in single file, `validators.min.js`, so you can't opt-out from using them. Having them in separate files would help and we can continue to add even less frequently used validators to this repo. I'm not sure if splitting the packages is necessary and any beneficial. It's not as general purpose as lodash for example.

BTW, I'm actually using exactly IP fields and mac addresses in my project with Vuelidate 😄

**Comment by robcresswell** [comment]
Ah, I see now. I'm only including things in a modular way anyway; I just expected you may be against bloating the web bundle with other validators. Would you consider putting your IP / MAC validators upstream? I know it would certainly save me time at the very least, and I can imagine there are / will be many others who are likely to use them.

**Comment by Frizi** [comment]
I should be able to write a few network related validators for sure. Not necessarily upstreaming what I already have (as it's a bit wired into the internal structures), but something a bit simpler. Ideally i would like to just add them like crazy to the current list. Tree shaking gets rid of unused modules anyway, so it's not an issue on users end. The only problem I see is the web bundle, but then having a fat "all things included" should be all right for prototyping. Optimisation may come later when the problem will manifest itself, and when somebody cares about their overall bundle size, they are not using web bundles anyway. Correct me if I'm wrong please.

The documentation needs a serious overhaul to cope with that though.

**Comment by robcresswell** [comment]
I agree with everything you said. Web bundle should be dev only anyway. My suggestions were merely cautiousness. Please let me know if I can help, I'd be happy to.

**Comment by robcresswell** [comment]
Hey there; any traction on adding new upstream validators? Anything I could do to help?

**Comment by Frizi** [comment]
I just implemented`ipAddress` and `macAddress` validators in https://github.com/monterail/vuelidate/pull/199. I think this scheme of adding new validators to existing bundle should work for a good while and we don't have to change anything in packaging, thus i consider this resolved.

**Comment by robcresswell** [comment]
Oh, fantastic. Thanks so much!
