### ISSUE TITLE
Nested validations don't play well requiredIf/requiredUnless and computed properties

### ISSUE THREAD

**Issue by xavier** [monterail/vuelidate#185]
When using nested validations, it's not possible to use `requiredIf` (or `requiredUnless`) using a computed property.  The conditional validation will attempt (and silently fail) to get the property from the nested object rather than from the component instance itself .

See fiddle: https://jsfiddle.net/kqh4ebq8/2/

Is there a way to work around this issue?

**Comment by Frizi** [comment]
That behaviour is intended and the construct you need is supported as 
```javascript
requiredIf(function () { return this.isRequired })
```
https://jsfiddle.net/Frizi/kqh4ebq8/3/

The locator semantic is documented under `sameAs` description in the docs. I see it might be a bit poorly placed though.

**Comment by xavier** [comment]
Thanks for the quick feedback. This should do the trick, thanks a lot! 👍 

The documentation about `requiredIf` is indeed a bit lacking, the concept of locator should perhaps be defined and explained before it's first mentioned in the validators table. 😉 

I've read this sentence 3 times and I still cannot make any sense out of the second half of it:

> Locator might be either a sibling property name or a function, that will get your component as this and nested model which sibling properties under second parameter.

Shouldn't 'which' be 'with'? And what 'second parameter' are we talking about?

Btw, after some additional research, I figured out that I was passing arrow functions to `requiredIf`, the binding of `this` was thus ineffective. /facepalm

Should I open a PR to try improving this part of the documentation?

**Comment by Frizi** [comment]
@xavier PR would be awesome 💛 I'm surely not the best at describing things in documentation for sure, every help is greatly appreciated 👍

**Comment by Frizi** [comment]
I guess we can consider this closed after PR was merged
