### ISSUE TITLE
Vuelidate doesn't fire on created() - unable to correctly validate pre-filled values

### ISSUE THREAD

**Issue by sergiocastrovale** [monterail/vuelidate#188]
https://jsfiddle.net/pofm0mgr/

This is problematic in cases you have a multi-step form with a back button in each step; if you click back to the previous step you'll get the pre-filled form but the form will be marked as erroneous by vuelidate since the required fields were not sync'd. 

As soon as we touch each of the required fields, then the form is accepted as valid.

**Comment by Frizi** [comment]
I'm not sure I understand. Vuelidate fires whenever you read it, always using the data that's currently in the model. Just like a computed value. I suppose you might be confusing `$error` with `$invalid`. You should first of all make the submit button logic dependant on `$invalid` field only. The `$dirty` flag is set to true by calls to `$touch` method, and it's your choice when to call it. If you want to visually **mark the errors** when you go back in your wizzard, you can call `$touch` on the whole `$v` object.

**Comment by sergiocastrovale** [comment]
@Frizi you are correct - I was indeed using $error in the wrong place. Thanks!
