### ISSUE TITLE
Release request for required Date fix

### ISSUE THREAD

**Issue by mattixittam** [monterail/vuelidate#189]
Hi, any reason not to put out a release for the Date fix in the required validator that went in a few months ago? (Which I ran into, fixed locally, then discovered it was already in the codebase :) ).

I can install directly from GitHub of course, but I would prefer sticking with actual releases for our production software, to minimize the risk of bugs.

**Comment by mattixittam** [comment]
Cool, tnx!

**Comment by Frizi** [comment]
Release done :) It was a bit overdue, but I was finally able to finish that.
