### ISSUE TITLE
Force Validate

### ISSUE THREAD

**Issue by nnjeim** [monterail/vuelidate#190]
Hi,

i am using validate on exsiting data in a modal view... errors are displayed as if vuelidate is fired before the data is populated. 

Any existing method to re-validate ?

thanks

**Comment by Frizi** [comment]
Vuelidate is reactive, it revalidates continuously when you ask for validation state. What's your issue/use case here?

**Comment by nnjeim** [comment]
hi frizi,
thanks for the time spent to reply... i am combining vuelidate with vutify and the issue seems to be not related to vuelidate. Any best practice to be shared here? Sorry it might be the wrong place to post this.
Any forum related to vuelidate maybe?

**Comment by Frizi** [comment]
There is no forum, so this is the best place for such post currently. Documentation holds many "best practices" IMHO, also there are many closed issues with solutions to different problems which you might be interested in.
