### ISSUE TITLE
Select Vuelidation Incorrect on Initial Selection

### ISSUE THREAD

**Issue by IDontKnowMyUsername** [monterail/vuelidate#192]
Vuelidation not correctly working for select boxes in Google Chrome and Safari for initial selection.   Subsequent selections seem to correctly apply vuelidation.
Vuelidation works in Firefox even though the third select box where label/value pairs for options are not recognized.

Browsers used:
Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)
Safari Version 11.0 (11604.1.38.1.7)
Firefox 55.0.3 (64-bit)

JSFiddle:
https://jsfiddle.net/6dupwfpf/

**Comment by Frizi** [comment]
Hi, it seems it's a bug in vue. When class on select box is changed in input handler, it prevents the update. I created the issue upstream.

https://jsfiddle.net/6dupwfpf/6/

**Comment by waseemprojectmarker** [comment]
Try to use @change instead 0f @input
