### ISSUE TITLE
Vuelidate does not observe change in date picker

### ISSUE THREAD

**Issue by laliluna** [monterail/vuelidate#194]
https://codesandbox.io/s/52143q5z44

HINT: the sandbox worked for me only in Safari. In components/Hello.vue you will find a form with two inputs. The required validation works for the text field but not for the date picker component. If I choose a value the field is still marked as required. How can I deal with this component?

**Comment by laliluna** [comment]
The issue is that the date picker sets a date which is not recognized by vuelidate. See a working example here:
https://codesandbox.io/embed/pwj2n2yor0?module=%2Fcomponents%2FHello.vue

**Comment by Frizi** [comment]
Hi :) This is due to the fact how datepicker decides to update this date object. Vue will not make Date object observable, you have to force set it's value again via Vue.$set or by creating new object. Your actual solution is one way to deal with that, but you don't need to convert to string. You can just clone the object and assign.

**Comment by laliluna** [comment]
Hi Frizi!
I tried to validate what you said. But I could not confirm it. See here all the variants, I played with. It looks as if date change are just not observed. 

`onDateChange(date) {
      // works
      // this.bike.lastChangeDate = date.toISOString()
      //this.bike = Object.assign({}, this.bike, {lastChangeDate: date.toISOString()})
      //this.$set(this.bike, 'lastChangeDate', date.toISOString());

      // fails
      //this.$set(this.bike, 'lastChangeDate', date);
      //this.$set(this.bike, 'lastChangeDate', new Date());
      //this.bike = Object.assign({}, this.bike, {lastChangeDate: date})
    },`


On the other hand should not be a explicit $v.bike.lastchangeDate.$touch() trigger a validation on that field?

Cheers Sebastian

**Comment by Frizi** [comment]
You have to do `this.$set(this.bike, 'lastChangeDate', new Date(date));`
If the date object doesn't get new instance, it's not triggering the watchers and render function is not rerun. This is not specific to vuelidate.

https://jsfiddle.net/dec971ju/
