### ISSUE TITLE
Using computed values to render the class

### ISSUE THREAD

**Issue by DaniG2k** [monterail/vuelidate#196]
Hello, sorry if this is a bit of a n00b question but I am wondering how I can use computed values to determine the class of a field. I am trying with something like:

```
new Vue({
  el: '#listing-multistep',
  validations: {
    name: {
      required,
      minLength: minLength(4)
    }
  },
  computed: {
    validateClass: function() {
      return {
        'form-control': !$v.name.$dirty,
        'form-control is-invalid': $v.name.$error,
        'form-control is-valid checkmark': (!$v.name.$invalid && $v.name.$dirty)
      }
    }
  },
```

but this doesn't seem to work, I believe because `$v` is not accessible within the scope of computed properties. What would be a good way to set the classes for each form control?

Thanks in advance

**Comment by Frizi** [comment]
`$v` is accessible in any scope you wish, you just have to access it on your instance. Try with `this.$v`. Also your class syntax is a bit off. Make `form-control` a static class (ordinary `class="form-control"`, and add a second `:class="validateClass"` for dynamic classes. Then, you have to only specify those:
```
{
  'is-invalid': $v.name.$error,
  'is-valid checkmark': $v.name.$dirty && !$v.name.$error
}
```
