### ISSUE TITLE
minValue & maxValue not functional with dates

### ISSUE THREAD

**Issue by mattixittam** [monterail/vuelidate#201]
The minValue and maxValue validators don't seem to take into account dates. Seems a few casts would suffice as a fix:

old
`value => !req(value) || (!/\s/.test(value) && value >= min)`

new
`value => !req(value) || (!/\s/.test(+value) && +value >= +min)`

**Comment by Frizi** [comment]
Hey, that's reasonable :) I would be very happy if you can provide a PR for that.

**Comment by mattixittam** [comment]
Yup, will do.

**Comment by Frizi** [comment]
Thanks, merged :) closing
