### ISSUE TITLE
Maximum call stack when using validations in mixin

### ISSUE THREAD

**Issue by mokkabonna** [monterail/vuelidate#202]
https://jsfiddle.net/b5v4faqf/321/

I provide a global mixin like this:

```js
Vue.mixin({
  validations() {
    return {
      foo: {
        required
      }
    }
  }
})
```

This results in a maximum call stack when run. See the fiddle. Make sure to click run.

However if I provide it as a local mixin then it works fine: https://jsfiddle.net/b5v4faqf/320/

Not sure if this is an issue with vuelidate or not. Could be an issue with Vue. But thought I'd open an issue here anyway.

Note that I think it does not have to do with the merge strategy, here is a simpler example: https://jsfiddle.net/b5v4faqf/325/ This merge strategy only take whatever it can get, either the mixins validations or the vm validations.

EDIT:

It does seem to have something to do with vuelidate, here is a simpler example that fails: https://jsfiddle.net/b5v4faqf/335/ But it works if I remove the Vue.use call:  https://jsfiddle.net/b5v4faqf/337/

**Comment by Frizi** [comment]
Please do not do this. You are abusing global mixins heavily with that. You are now forcing vuelidate to run on every single component instance in the whole application, including the instances that are internal to vuelidate or vuex. This is not a valid usecase for global mixins.

The way vuelidate registers itself as a global mixin is by checking first if there is a `validations` key on the instance. You are adding it to every single one ever created.

What is your usecase that you are trying to accomplish? I believe there is a simpler and better solution. Global mixins are really a feature of last resort.

**Comment by shentao** [comment]
Whoa 😱

**Comment by mokkabonna** [comment]
Hmm ok. Thanks for the quick feedback. It is for this plugin: https://github.com/mokkabonna/vue-vuelidate-jsonschema

Here I define validations, but don't create any unless the schema property is present: https://github.com/mokkabonna/vue-vuelidate-jsonschema/blob/master/src/index.js#L375

Do you have any tips for how to install it as a global mixin, but avoid instantiating vuelidate if the schema property is not present?

It would be nice if users could just install it, but have no overhead if not using it on a vm. Like you do for vuelidate as you say.

**Comment by Frizi** [comment]
Then what you want to do is registration similar to how vuelidate itself is doing it, by checking if approppropriate key is present on your component first.

Check this logic out:
https://github.com/monterail/vuelidate/blob/901a8f0a7acf5156fa9a37b37868a895e0f9858b/src/index.js#L440-L446

**Comment by mokkabonna** [comment]
Ok thank you very much. I will look into it. Closing issue.

**Comment by Frizi** [comment]
Note however that now the order of execution is becoming important. If both mixins run inside the same `beforeCreate` hook checking and generating the properties they depend on, you have to make sure that your mixin will run first, generate `validations` option and only then vuelidate will kick in detecting it. If you mess that order up, it will never bootstrap itself again.
That means you have to either install vuelidate after your mixin or by importing the mixin and using it manually.

**Comment by mokkabonna** [comment]
I changed the behaviour and now it works as expected as a global mixin:

https://github.com/mokkabonna/vue-vuelidate-jsonschema/blob/a8a5532c6f349be717d5ffaec2830db898f0c6c6/src/index.js#L393-L399

Does not create vuelidate instance now:
https://github.com/mokkabonna/vue-vuelidate-jsonschema/blob/master/test/specs/index.spec.js#L10-L46
