### ISSUE TITLE
Validate Async on blur only

### ISSUE THREAD

**Issue by zagreusinoz** [monterail/vuelidate#211]
I've got an async validator (see below) and it works fine, however currently it validates on each data change, I'd like to do it when the field blurs only.

I know the documentation says the following, however I don't follow what I should do here.

> Validator is evaluated on every data change, as it is essentially a computed value. If you need to throttle an async call, do it on your data change event, not on the validator itself. You may end up with broken Vue observables otherwise.

Here is my validation code.

```
    validations: {
      form: {
        firstName: {required},
        lastName: {required},
        username: {
          required,
          minLength: minLength(6),
          isUnique (value) {
            if (value === '' || value === this.origUsername) return true
            this.checkingUsername = true

            return api('post', 'check/username', 'client', {
              username: value,
              user_id: this[userGetters.GET_SETTINGS]['id']
            })
              .then((response) => {
                console.log(response)
                this.checkingUsername = false
                return true
              })
              .catch(() => {
                return false
              })
          }
        },
        defaultPrivacy: {required},
        units: {required}
      }
    }
```

**Comment by Frizi** [comment]
The documentation says that if you do throttling inside your `isUnique` function, you might break things. Exactly the same will happen if you do that in a computed value, so it's not a surprise really.

That means the code you have here is all fine. The real solution needs a template change though.

If you are using `v-model="myData"`, you have to split it into it's full form (assuming input type="text", change if necessary):
```
@input="myData = $event.target.value" :value="myData"
```

Now, because every `@input` event modifies your local state, all computed values related to it will also retrigger. This includes validation. So what you really want to do is to change that event to `@blur` and it should work as you requested.

**Comment by zagreusinoz** [comment]
Thanks for that explanation mate, much appreciated.

**Comment by ZjanPreijde** [comment]
I stumbled upon this same problem today.

Can't be sure if it is a similar situation, but I used 
`<input type="email" id="email" v-model="email" @blur="$v.email.$touch()">`
This triggered a validation on each keystroke.

When I changed it to `v-model.lazy="email"`, it only triggered the validation when leaving the field.

Hope this helps (someone).

**Comment by unikitty37** [comment]
Is there a way to trigger *only* the async validations on blur?

For example, if a field has `isUnique` and `hasValidCharacters` validations, with `isUnique` making an async API call, I'd want to have `isUnique` run when the field blurs, but `hasValidCharacters` should run after each keystroke (it's poor UX to tell the user the field contains invalid characters without giving them a clue as to which one it is — and having the message come up as soon as they type the wrong character is the best way of doing that :)

**Comment by rushairer** [comment]
> I stumbled upon this same problem today.
> 
> Can't be sure if it is a similar situation, but I used
> `<input type="email" id="email" v-model="email" @blur="$v.email.$touch()">`
> This triggered an async validation on each keystroke.
> 
> When I changed it to `v-model.lazy="email"`, it only triggered the validation when leaving the field.
> 
> Hope this helps (someone).

But,
If an async validation of A is not finished, then you change the B value, when the validataion of A is finished, the B value will be return to the old value of B.
