### ISSUE TITLE
`this` context is not available within `requireIf`

### ISSUE THREAD

**Issue by Fohlen** [monterail/vuelidate#213]
The fiddle is here, https://jsfiddle.net/b5v4faqf/389/
The `this` context of the current `vue` instance is not available within the `requiredIf` validator instance, which makes it pretty useless.

**Comment by Frizi** [comment]
It is available, but you used an arrow function, which has a lexical scoped `this`. Use a `function` keyword.

**Comment by Frizi** [comment]
In your case though, you could drop the `requiredIf` validator at all. Any validator accepts empty input by default, but doesn't accept invalid one even when the field is not required.

All of those are equivalent:
```javascript
text: {
    minLength: minLength(5)
}
```

```javascript
text: {
    required: requiredIf(minLength(0)),
    minLength: minLength(5)
}
```

```javascript
text: {
    required: requiredIf((text) => text.length > 0),
    minLength: minLength(5)
}
```

```javascript
text: {
    required: requiredIf(function () { return this.text.length > 0 }),
    minLength: minLength(5)
}
```

**Comment by wa05** [comment]
yeah but.. Quasar for example is promoting the required use of unnamed functions with a warning
