### ISSUE TITLE
set error programically

### ISSUE THREAD

**Issue by mekramy** [monterail/vuelidate#216]
How can i set error message programmically?
i want for ex set required validation of my field to false!

`this.$v.name.required = false;`

if my back-end validation failed, i need to process error response and set validation failed in client-side.

**Comment by ralugli** [comment]
I have the same problem. There any way to do this?

**Comment by dmig** [comment]
My suggestion: https://monterail.github.io/vuelidate/#sub-dynamic-validation-schema
Use some flag to add custom validator, e.g. one which is always invalid. In this example `serverError` may contain error message.
```javascript
import { required } from 'vuelidate/lib/validators'
import { alwaysInvalid } from 'my/validators'

export default {
  data () {
    return {
      serverError: '',
      name: '',
      description: ''
    }
  },
  validations () {
    if (this.serverError) {
      return {
        name: {
          alwaysInvalid
        }
      }
    } else {
      return {
        name: {
          required
        },
        description: {
          required
        }
      }
    }
  }
}
```

**Comment by Frizi** [comment]
Well, you could just create a validator that returns whatever value there is on your model.

```javascript
field: {
  serverRequired () { return this.serverRequired }
}
```

Then you can just do this in your method
```javascript
this.serverRequired = await askServerIfRequired()
```

**Comment by mekramy** [comment]
define a new validation rule is not a right solution. i need to set same error not new rule!

**Comment by Frizi** [comment]
Vuelidate is ment to be used for validation rules, not for message formatting. You can either express your intent using a validator, or write your own logic using your usual model. What does it even mean to set `required` validation value to false? It is a computed value, `required` being false means your input is empty, and there are multiple ways of being empty.

**Comment by mekramy** [comment]
thank you. i think it's better to show user a common message that say your input is wrong!

**Comment by kevintruby** [comment]
@mekramy it looks like this ticket is a bit old, but still open, so I figured I'd weigh in with my implementation for cleaner error messaging: using the computed data attributes for message display.

```html
<label for="registration_email"
           :class="{
               'has-error': $v.email.$error,
                'validated-input': ($v.email.$dirty && !$v.email.$invalid)
            }">
    <span class="validation-error" v-if="$v.email.$error">{{ getEmailErrorMsg }}</span>
    <input placeholder="Email Address" id="registration_email" type="text"
                v-model="email" name="registration_email" @input="$v.email.$touch()" />
</label>
```
That span only shows up if the model is flagged as breaking a rule. Then, the validations and computed message to display are very simple!
```JavaScript
exports default {
    data: function() {
        email: ''
    },
    validations: {
        email: { required, email }
    },
    computed: {
        getEmailErrorMsg: function(){
            if(!this.$v.email.required)
                return 'Email is required!';
            if(this.$v.email.required && !this.$v.email.email)
                return 'Please enter a valid email address!';
        }
    }
}
```
Personally, I find this to be a better approach to cluttering the DOM with elements and complicated if statements; and I don't think this necessarily needs to be handled by Vuelidate. It already provides the perfect contexts you need to determine your message logic!
