### ISSUE TITLE
debouce async custom validators

### ISSUE THREAD

**Issue by nnjeim** [monterail/vuelidate#218]
Hi,

custom async validators are working perfectly but placing too many calls to the backend.
i tried to apply debouce to the the custom methods but errors were there
 Error in render function: "TypeError: Cannot read property '__isVuelidateAsyncVm' of undefined"

any hint to share here?

thanks in advance

**Comment by Frizi** [comment]
Hi! You should not debounce your validator, but the event changes the data and causes the validation.

One easy example is to add `.lazy` into your `v-model`, or change `@input` into `@change`.

**Comment by nnjeim** [comment]
thanks a lot for the hint, i applied the .lazy to v-model and this solved my issue.

**Comment by genyded** [comment]
The lazy modifier does not work for custom components though.

**Comment by RoundRobin-fr** [comment]
`_.debounce` from lodash does not return the result of the debounced function so the validator cannot work.

You could use this `debounce` version to make sure every call to the debounced function resolves their promise with the result of the latest call during the interval.

```
const debounce = (callback, timeout) => {
    let timer;
    const resolvers = [];
    return async (...args) => {
        clearTimeout(timer);
        return new Promise((resolve) => {
            resolvers.push(resolve);
            timer = setTimeout(async () => {
                const result = await callback.apply(this, args);
                resolvers.map((resolver) => resolver(result));
            }, timeout);
        });
    };
};

const rules = {
    name: {
        test: helpers.withAsync(
            debounce(() => {
                return false;
            }, 1000)
        ),
        $lazy: true,
    },
};
```
