### ISSUE TITLE
Swaped variables?

### ISSUE THREAD

**Issue by coyotevz** [monterail/vuelidate#219]
Hello, I was inspecting the code and I found this lines in `src/index.js` that caught my attention:

```javascript
133 let _cachedComponent = null
134 const getComponent = (Vue) => {
135   if (_cachedComponent) {
136     return _cachedComponent
137  }
...
411  _cachedComponent = {VBase, Validation}    // <----
412  return _cachedComponent
413 }
```
[here](https://github.com/monterail/vuelidate/blob/844873811afa37ecbf8a9a11675b0f34b2f87240/src/index.js#L411)

and then:
```javascript
427  const {Validation, VBase} = getComponent(Vue)    // <----
```
[here](https://github.com/monterail/vuelidate/blob/844873811afa37ecbf8a9a11675b0f34b2f87240/src/index.js#L427)

Is this intentional for some reason? Or it's just a typo

Thanks, Best regards

**Comment by Frizi** [comment]
It does not have any bad effect from maybe the code style. Object destructuring doesn't enforce any order.

**Comment by coyotevz** [comment]
Hello @Frizi, thank you for your answer, you are right, the order is not forced in object destructuring, I had a miss concept about object destructuring, sorry for the noise.
Best Regards
