### ISSUE TITLE
required error message visible on first load

### ISSUE THREAD

**Issue by andreliem** [monterail/vuelidate#22]
Not quite sure if this is a bug, but it seems like on my tests when using the `required` validation rule that the form will indicate there is an error before user input is given.

```
<span class="form-group__message" v-if="!$v.phoneNumber.required">* required</span>
```

So on the first visit, a user will see `* required` even though they haven't inputted anything in. It doesn't seem to do this on the example page though so I'm a bit confused.

**Comment by Frizi** [comment]
It's because you are directly watching the validator output, instead of matching against field's dirty state first. Try wrapping your messages inside an element and do `v-if="$v.phoneNumber.$error"`. It will show up only after the input was touched.

**Comment by andreliem** [comment]
Thank you @Frizi

**Comment by robertkabat** [comment]
Hi Guys,

I think you might want to consider documentation review because I think it's not mentioned in there.

Pozdrawiam,
Robert

**Comment by ant-g** [comment]
The docs need updating because the HTML code in this example: 
https://monterail.github.io/vuelidate/#sub-basic-form
Does not do this (the actual html used must be different than what is quoted on the page) only by finding this issue log have I been able to understand how this should work.

**Comment by stikoo** [comment]
+1 on the above, I thought the behaviour was weird, didn't realise you were controlling the visibility of the errors with a parent css class. Not that obvious from the basic example.

**Comment by jdhines** [comment]
+1 on this too, I've been going back and forth for several hours now trying to compare my code and setup, and wondering why my errors were showing on page load, when in the Basic Example they're not, and the above comments helped me find the CSS that uses a sibling rule to show the error message, and I thought Vuelidate in the docs was just doing something (that made sense to me) that made messages not show if `$dirty` was false, even if the form or certain fields were invalid.

Given that most people would not want errors to show on load, when the form hasn't been touched, and hiding them has to do with CSS more than Vuelidate, I feel like that should be called out, or the examples reworked to not need custom CSS, something like:

```
<template v-if="$v.myfield.$dirty">
  <div :class="{ error: $v.myfield.$error" }>Fix this field</div>
</template>
```
I'm not sure what the difference is between `$error` and `$invalid` though, so don't know which is better to put here.

**Comment by jdhines** [comment]
Created pull request #463 to clarify. Chose not to add more examples but just add an extra paragraph.

**Comment by rahulswimmer** [comment]
I am using :rules="errorRules" in my v-text-field tag. Then I have attached a watch method that constantly monitors for changes in the variables and pushes error to errorRules. These errors get activated when v-text-field is touched. Now I need to display those errors on page load rather then touch/ click event.

For that I am pushing errors in errorRules array and placing this in beforeMount(). Still on page load the error doesn't appear. 

How should I achieve this ?

**Comment by nowucca** [comment]
I'm still not clear how in the basic example having a conditional class affects the visibility of sibling divs that contain the error messages.

The paragraph pull request is a little obtuse.

I'd suggest changing the basic example to be a little simpler, or adding an example before the basic example.

In addition to #463 by @jdhines I'd suggest an example:

`
<div class="form-element">
              <label for="name">Name</label>
              <input
                type="text"              
                v-model="$v.name.$model"
              />
            </div>
<template v-if="$v.name.$error">
              <span class="error" v-if="!$v.name.required"
                >Name is required</span
              >
              <span class="error" v-if="!$v.name.minLength">
                Name must have at least
                {{ $v.name.$params.minLength.min }} letters.
              </span>
</template>`

**Comment by nicolanilomartinoph** [comment]
Sorry for spamming but I'm new to open-source and I'd like to start contributing. Where is the right channel for newbie contributors? I'd like to do it right the first time and follow guideline and conventions and such. Please help me!

**Comment by ryanrapini** [comment]
Bumping this thread to say the current documentation is not at all clear and the paragraph supplied in the [above comment](https://github.com/vuelidate/vuelidate/issues/22#issuecomment-477706817) didn't really help. Lost a lot of time trying to figure out why the `.required` property wasn't behaving how i expected.

**Comment by epmatimbe** [comment]
I suggest you to keep the docs straight forward and do not omit anythang.
For eg. the behaving of those classes we passing in to style

**Comment by duskim** [comment]
Pls reference the example below. The input field captures user email and there are two validations: required, email. Include conditional $v.your_model.$dirty && $v.your_model.your_custom_validation to each error. also note the event @input="$v.your_model.$touch" on the input field to trigger the touch method on every key press. More about $touch method on the website : https://vuelidate.js.org/#sub-v-methods. 

```
                    <input
                    @input="$v.email.$touch"
                    v-model="email"
                    name="email"
                    class="form-control"
                    :class="{ 'input--error': $v.email.$error }" />

                    <div class="error" v-if="!$v.email.required && $v.email.$dirty">Field is required</div>
                    <div class="error" v-else-if="!$v.email.email && $v.email.$dirty"> This is not a valid email </div>
```

...

validations: {
          email: {
            required ,
            email
          },
}

...

**Comment by dapobelieve** [comment]
@duskim I did this and it still doesnt work, once I enter text into a required field the error pops up, i've been stuck with this for days

**Comment by ravianand1988** [comment]
@dapobelieve Would you mind look if there is any `blur` event to control the error appearance?
