### ISSUE TITLE
URL validator fails when URL is uppercase

### ISSUE THREAD

**Issue by JacobBennett** [monterail/vuelidate#220]
see fiddle https://jsfiddle.net/b5v4faqf/446/

Will fail if the URL entered is in all uppercase. Simple fix would be to make it case insensitive match

**Comment by JacobBennett** [comment]
![image](https://user-images.githubusercontent.com/1517011/33137431-eeac483e-cf75-11e7-8c22-f07762d6ccea.png)

**Comment by Frizi** [comment]
I have very mixed feelings about this one. I actually never seen uppercase protocol in the wild, even more so a mixed case one.

Some of case mixing is allowed by the standard though, even if servers usually convert to lowercase anyway. That means you have fair point seeing it's a bug, but it can't be solved just by insensitive match.

**Comment by Frizi** [comment]
That makes sense. I'm mostly concerned about things like `hTtP:` protocol. Otherwise it's indeed not front-end's business to worry about that as RFC allows case mixing, even if it's a de-facto standard to make everything lowercase.

**Comment by JacobBennett** [comment]
So what do you need from me to get this PR merged? If there is anything I can do to help just say the word. If you just need time to think about it thats fine too. Thanks for the lib! Huge fan :)

**Comment by Frizi** [comment]
Ideally You could check and link some sources how it should be accepted (maybe RFC) and write a few tests to check that behaviour. This would be a perfect PR to merge 😄

**Comment by JacobBennett** [comment]
According to [this article](https://www.ietf.org/rfc/rfc1738.txt)

![image](https://user-images.githubusercontent.com/1517011/33156923-53103f0a-cfcc-11e7-8cf1-b1e8f8ce09a1.png)

[Wikipedia](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax)

![image](https://user-images.githubusercontent.com/1517011/33157112-9b5d3294-cfcd-11e7-937f-a727abe68f05.png)

![image](https://user-images.githubusercontent.com/1517011/33157131-d2d7b7c6-cfcd-11e7-8eaf-5e08a68feae8.png)


Lastly, this [RFC 3986](https://tools.ietf.org/html/rfc3986)

![image](https://user-images.githubusercontent.com/1517011/33157180-29a64482-cfce-11e7-9b6c-a22ce85a7c32.png)

![image](https://user-images.githubusercontent.com/1517011/33157205-4fe2cae4-cfce-11e7-86f2-fa1680af04e3.png)

![image](https://user-images.githubusercontent.com/1517011/33157214-6e5acd3c-cfce-11e7-81b6-55bd92e0d53e.png)

After reading through these, I don't think there is a case for saying an all uppercase URL would ever be "invalid" as such, more like not best practice. To reject the URL as invalid though I believe is incorrect. 

I think that in this case then, an insensitive flag would be acceptable.

**Comment by JacobBennett** [comment]
even mixed case I don't think would ever be rejected as invalid since all downstream parsers would handle the url correctly.

**Comment by JacobBennett** [comment]
At the end of the day, I think **you** have to decide what is a valid URL for this library. If you are not comfortable with the idea of mixed case or uppercase, so be it. I didn't develop the library so I can only point out what I believe to be correct and leave it in your hands.

In any case, thanks again for all your hard work. Love this library even with a lowercase requirement :)

**Comment by Frizi** [comment]
Seeing the great research you've done here, I think that the `i` regex flag is actually a preferred way to solve that. Thank You! As RFCs suggest that mixed case should be accepted on application input and we validate exactly that, it makes perfect sense to treat it as valid. If somebody really cares about normalization on client side, it still can be done before sending the request. RFC 3986 point 3.1. actually suggest doing exactly that.

**Comment by JacobBennett** [comment]
PR has been updated with uppercase and mixed case tests. Thanks!

**Comment by Frizi** [comment]
Thanks for this PR, it's a job really well done! It's great to see someone willing to invest some time to look into the sources, fix the issue and not just give up in the process. I wish more people were as professional as You 👍
