### ISSUE TITLE
Delay $invalid

### ISSUE THREAD

**Issue by bschulz87** [monterail/vuelidate#224]
Is there any way to delay the $invalid state, instead of the $dirty state?

I want to hide input fields based on their $invalid status. So after clicking a button (setting validating = true) only invalid fields are shown to the user. My problem is the fields disappear immediately on input when they are valid. I tried the delayed validation errors approach, which only get's me so far. After switching the view the fields are shown again when validating, because they aren't $dirty anymore. 

An example input looks like this currently:

```
v-text-field(type="text" color="black"
              v-if="!(validating && $v.einsatz.patient.bezirksstelle.$dirty && !$v.einsatz.patient.bezirksstelle.$invalid)"
              name="patientBezirksstelle" label="Bezirksstelle"
              v-model="einsatz.patient.bezirksstelle" @input="delayTouch($v.einsatz.patient.bezirksstelle)")
```

**Comment by Frizi** [comment]
> I want to hide input fields based on their $invalid status.
What are you trying to accomplish?

You cannot delay $invalid, as it's a computed value. What you can do is to delay the input event. Try using `v-model.lazy`.

**Comment by bschulz87** [comment]
The goal is to just show invalid fields when validating the form. It's rather unorthodox and the model based validation is just perfect for this.

I managed to solve my problem with `$v.$touch()` when starting the validating and sticking with `delayTouch()`.
