### ISSUE TITLE
Dynamic Schema Not Working

### ISSUE THREAD

**Issue by kquiring** [monterail/vuelidate#227]
I'm trying to implement a vanilla-grade dynamic schema setup.  
https://jsfiddle.net/kquiring1/yjt962a3/4/

The idea is to maintain valObj elsewhere in code.  The Vuelidate page says "recomputations will happen automatically", which I take to mean that the "validations" object will get re-pinged somehow during operation.  It doesn't say on what trigger.   [Issue #98](https://github.com/monterail/vuelidate/issues/98) suggested that a manual call to $touch() might be needed to supply that trigger, so when my code didn't work, I added that.  

As seen in the fiddle, this re-fetch of "validations" isn't happening for me.  Every time validations gets pinged, the counter should increment, and it doesn't.  

In issue #98, he eventually got his code working.  If I put the same "counter" mechanism in his working code, I see it increment on every keystroke, indicating "validations" is getting hit.  But that was Vuelidate v0.3.1.  If I copy/paste his code into a fiddle with the latest Vuelidate, it fails again.  And actually I can make his fiddle fail (the one with v0.3.1) if I convert the value "array" to being a string instead of an actual array, which it seems to me should've worked as well.  

Is there something I'm missing?

**Comment by Frizi** [comment]
You should treat `validations` as computed value. The recomputation happens exactly in the same way as if it was one. That means the trigger is a modification of any observable state that has been used during previous function execution.

Here is a reworked example of yours:
https://jsfiddle.net/xe82e42r/

**Comment by kquiring** [comment]
Thanks much for your quick reply.  

It turns out I was corrupting valObj in the code that maintains it (not in the fiddle), and when I saw the differing behavior in the #98 code I mistakenly thought I was onto something in the module.  When I fix the corruption, my original code works, even without the manual $touch().  

So all is good -- thank you.
