### ISSUE TITLE
Custom validation vuelidate

### ISSUE THREAD

**Issue by sandeepghimire77** [monterail/vuelidate#228]
I have a problöem creating custom validation .
I want my phonenumber to start with + sign .
How do i solve that issue?

custom: (val) => {
            if (val === 'undefined' || val === null || val === '') {
              return true;
            }
            return /^\+?\d{2}[- ]?\d{3}[- ]?\d{3}$/.test(val);

**Comment by Frizi** [comment]
Well, you just described your logic and you've written a function exactly in a way that should be written. Now just use it as a validator. Do you have any issues with that?
