### ISSUE TITLE
Validation rules

### ISSUE THREAD

**Issue by nilgradisnik** [monterail/vuelidate#23]
Please consider incorporating [validator.js](https://github.com/chriso/validator.js) to take care of string validation instead of re-implementing rules.

I like the validation approach this project is taking, keep up the good work.

**Comment by Frizi** [comment]
There is nothing wrong in using `validator.js` inside your code, as we support any function you throw into the validation object. Our validators are split from the main library for a reason. You can just not import them at all if you prefer to.

```javascript
validators: {
  email: {
    isEmail: validator.isEmail
  }
}
```

**Comment by shentao** [comment]
We might add a section both in the README and in the docs with some recommendations for 3rd party validation rules.
Thanks!
