### ISSUE TITLE
is there a notSameAs method?

### ISSUE THREAD

**Issue by samsebastian** [monterail/vuelidate#234]
Or is there a way to use sameAs to achieve a negative result?

I can create a custom validator to do this based on the example, but it seems like it might be something already included that I missed... 

Thanks!

**Comment by nervgh** [comment]
Hey, thank your for the really great library!

I think we need third logic operation -- `not`. Then we can use composition like `not(sameAs('field'))`.

By the way the basic operators `and + or + not` form the "alphabet" of [Boolean Algebra](https://en.wikipedia.org/wiki/Boolean_algebra#Basic_operations) and the base for the derived operators like `xor`.

**Comment by nervgh** [comment]
I have just found out the `not` validator can has next representation:

```
  not (validator) {
    return withParams({type: 'not'}, (...args) => !validator(...args))
  }
```
=)

**Comment by Frizi** [comment]
@nervgh Almost 😄 you still have to handle optional values correctly. I'm going to add it to the core.
