### ISSUE TITLE
Can't access vue component from validators

### ISSUE THREAD

**Issue by rhymes** [monterail/vuelidate#237]
I seems to be unable to access the vue component from validators.

I'm trying to setup a group of data properties that need to be required depending on the value of a computed property, something like the example at the end of this section: https://monterail.github.io/vuelidate/#sub-builtin-validators

Unfortunately though, when I "console.log" the computed property it is always undefined so I really don't know how to make this work.

I tried to strip it down on jsfiddle: https://jsfiddle.net/rhymes/7mpgLt7v/2/

If you open the console you can see that this.isCoverPresent is always undefined (the same in my app using single file components).

I am using Vue 2.5.13 and vuelidate 0.6.1

Thank you

**Comment by Frizi** [comment]
You are using `this` in an arrow function, it's taken over from the parent scope, which (in fiddle's case) turns out to be `window` global object. Try replacing it with full `function`.
https://jsfiddle.net/7mpgLt7v/3/

**Comment by rhymes** [comment]
Thank you! :-)
