### ISSUE TITLE
Cannot read property 'type' of null

### ISSUE THREAD

**Issue by sellou** [monterail/vuelidate#238]
Vue: 2.5.6
Vuelidate: 0.6.1
Vue devtools: 4.0.1
Chrome: 63.0.3239.132 
This issue disables the component inspection in devtools.
It seems it is related to the dependency provide/inject and was discussed here [Vue devtools issue 499](https://github.com/vuejs/vue-devtools/issues/499)

A fix was provided for vee-validate (version 2.0.3), but it seems that vuelidate is also affected by the issue

![image](https://user-images.githubusercontent.com/28937928/34941324-8e3793b6-f9f3-11e7-9c48-8e25c51da2eb.png)

**Comment by Frizi** [comment]
The issue should be already fixed upstream in devtools, so the crash should not happen anyway.
What bugs me though is that I tried downgrading devtools to 4.0.1 and I can't reproduce it there either. Everything just seems to work.

I'm going to close that, but please reopen the issue if you can still reproduce it.
