### ISSUE TITLE
Mocking validator methods not possible because they are set non configurable

### ISSUE THREAD

**Issue by maoberlehner** [monterail/vuelidate#239]
Is there any special reason why validator methods are set `configurable: false` [1]? Because this makes it impossible to mock / spy on them with `jest.spyOn()` [2] or jasmines `spyOnProperty()`

[1] https://github.com/monterail/vuelidate/blob/efa9c5a09798f6378e1d7decea694a2310595127/src/index.js#L272
[2] https://facebook.github.io/jest/docs/en/jest-object.html#jestspyonobject-methodname-accesstype

**Comment by Frizi** [comment]
I don't remember to be honest what was my reasoning when doing that. It does seem unimportant indeed and your point is valid. I'm going to change that.

The only question is, why are you trying to test the library?

**Comment by maoberlehner** [comment]
@Frizi cool, thx.

> The only question is, why are you trying to test the library?

I don't, thats why I want to mock it in my tests.

**Comment by DanielPe05** [comment]
@maoberlehner Did this fix the mocking issue?
I'm running into the same scenario after this change was merged where I need to do an async validation and I want to mock the util that does that async validation.
something like this:
```
import asyncValidator from './asyncValidator'
...
  validations: {
    zipCode: {
      required,
      numeric,
      minLength: minLength(5),
      zipCode: asyncValidator.zipCode
    }
  },
...
```
and then the test does something like this:
```
import asyncValidator from './asyncValidator'
...
it('some test', async () => {
  jest.spyOn(asyncValidator, 'zipCode').mockResolvedValue(true)
  const { getByText, getByTestId } = render(App)

  await userEvent.type(getByTestId('input'), '33012')

  // I expect that the real async validation didn't happen and instead my mockImplementation kicks in yet that is not the case. Is there a way to accomplish this?
})
```
