### ISSUE TITLE
Is it possible to use `withParams` in an asynchronous validator?

### ISSUE THREAD

**Issue by samtsai** [monterail/vuelidate#240]
I'm trying to create a custom validator that is asynchronous (ie loads in an external library on demand) and its important for me to append useful `$params` but I can't seem to get both async validation and `withParams` working:
https://jsfiddle.net/b5v4faqf/527/

Validation works but `params` are always `null`.

**Comment by Frizi** [comment]
`withParams` is synchronous by nature. There is no way to append params inside async call. What are you trying to accomplish? Maybe there is other more natural way to do it? If not, it might be a valid case to extend the library.

**Comment by samtsai** [comment]
Thanks for the response @Frizi . Albeit, I might be trying an edge case but what I'm trying to do is:

- load the Dropbox library [zxcvbn](https://github.com/dropbox/zxcvbn) asynchronously (on-demand)
- validate password strength
- attach `zxcvbn` strength messages to params via `withParams`

```
import { required } from 'vuelidate/lib/validators';
import { withParams } from 'vuelidate/lib/validators/common';

export default (requirement, value) => {
  return import(/* webpackChunkName: "zxcvbn" */ 'zxcvbn').then(zxcvbn => {
    let strength = zxcvbn(value);
    let score = strength.score;
    let isStrong = score >= requirement;
    let message;

    if (!isStrong) {
      message = gatherMessage(strength.feedback);
    }

    return withParams({
      type: 'passwordStrength',
      feedback: message,
      requirement,
      isStrong,
    }, () => {
      return required(value) && isStrong;
    });
  });
};
```

My current implementation:

```
import { required } from 'vuelidate/lib/validators';
import { withParams } from 'vuelidate/lib/validators/common';
import zxcvbn from 'zxcvbn';

export default (requirement, value) => {
  let passwordStrength = zxcvbn(value);
  let score = passwordStrength.score;
  let isStrong = score >= requirement;
  let message;

  if (!isStrong) {
    // `gatherMessage` defined outside of `export`
    message = gatherMessage(passwordStrength.feedback);
  }

  return withParams({
    type: 'passwordStrength',
    feedback: message,
    requirement,
    isStrong
  }, () => {
    return required(value) && isStrong : true;
  });
};
```

This was inspired by my reading this post: http://jmduke.com/posts/how-i-cut-my-webpack-bundle-size-in-half/

**Comment by samtsai** [comment]
The response from `zxcvbn` is important to as part of validation and I want a clean way to show to the user. I know I could emit an event with the message or update a dynamic property but it seems less appropriate.

**Comment by Frizi** [comment]
Unfortunately you cannot use `withParams` inside promise call. I can't really see how it could be supported with current implementation. It would require a mechanism similar to angular's zones, which is kinda an overkill for validation library.

I have no intention to add a support for this. You should probably load the 'zxcvbn' library prior to loading your component to not overcomplicate things.

Try using dynamic components to codesplit it.
```javascript
components: {
  FormWithPasswordChecker: () => import('./FormWithPasswordChecker.vue')
}
```

**Comment by NukeTheMoon** [comment]
no support for async with params makes image validation a little tricky to do with vuelidate.

checking image dimensions with js, whether it's by File, Blob or base64 string, will always require awaiting inside the validator. however without $params, you can't display an error message stating the actual dimension requirements to the user.  

a possible workaround is to pass a ref with the already calculated image dimensions into the withParams helper, but personally I'd prefer to have this async logic inside the validator. oh well.
