### ISSUE TITLE
Data nesting dose not support array 

### ISSUE THREAD

**Issue by yuuk** [monterail/vuelidate#243]
my code is here: [ https://jsfiddle.net/b5v4faqf/547/]( https://jsfiddle.net/b5v4faqf/547/)

**Comment by Frizi** [comment]
Arrays are indeed supported. The issue you have is an error with incorrect template usage. You cannot have dynamic `:type` on input while having `v-model` on it.

**Comment by kosanr1** [comment]
For array validation you should use `$each` . Here is example https://monterail.github.io/vuelidate/#sub-collections-validation
