### ISSUE TITLE
Dynamic manipulation of validations object.

### ISSUE THREAD

**Issue by vbledar** [monterail/vuelidate#248]
I have a main component A and two sub-components C and B.
Component A has a data object name parent. Based on type property of parent one of C or B is shown.

When C or B are created they receive the parent as a prop and introduce child objects in parent using this.$set.

Since I don't know in advance which component (C or B) will be shown I cannot apply the required validations because $touch() would complain about undefined.

The $v is also passed from component A to the sub-components. Is it possible to inject the appropriate validations in $v during created lifecycle and remove them during destroyed?

**Comment by Frizi** [comment]
You have to add some logic to `validations` definition. Use it in a method form. There are a few examples in the docs how to define it dynamically.

**Comment by vbledar** [comment]
Sorry for coming back so late. I will give it a try. For the time being I guess this should not stay open any longer.

Thank you for taking the time.
