### ISSUE TITLE
Built in validators accept functions for arguments

### ISSUE THREAD

**Issue by jasonshsoftware** [monterail/vuelidate#251]
I am serializing my MVC validations for use in my Vue ViewModels. This often includes things like minLength, etc. I also created a custom decorator so that I can just add @Validation({blah...}) to my model properties and the validation is automatically added.

This works great except when I want to use a serialized parameter for my validation. For the length of minLength. That validation only accepts a number. It would be nice if it could also accept a function returning a number and evaluate the function at run time. This would allow me to supply the the length from the server.

I'm sure that this is an edge case, but I sure hit it. My setup is this (and I'm sure this is one of the only setups that hit it, but it's a nice to have):

- Vue-Class-Component
- Vue-Property-Decorator
- Custom Validate decorator
- Typescript

**Comment by Frizi** [comment]
You could slightly invert your problem: just treat the whole validations object as a function and provide the validation parameters as variables.

```javascript
validations () {
  return {
    myValue: {
      minLength: minLength(this.lengthFromServer)
    }
  }
}
```

You can also use more complex logic to generate the whole object.

The other solution would be to wrap the validator into your own function:
```javascript
const lazyMinLength = fn => function (...args) { return minLength(fn(this))(...args) }

...

validations: {
  myValue: {
    minLength: lazyMinLength(vm => vm.lengthFromServer)
  }
}
```
