### ISSUE TITLE
Using contextified validator on nested data

### ISSUE THREAD

**Issue by FerrielMelarpis** [monterail/vuelidate#252]
Hi! Great plugin. 
Not sure if this is an issue, this is more like a question.
How can I take advantage of contextified validators on nested data?
```js
validators: {
  form: {
    field1: {
      field1a: { required },
      field1b: { required, email },
    field2: {
      field2a: { required, email } // same as 'field1b'
...
```
Is there a way to do this using the `sameAs` validator?

**Comment by SerVac** [comment]
Yes, please, can any resolve this issue?

```
<input  v-model.trim="form.password">
<span  v-if="!$v.form.password.required">Password is required.</span>
<span  v-if="!$v.form.password.minLength">Password must have at least 6 letters.</span>

<input  v-model.trim="form.repeatPassword">
<span   v-if="!$v.form.repeatPassword.sameAsPassword">Passwords must be identical.</span>
 
data() {
      return {
          form: {
             password: '',
             repeatPassword: ''
        },
},
validations: {
      form: {
        password: {required, minLength: minLength(6)},
        repeatPassword: {sameAsPassword: sameAs('form.password')},
      }
}
```

**Comment by FerrielMelarpis** [comment]
@Arxi My workaround was to create a custom validator since this validators are just higher order functions anyway. But, it would be nice to have it in `sameAs` validator.

**Comment by Frizi** [comment]
@FerrielMelarpis Actually `sameAs` does allow this. Check what the documentation says about locators.

```javascript
field2a: {
  required,
  sameAsField1B: sameAs(function() { return this.form.field1.field1b })
}
```

**Comment by FerrielMelarpis** [comment]
@Frizi I noticed the documentation has been updated. It is so clear to me now. Thanks a lot! :+1:

**Comment by zvaehn** [comment]
I cannot see the documentation being updated. Took me about 1 hours to figure out, that `sameAs()` does not work for nested properties out of the box. Using the function provided by @Frizi worked out well though!

**Comment by giovanemariel** [comment]
Very cool!!!

**Comment by shentao** [comment]
This has been reworked in the upcoming version. You will be able to pass any value there along with using anything found on `this`.

**Comment by webfacer** [comment]
Hi,
i am getting this error when using it like this:
```
@Component({
  mixins: [validationMixin],
  validations: {
    formParams: {
      newPassword: {
        value: {
          required,
          minLength: minLength(6),
          maxLength: maxLength(80)
        }
      },
      newPasswordConfirmation: {
        value: {
          sameAsNewPassword: sameAs(function() {
              return this.formParams.newPassword.value
          })
        }
      },
      password: {
        value: { required, minLength: minLength(6), maxLength: maxLength(80) }
      }
    }
  }
})
```
how i  should use it in typescript?

**Comment by dobromir-hristov** [comment]
What error are you getting?

**Comment by webfacer** [comment]
that i cannot use "this" in annotation @Component you see it on the validation of sameAs() method, but i solved it by using the vuelidate-property-decorator package. With this package i could declare it as class property and could use then an arrow function to use data of component.
