### ISSUE TITLE
Check if only letters and/ or spaces

### ISSUE THREAD

**Issue by sjardi** [monterail/vuelidate#253]
Hello! I wanted to do a check where a string only contains letters or spaces ( first name and lastname ), but it gives a false if i enter a space between first and lastname. Is there a recommended way to fix this?

**Comment by lawsonry** [comment]
You can always use a regex pattern, like this:

    <input type="text" pattern="[a-zA-Z0-9]+" data-error="Must be alphanumberic" data-success="Great!">

**Comment by robodude** [comment]
I would also like to see a pre-made validation function provided that would check letters or numbers or spaces. I would prefer to keep all my validation 'stuff' happening in the same place.

**Comment by sjard1** [comment]
Well you can make a custom validation, but the way vuelidate fix this is that you almost completly remove the vuelidate syntax and completly write it in normal javascript..

**Comment by robodude** [comment]
You're absolutely correct, @sjard1 . I was only suggesting that this type of validation could be offered out of the box as one of the built in validators as seen here: 
https://monterail.github.io/vuelidate/#sub-builtin-validators

Maybe this is a good opportunity for me or someone to build one and submit a PR ;)

**Comment by lawsonry** [comment]
@robodude that's a good idea! I just recently ran into this problem and ended up rolling my own quick and dirty front-end solution. I think it would be smart to offer more solutions as pre-built validators out-of-the-box.

**Comment by Frizi** [comment]
Improved docs for custom validators incoming. This should resolve this issue.

**Comment by JordanaCaiCarv** [comment]
Hi! This solution works. Thanks. But... If I have something like this "Aaaaaaaaaa bbbbb ccc" , how can  I trate? Thinking in security too.

**Comment by sjardi** [comment]
> Hi! This solution works. Thanks. But... If I have something like this "Aaaaaaaaaa bbbbb ccc" , how can I trate? Thinking in security too.

What is trate? And what do you mean in security to? If you want custom validation you must use your own regex as jesselawson described above. The so after pattern= "Your own regex here", if you don't know what regex is or how it works you should google it ;)

good luck!
