### ISSUE TITLE
Tracking Validation Progress

### ISSUE THREAD

**Issue by RyanMulready** [monterail/vuelidate#254]
I'd like to track the validation progress of a workflow.  Lets say the user starts off with 0/5 required inputs filled out.  As they enter one I'd like to know the progress has now changed to 1/5.

What's the best approach here?

**Comment by jpickwell** [comment]
If it's a workflow, then only allow them to progress to the next field after filling the current field with a valid value.

If that's not an acceptable option, then you'll have to "watch" the `$invalid` or `$error` flags of each field validation. Increment a data field when valid, decrement when invalid.

**Comment by RyanMulready** [comment]
My thought process went to a watcher but I could not get it to work.  The example I was looking at was this: 

`watch: {
  	$v(value) {
    	console.log('watch $v', value)
    }`

But the watcher never triggered.

**Comment by jpickwell** [comment]
```javascript
watch: {
  // cannot be an arrow-function
  '$v.someField.$invalid': function _watch$vSomeField$invalid (value) {
    console.log('watch $v.someField.$invalid', value)
  }
}
```

**Comment by RyanMulready** [comment]
Awesome, works well.

**Comment by recoiladam** [comment]
Just a note that this no longer works. It returns the following error:

```
Method "computed" has type "object" in the component definition. Did you reference the function correctly?
```

> ```js
> watch: {
>   // cannot be an arrow-function
>   '$v.someField.$invalid': function _watch$vSomeField$invalid (value) {
>     console.log('watch $v.someField.$invalid', value)
>   }
> }
> ```
> 
> You cannot watch `$v` because that's the vuelidate validation container. You could watch `$v.$invalid` but that would only change once all fields are valid.
