### ISSUE TITLE
[question] Validation in child component

### ISSUE THREAD

**Issue by vystepanenko** [monterail/vuelidate#259]
hello!
I have layout something like this https://jsfiddle.net/2m5uwm9x/25/

Can I somehow validate it? I just dont know on what event bind "$v.$touch()" on my component

**Comment by jpickwell** [comment]
Issue 1: Your `custom-input` needs to have an `input` event for `v-model` to work. https://jsfiddle.net/2m5uwm9x/40/

[Form Input Components using Custom Events](https://vuejs.org/v2/guide/components.html#Form-Input-Components-using-Custom-Events) 

Once that's fixed, just add a validations option like in the documentation. You can listen to your `custom-input`'s `input` event and trigger `$v.senderCity.$touch()` or whatever. If you want to trigger on any other event, either add those events to the `custom-input` or, if the event exists on the HTML `input`, use the `native` modifier on the event.

**Comment by vystepanenko** [comment]
@jpickwell 
thnx. i have input event for v-model just forgot it in my jsfiddle.
`@input="$v.senderCity.$touch()"`
Thats wokr perfectly.
I recived something like this
```
{
  "senderCity": {
    "name": {
      "required": false,
      "minLength": true,
      "$invalid": true,
      "$dirty": false,
      "$error": false,
      "$pending": false,
      "$params": {
        "required": {
          "type": "required"
        },
        "minLength": {
          "type": "minLength",
          "min": 3
        }
      }
    },
    "$invalid": true,
    "$dirty": false,
    "$error": false,
    "$pending": false,
    "$params": {
      "name": null
    }
  },
  "$invalid": true,
  "$dirty": false,
  "$error": false,
  "$pending": false,
  "$params": {
    "senderCity": null
  }
}
```

I can see that it's changed on my input,  but if i try
`<div style="background: red" v-if="$v.senderCity.invalid">Invalid</div>`
its not working

**Comment by jpickwell** [comment]
should be `$v.senderCity.$invalid` or `$v.senderCity.$error`

**Comment by kevingermain** [comment]
Simple question, I'm trying to add validation logic inside the child component... I really can't do it. How can I do it properly and change the parent $v?

**Comment by jpickwell** [comment]
Not entirely sure, but you could try `this.$parent.$v` in the child component as a starting point. Also, look through [Vue's API documentation](https://vuejs.org/v2/api/) because what you're asking isn't specific to Vuelidate.

**Comment by vidal7** [comment]
I succeeded with the vuejs's provide/inject API. To make it worked, I had to provide $v in the vuejs beforeCreate() life cycle hook of the parent component like this.

`beforeCreate(): void {
        this.$options.provide = () => ({
            $v: this.$v
        });
    }`

In the child component, use the inject option as usual

`inject: ['$v']`

Please note that I am using vue-class-component with TypeScript but I think it should works in plain JS if you adapt my code. Note also when providing $v in the parent component, I needed to encapsulate in a function. 

Doing that was not working
`this.$options.provide = {
            $v: this.$v
        };`

**Comment by Frizi** [comment]
@vidal7 option should work, but this seems like an overkill. You should simply pass a specific `$v` subtree as a prop.

https://jsfiddle.net/Frizi/2m5uwm9x/51/

**Comment by vidal7** [comment]
Hooo :) Simplest solution works best :)

**Comment by twalldesign** [comment]
> Simple question, I'm trying to add validation logic inside the child component... How can I do it properly and change the parent $v?
> 
> (I have custom validation in the child component...) I spend 3 days to do something that should be simple but it's so hard to make it work...

Did you ever figure this out? I have the same problem.

**Comment by jpickwell** [comment]
@twalldesign, see @Frizi's final [comment](https://github.com/vuelidate/vuelidate/issues/259#issuecomment-390677212).

**Comment by twalldesign** [comment]
Thanks. Not quite what I am looking for. I would like to keep the field info in the child component (which has multiple fields), bring that component into the parent and be able to add a custom error message for each field in my child component.
