### ISSUE TITLE
Difference validation result depends about input type

### ISSUE THREAD

**Issue by czarek19937** [monterail/vuelidate#262]
Hello,
My fiddle: https://jsfiddle.net/b5v4faqf/1076/
Problem/Question/Bug?
Please try 2 tests:
1)Open Chrome browser with my fiddle and write 'eeee' in both fields
2)Same on Firefox(but here you have bigger choice about letters because in firefox there is possibility to write other letters in number type input)
You will see two differents results depend about input type related to numeric and between params.
I am not sure is it correct behaviour? But maybe it's my mistake?
Best Regards,
Cezary

**Comment by Frizi** [comment]
This is the way how different browsers handle `type="number"` inputs. It's not a difference in Vuelidate itself. You have to either not use such inputs or normalize their outputs yourself. Second option might be a bit hard, as browsers doesn't even trigger change reliably on invalid input.
