### ISSUE TITLE
Scroll to the first error

### ISSUE THREAD

**Issue by lalitbansal457** [monterail/vuelidate#268]
is it possible to scroll to the first error field ?

**Comment by Frizi** [comment]
Yes. You have to implement scrolling to the node on your own. Vuelidate already makes it pretty easy to detect where error occured by inspecting `$v`.

**Comment by andot13** [comment]
I got this to work, but a non-native javascript with scroll animation would be better. 
In your template:
```
<input :class="{ 'input--error': $v.name.$error}" >
```
In your methods:

```
this.$nextTick(() => {	
let domRect = document.querySelector('.input--error').getBoundingClientRect();
  window.scrollTo(
    domRect.left + document.documentElement.scrollLeft,
    domRect.top + document.documentElement.scrollTop
  );
})

**Comment by 1beb** [comment]
Method doesn't seem to work anymore @maoberlehner

**Comment by ataldev** [comment]
> For anyone discovering this via Google: [I've written an article about how to scroll to the first Vuelidate validation error](https://markus.oberlehner.net/blog/vue-form-validation-with-vuelidate/).

Not a general solution.

**Comment by 1beb** [comment]
I was able to achieve this by using a method like this, that's triggered when someone attempts to submit the form.  

```
triggerTouch() {
      this.v$.$touch()
      document.getElementById('SOMEID').scrollIntoView({
        behavior: "smooth"
      }) 
    }
```
