### ISSUE TITLE
Validate before submit

### ISSUE THREAD

**Issue by iagokv** [monterail/vuelidate#278]
Hi. 

I'm trying to validate my form and them send it to the server, but I can't find a way to do this through Vuex. It's calling both the validate method, which I implemented with `this.$v.$touch()`, and the action which modify my state and send it to the server.

Does Vuelidate has a promise - like `validateAll()` in vee-validate - to solve this problem?

**Comment by narramadan** [comment]
Did you sort out what should be done to perform validate upon click of submit button only ?

**Comment by iagokv** [comment]
Yeah, I did.
on the submit function, you should do: 
`if (!this.$v.$invalid) {
  // do your sucess request here.
} else {
  this.$v.$touch()
}`

with this, you will successfully send your request when your form is not invalid and, if it's, you'll alert the user with $touch().

**Comment by narramadan** [comment]
thnx
