### ISSUE TITLE
Having issues validating with sameAs

### ISSUE THREAD

**Issue by lighth7015** [monterail/vuelidate#279]
I'm having issues with getting sameAs() to work, similar to an issue with requiredIf() a few monts ago, but I don't know what I'm doing wrong-

-  https://jsfiddle.net/ys1xdwch/12/
- https://codepen.io/lighth7015/pen/BrXbgG?editors=1111

Thank you,
Robert

**Comment by Frizi** [comment]
@JonelRempis This is correct 👍
