### ISSUE TITLE
adding validation with emit

### ISSUE THREAD

**Issue by gomezmark** [monterail/vuelidate#283]
How can i add vuelidate together with emit

```
<div class="mobile-no">
        <input 
          type="number" 
          :value='mobileno'
          @input='changeMobile'
        >
</div>
```

for my methods
```
methods : {
      selectCode(value, $event) {
        if(value && value.dial_code) {
          
          this.$emit('changeMobile',{ 
            update : 'countrycode',
            value  : value.dial_code
          });
        }
      },
      changeMobile($event) {
        if($event.target.value) {
            this.$emit('changeMobile',{ 
              update : 'mobile',
              value  : $event.target.value
            });
        } 
      }
    },
```

I tried to add the vuelidate on the functions, but it doesn't update at all
```
changeMobile($event) {
            this.$v.mobile.$touch();
            this.$emit('changeMobile',{ 
              update : 'mobile',
              value  : $event.target.value
            });
```

![image](https://user-images.githubusercontent.com/19304789/39091433-76c46fcc-4626-11e8-9a64-76e9517a6ceb.png)

**Comment by Frizi** [comment]
What are you trying to accomplish?
If you mean to register touch to the field on event call, your code with `this.$v.mobile.$touch()` is supposed to work correctly.

I'm closing this as non-actionable. If You think there is something missing/wrong with the library, please provide a reproduction and clear explanation.
