### ISSUE TITLE
Localized Error Messages

### ISSUE THREAD

**Issue by abdullah-abunada** [monterail/vuelidate#284]
How can I customize .errors base language?

**Comment by Frizi** [comment]
There is no localization in Vuelidate and I don't see this as a fit for validation library. Bring your own translation lib. This was discussed multiple times here before.

**Comment by zortext** [comment]
Localization is a pain with vuelidate. I gave up using it just because of this issue.

**Comment by dobromir-hristov** [comment]
@zortext maybe give Vuelidate 2 a try :) or let us know what you did not like about the experience.

Vuelidate 0.x translations were kinda a pain, even with the Vuelidate-error-extractor package :)

**Comment by zortext** [comment]
Thank you @dobromir-hristov. I  figured it out.

https://vuelidate-next.netlify.app/advanced_usage.html#i18n-support

**Comment by zortext** [comment]
I have some issues with using with vue-i18n [(v9)](https://vue-i18n-next.intlify.dev/guide/advanced/composition.html) at `compositionOnly: true` mode.

Following the example at https://vuelidate-next.netlify.app/advanced_usage.html#i18n-support
```
// @/utils/i18n-validators.js
import * as validators from '@vuelidate/validators'
import { useI18n } from 'vue-i18n'

// or import { createI18nMessage } from '@vuelidate/validators'
const { createI18nMessage } = validators

// extract the `t` helper, should work for both Vue 2 and Vue 3 versions of vue-i18n
const { t } = useI18n()

// pass `t` and create your i18n message instance
const withI18nMessage = createI18nMessage({ t })

```
I have an error: `Uncaught SyntaxError: Must be called at the top of a 'setup' function`

Could not find a way to access the `t` function outside a component. 

Any ideas?

**Comment by dobromir-hristov** [comment]
Use the exported i18n instance, how I showed, not the useI18n helper.

**Comment by zortext** [comment]
New API of vue-i18n does not provide an export named 'i18n' so cannot use something like 

```
import { i18n } from "vue-i18n"
const { t } = i18n.global || i18n
```

**Comment by dobromir-hristov** [comment]
That is not how I show it on the linked by you example. Use your instance.

**Comment by fvclaus** [comment]
For me only the following worked:
```
const withI18nMessage = validators.createI18nMessage({
    t: i18n.t.bind(i18n),
});
```
`i18n.global` was not defined for me and passing `t` into `createI18nMessages` would result in an undefined `this`.

**Comment by kevindesousa** [comment]
Hello,

I have the same problem, how did you fix that ?

> I have some issues with using with vue-i18n [(v9)](https://vue-i18n-next.intlify.dev/guide/advanced/composition.html) at `compositionOnly: true` mode.
> 
> Following the example at https://vuelidate-next.netlify.app/advanced_usage.html#i18n-support
> 
> ```
> // @/utils/i18n-validators.js
> import * as validators from '@vuelidate/validators'
> import { useI18n } from 'vue-i18n'
> 
> // or import { createI18nMessage } from '@vuelidate/validators'
> const { createI18nMessage } = validators
> 
> // extract the `t` helper, should work for both Vue 2 and Vue 3 versions of vue-i18n
> const { t } = useI18n()
> 
> // pass `t` and create your i18n message instance
> const withI18nMessage = createI18nMessage({ t })
> ```
> 
> I have an error from useI18n() : `Uncaught SyntaxError: Must be called at the top of a 'setup' function`
> 
> Could not find a way to access the `t` function outside a component.
> 
> Any ideas?

**Comment by dobromir-hristov** [comment]
Sorry about the confusion everyone. I have added the `bind` to the docs.

**Comment by dvincitravis** [comment]
I am also struggling with this.

I'm using the exact code shown [in the docs](https://vuelidate-next.netlify.app/advanced_usage.html#i18n-support).

I get:

```
Compiled with problems:

ERROR in ./src/utils/i18n-validators.js 4:0-30

Module not found: Error: Can't resolve '@/i18n' in '/Users/dvincitravis/Desktop/vuesandbox/src/utils'
```

I don't really understand what this line is supposed to be importing, or from where:

    import { i18n } from "@/i18n"

Do I need to create a /src/i18n directory in my project? If so, what should I put there?

**Comment by CyntaxDotDev** [comment]
It might be just me but I am failing to implement these two libraries and get decent translations going. I really like how Vuelidate works but this is a serious pain at the moment. Anybody got a working example of overwrites in either main.ts or a specific component such as a login form (in my case)?

**Comment by clockwiser** [comment]
> New API of vue-i18n does not provide an export named 'i18n' so cannot use something like
> 
> ```
> import { i18n } from "vue-i18n"
> const { t } = i18n.global || i18n
> ```
There is a warning, "export 'i18n' was not found in '@/i18n'.
Apparently, the sample from the vuelidate site is not working.

**Comment by dobromir-hristov** [comment]
This is just an example how you can organize your code.

Please adjust to your specific i18n setup.

**Comment by clockwiser** [comment]
> import { i18n } from "vue-i18n"

Removing braces as below will work with 2.3.1 .

 import  i18n  from "vue-i18n"

**Comment by dobromir-hristov** [comment]
It's a matter of how you export your i18n instance. That is out of this library's scope.
