### ISSUE TITLE
Add changelog or consistent release notes

### ISSUE THREAD

**Issue by jean-moldovan** [monterail/vuelidate#298]
Hey!

I'm glad that Vuelidate is back on track with the new "major" version released.

Would be nice to not forget to add release notes here `https://github.com/monterail/vuelidate/releases` or to have a changelog so that people can address possible breaking changes without digging into the code.

Thanks again!

**Comment by nikwen** [comment]
It's important to be able to see what has changed. :+1:

**Comment by Frizi** [comment]
I've added release notes. Thanks for being cautious 🙂

**Comment by nikwen** [comment]
Thank you so much! :)

**Comment by lobo-tuerto** [comment]
Where are the release notes? or CHANGELOG file?
