### ISSUE TITLE
Setup jsfiddle with the latest Vuelidate

### ISSUE THREAD

**Issue by jean-moldovan** [monterail/vuelidate#299]
Super useful when submitting issues. Add it to the readme maybe or somewhere.

Thanks!

**Comment by Frizi** [comment]
It is set up since a long time ago, you should see it in the issue template. It is also linked in the docs in the top section. Do you have any issues with this fiddle?

**Comment by jean-moldovan** [comment]
Sorry, didn't see it in the docs.
