### ISSUE TITLE
$anyError should check $error on children instead of $anyDirty

### ISSUE THREAD

**Issue by Akryum** [monterail/vuelidate#315]
Currently $anyError uses this expression according to the docs:

```js
this.$anyDirty && !this.$pending && this.$invalid
```

This is wrong because a form can be `$invalid` and `$anyDirty` but not having any single `$error` in the validation tree.

For example, you only have required fields.
1. The form is `{ $invalid: true, $anyDirty: false, $anyError: false }` and no errors are displayed (yet)
2. The user enter something in the first field, making it valid
3. We touch the field so it becomes `$dirty`
5. No error are show yet, because the other fields aren't `$dirty` (the user hasn't come to those yet)
4. The form is now `{ $invalid: true, $anyDirty: true, $anyError: true }`

It should be `{ $invalid: true, $anyDirty: true, $anyError: false }` because we don't display any error.

This is very anoying if we want to disable the submit button *as long as* at least one error is shown.

**Comment by pareeohnos** [comment]
Any ETA on getting this merged? Running into this in our system and would like to get it finished up
