### ISSUE TITLE
Validating Nested Object inside Nested Object 

### ISSUE THREAD

**Issue by paolog22** [monterail/vuelidate#318]
this is the sample data
![image](https://user-images.githubusercontent.com/12680745/40974229-8023d6a2-68f9-11e8-80d0-35c18c253020.png)

i cant validate the `itemTwoList`

**Comment by downace** [comment]
Will this work?

```javascript
new Vue({
    data: { /* ... */ },
    validations: {
        data: {
            obj: {
                list: {
                    $each: {
                        itemList: {
                            itemTwoList: {
                                // Validation rules for itemTwoList
                                $each: {
                                    // Validation rules for each item in itemTwoList
                                }
                            }
                        }
                    }
                }
            }
        }
    }
});
```

**Comment by Ju66ernaut** [comment]
I am facing this same issue. I tried the above suggestion but I can't seem to get the html part correct to show the error if it is triggered. Or the error always shows.

**Comment by dobromir-hristov** [comment]
`$v.data.obj.list.$each[0].itemList.itemTwoList.$each[0].required.$invalid` like that for the above example/

**Comment by Ju66ernaut** [comment]
Excellent thank you @dobromir-hristov. This is what I was not getting right `.$each[0]`
