### ISSUE TITLE
Example debounce with AJAX (Axios) and debounce

### ISSUE THREAD

**Issue by genyded** [monterail/vuelidate#320]
Having scoured for hours, we are unable to find an FULL example for this use case:

- Input with v-model that is a data object property (form.passcode) - input is custom ([Quasar framework](https://quasar-framework.org/components/input-textfield.html))
- Vuelidate validation (called checkPasscode or whatever) that uses the input value to place an ajax axios post to an api that returns true if the passcode matches and false if not
- The api call (and validation?) are debounced so that they happen after the user stops typing

We did not provide a fiddle since we are not sure how to even do this. The docs say not to debounce in validations, so how can we do this? The async examples in the docs do not use debounce but have the api call in the validation, so where should the debounce go?

**Comment by OCJvanDijk** [comment]
Async example from the docs adjusted with debouncing:

```JavaScript
import { required } from 'vuelidate/lib/validators'

export default {
  data() {
    return {
      username: ''
    }
  },
  methods: {
    // In my example I'll use lodash debounce for simplicity
    debounceInput: _.debounce(function (value) {
      this.$v.username.$model = value
    }, 300)
  },
  validations: {
    username: {
      required,
      isUnique(value) {
        // standalone validator ideally should not assume a field is required
        if (value === '') return true

        // simulate async call, fail for all logins with even length
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            resolve(typeof value === 'string' && value.length % 2 !== 0)
          }, 350 + Math.random() * 300)
        })
      }
    }
  }
}
```

The html, note that I'm not using v-model anymore:
```html
<div>
  <div class="form-group" :class="{ 'form-group--error': $v.username.$error, 'form-group--loading': $v.username.$pending }">
    <label class="form__label">Username</label>
    <input class="form__input" :value="$v.username.$model" @input="debounceInput($event.target.value)"/>
  </div>
  <div class="error" v-if="!$v.username.required">Username is required.</div>
  <div class="error" v-if="!$v.username.isUnique">This username is already registered.</div>
  <tree-view :data="$v.username" :options="{rootObjectKey: '$v.username', maxDepth: 2}"></tree-view>
</div>
```

**Comment by genyded** [comment]
Actually it does work. We're using Quasar, so the input event needed the native modifier and then it works.

**Comment by OCJvanDijk** [comment]
It would probably be better to use `@input="debounceInput($event)"` instead of `@input.native="debounceInput($event.target.value)"`

**Comment by genyded** [comment]
doing that gives:

    Error in render: "TypeError: Cannot read property '__isVuelidateAsyncVm' of undefined"

**Comment by RoundRobin-fr** [comment]
`_.debounce` from lodash does not return the result of the debounced function so the validator cannot work.

You could use this `debounce` version to make sure every call to the debounced function resolves their promise with the result of the latest call during the interval.

```
const debounce = (callback, timeout) => {
    let timer;
    const resolvers = [];
    return async (...args) => {
        clearTimeout(timer);
        return new Promise((resolve) => {
            resolvers.push(resolve);
            timer = setTimeout(async () => {
                const result = await callback.apply(this, args);
                resolvers.map((resolver) => resolver(result));
            }, timeout);
        });
    };
};

const rules = {
    name: {
        test: helpers.withAsync(
            debounce(() => {
                return false;
            }, 1000)
        ),
        $lazy: true,
    },
};
```
