### ISSUE TITLE
single prebuilt js file

### ISSUE THREAD

**Issue by andrisi** [monterail/vuelidate#33]
Could you include a prebuilt js file containing all plugins? Just for the lazy ones who want to try it out quickly, or those that use another toolchain. Thanks a lot. Great direction.

**Comment by Frizi** [comment]
Browser ready files are already included. It's just split into two, one for core and one for validators, as you might want to not use them. It is all in npm package inside `dist` directory.

**Comment by shentao** [comment]
I think we could also add it to the GitHub repository so one could just download them. :)

**Comment by andrisi** [comment]
Thanks!

**Comment by andrisi** [comment]
window.Validation does not seem to be defined after including vuelidate.min.js. Is this still the object to use?

**Comment by Frizi** [comment]
I'm not sure from where you've got the `window.Validation` global, but it's called `window.vuelidate` and has `default` key in it, so you have to do `Vue.use(window.vuelidate.default)`

Referenced here: https://monterail.github.io/vuelidate/#sub-basic-usage

If you can point me to the place where `window.Validation` is still referenced?

**Comment by andrisi** [comment]
Thanks. window.Validation is at https://github.com/monterail/vuelidate under the Install section.

**Comment by Frizi** [comment]
OH! Thank you for pointing that, I've forgot to update the readme file alongside the docs. Will do it shortly.

**Comment by andrisi** [comment]
And how do I add the validators?

**Comment by Frizi** [comment]
What do you mean by add? Just use them. Validators are functions.

**Comment by andrisi** [comment]
I included vuelidate-validators.min.js but there is stil a js error saying "required" and "sameAs" not defined when I try to use them.

`		validations: {
    
			user: {
				email: { required, email },
				password_repeat: sameAs(this.user.password)
			}
		
	  },`

**Comment by Frizi** [comment]
And if you mean importing them from the browser bundle, it's again under the basic usage and under builtin validators in the docs.


```javascript
// global
Vue.use(window.vuelidate.default)

// local mixin
var validationMixin = window.vuelidate.validationMixin
```

and

> It is possible to use validators directly in browser by using a browser-ready bundle. Keep in mind this will always load all builtin validators at once.

```html
<script src="vuelidate/dist/validators.min.js"></script>
```
```javascript
var required = validators.required
var maxLength = validators.maxLength
```

https://monterail.github.io/vuelidate/#sub-builtin-validators

**Comment by andrisi** [comment]
Thanks for helping, I got it working. Great component.
