### ISSUE TITLE
validating child components from parent component.

### ISSUE THREAD

**Issue by space87** [monterail/vuelidate#333]
I am trying to validate form input fields from a parent/grandparent component. we have form that is made up of child components and grand children components and when the user clicks the submit button we wanted to have access to the $v on the top level component but i cant seem to get it work.

any help on this one ?

**Comment by SMoni** [comment]
Got more or less the same question...

**Comment by jean-moldovan** [comment]
Had the same scenario. Was able to make it work using $refs.
Basically a child form would have a `touch` method:
```
touch () {
  this.$v.formData.$touch()
}
```

And in your parent you would do:
```
submit () {
   this.$refs.childForm.touch()
}
```

Valid / invalid state of each child form can be pushed to the parent using events:

In your child form:
```
computed: {
  ready () {
    return !this.$v.formData.$invalid
  }
},
watch: {
  ready (val) {
    this.$emit('ready', val)
  }
}
```

And in your parent
```
<child-form @ready="isReady => readyToSubmit = isReady" />
```

Hope this helps! Let me know if there is anything else.

**Comment by SMoni** [comment]
Thanks for the answer; I'll give it y try :)

**Comment by SMoni** [comment]
Gave it a try and it works... unfortunately it's not the solution I was looking for :(

**Comment by space87** [comment]
*update*  I figured a way of doing this and having it validate the information that was mapped to our vuex store. We use vuex-map-fields plugin and by mapping fields in parent component where vuelildate config was you can validate that field, and using provide()/inject methods to pass down $v to all descendants

**Comment by isneezy** [comment]
@space87 how did you used provide/inject? I'm getting `[Vue warn]: Injection "$v" not found`

**Comment by johanbaaij** [comment]
@isneezy Have you tried the following?

```
provide: {
  $v
}
```

**Comment by phprhl** [comment]
sadsadsad

**Comment by parth7676** [comment]
I was facing the same problem. Here is what I have done to solve it.

1. Created a global event pool. Where I can emit events using `$emit` and my child can subscribe using `$on` or `$once` and unsubscribe using `$off`. Inside your `app.js` paste the below code. Below is the list of event pool actions.

   - Emit: this.$eventPool.$emit()   
   - On: this.$eventPool.$on()   
   - Off: this.$eventPool.$off()   
   - once: this.$eventPool.$once()

`Vue.prototype.$eventPool = new Vue();`

2. Inside my child components, I have created a `watch ` on `$v` as below. Which emits the status of the form to the parent component.
```
watch: {
    "$v.$invalid": function() {
      this.$emit("returnStatusToParent", true);
    }
  }
```
3. Now inside you parent component handle the status as below.
`<ChildComponent @returnStatusToParent="formStatus =>isChildReady=formStatus"></ChildComponent>`

4. Now to display the proper errors to the users we will `$touch` the child form. For the we need to emit an event in the above-created event pool and our child will subscribe to that.

parent:
` this.$eventPool.$emit("touchChildForm");`

child:
```
 mounted() {
    this.$eventPool.$on("touchChildForm", () => {
      this.$v.$touch();
    });
  },
  destroyed() {
    this.$eventPool.$off("touchChildForm", () => `{});`
  }
```

Hope it helps :)

**Comment by kishorpatel85** [comment]
@parth7676 

works !! 

it does show the error in child component but how does the parent component know about the error in child component and stop from submitting the form.

`this.$v.$touch();
      this.$eventPool.$emit("touchChildForm");
      if (this.$v.$pending || this.$v.$error) {
        Toast.fire({
          icon: "error",
          title: "You Are Missing Some Fields"
        });
        return;
      }
      alert("submitting form !");`

i currently do this on submit . So it does show error in child component but the how the know the same in parent .

**Comment by parth7676** [comment]
@kishorpatel85 The way I handled it instead of handing the validation error at child level pass them to the parent
