### ISSUE TITLE
Automatic $touch()

### ISSUE THREAD

**Issue by andrisi** [monterail/vuelidate#34]
Could you include an option to automatically run validators on any change? As I unserstand I need to add an something like @change="$v.email.$touch()" to every input I have and this kind of kills the mood. Should be optional obviously, but it's also a nobrainer that it would be useful in many cases. Thanks.

**Comment by Frizi** [comment]
Validators are running every time. If you don't need the $dirty flag, you can just ignore $touch and $reset. Validators and $valid will still work.

There is a reason it's not done automatically. First of all, validators are decoupled from the forms. You can validate anything, it doesn't have to be an input field. Second, you may want to listen to a totally different event. If you want to automate stuff for yourself, just make a component.

```html
<template>
  <input :value="value" @input="$emit('input', $event); v.$dirty()" />
</template>
<script>
  export default {
    name: 'MyInput',
    props: ['value', 'v']
  }
</script>
```
and just use it like that
```html
<my-input v-model="email" :v="$v.email" />
```

**Comment by andrisi** [comment]
Thanks.
