### ISSUE TITLE
How can I check which validator is responsible for the error?

### ISSUE THREAD

**Issue by Billybobbonnet** [monterail/vuelidate#353]
Hello,

I planned to use Vuelidate but I couldn't find any way to check if a field with several validator could detail which one is ok and which one is not. 

I can't find an answer in the docs, SO, or google, so I ask it here.

**Comment by downace** [comment]
Use validation object, prop is named by validator name. Check first example: https://monterail.github.io/vuelidate/#sub-basic-form. Here, `$v.name.required` and `$v.name.minLength` is what you need
