### ISSUE TITLE
Vuex support

### ISSUE THREAD

**Issue by koljakutschera** [monterail/vuelidate#36]
Is https://github.com/vuejs/vuex supported?

**Comment by shentao** [comment]
It depends on what do you understand by *supported*. 
Vuelidate doesn’t interfere with Vuex in any way. If you use `mapState` or `mapGetters` in your component, you can declare validations for that fragments of the state / getters, just like you would for data declared in `data () { return { . } }`.

In other words – you can declare validations for whatever value that is available on your component’s `this`.

Does that answer you question? :)

**Comment by koljakutschera** [comment]
Perfect. Thx - nice work!

**Comment by Julien76** [comment]
Hi,
Could you please post a simple example on how Vuelidate can be used with Vuex?
I can't get to make it works.
Thanks.

**Comment by xxRockOnxx** [comment]
@shentao I understand what you mean and everything's fine but how can I `$touch` a property on `input` or `change` if it's on another component? Is it possible to make `$v` global or something like that in order for child component to do `$touch` ?

**Comment by odranoelBR** [comment]
Yea um needing something similar. 5 childs components with thers validations, mas my parent Just react when all them are valor.
