### ISSUE TITLE
Helpers dont work?

### ISSUE THREAD

**Issue by asgminfo** [monterail/vuelidate#363]
import { required, email, minLength, helpers } from 'vuelidate/lib/validators'

const alpha = helpers.regex('alpha', /^[ a-zA-Z -]*$/)

result: 

 [Mostrar/ocultar detalles del mensaje.] TypeError: __WEBPACK_IMPORTED_MODULE_1_vuelidate_lib_validators__.helpers is undefined[Aprender más] app.js line 2035 > eval:10:5
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html

**Comment by kamleshkatpara** [comment]
try this : 

```
const alpha = value => {
  if (typeof value === 'undefined' || value === null || value === '') {
    return true
  }
  return /^[ a-zA-Z -]*$/.test(value)
}
```

**Comment by asgminfo** [comment]
Thanks, this work: 

const alpha = value => {
  if (typeof value === 'undefined' || value === null || value === '') {
    return true
  }
  return /^[a-zA-Z\s]+$/g.test(value)
}

TY.
