### ISSUE TITLE
Dynamic inputs not validating (bis)

### ISSUE THREAD

**Issue by Sweetyy** [monterail/vuelidate#377]
Hi !

I'm sorry to do a new ticket for this issue that already exists but there is no way to figure it out even with my best friend 'GOOGLE' ...

Here is the link with the old ticket :
https://github.com/monterail/vuelidate/issues/356#issue-348755709

My code is approximately the same as his.

Thanks in advance :)

**Comment by kosanr1** [comment]
Closing this issue, for more information please follow #356
