### ISSUE TITLE
Between numbers from state

### ISSUE THREAD

**Issue by balazscsintalan** [monterail/vuelidate#39]
Hi!

Fist of all, I really like the package, but I got stock. How is it possible to pass values from the state dinamycally to validators? (If it is possible)

What I was trying to achieve is passing min, max value to between:

Simplified example:
```javascript
export default {
	data() {
		return {
			amount : 1,
			min : 100,
			max : 10000
		}
	},
	validations : {
		amount : {
			required,
			between : between(this.min, this.max)
		}
	}
}
```
But "this" seems to be undefined here, because I keep getting "Cannot read property 'min' of undefined" error. How could I solve this issue?

(Min and max value would change depending on other conditions)

Thanks!

**Comment by shentao** [comment]
That would be:
```
validations : {
  amount : {
    required,
    between () { 
      return between(this.min, this.max)
    }
  }
}
```
Validator functions are called with your component’s `this` context. Look into the custom validators section in the docs :) 

Happy holidays!

**Comment by balazscsintalan** [comment]
Ah, thanks! Sorry I missed that.
Happy holidays! :-)
