### ISSUE TITLE
Dynamic validation schema not updating when optionMergeStrategy defined

### ISSUE THREAD

**Issue by RipkensLar** [monterail/vuelidate#412]
Hi,
I have a mixin where I load validation rules from my backend and assign them to the data property in the created hook. This works as expected. Now I want to expand these validation rules in my components at will. I wrote a customMergeStrategy to merge the two validation rules, but it seems like this disables the behavior of the validations () function, because it does not jump into it when I do the following in created:
```
this.validationRules = {
    required,
    minLength: minLength(5)
}
```
I expected it to jump in the validations() function and to return the correct validation rules:
`return {
  			text: this.validationRules
    	}`

Am I missing a point or is this a bug?

Here is a fiddle which shows my problem (without the mixin and with the customMergeStrategy doing nothing but returning the validation object to keep things as simple as possible):
https://jsfiddle.net/LarsRip/hy0joanc/8/

**Comment by kosanr1** [comment]
When you call validations function in your customMergeStrategy, your `this` is changed to `window`. Use third argument and bind function with component. 

```
Vue.config.optionMergeStrategies.validations = function (toVals, fromVals, vm) {
  var validations = fromVals.bind(vm)
  return validations
}
```

**Comment by RipkensLar** [comment]
@kosanr1 Thanks for your quick reply. I see how the bind function works in the fiddle. I tried it in my project, but it didn't work there. "vm" is always undefined. I extended my fiddle by vue-router and my mixin logic so you can see the whole process and what's going on:
https://jsfiddle.net/LarsRip/hy0joanc/54/

As you can see the validations will not update when this.validationRules = this.$route.params.validationRules is called. I still can't figure out why.
What I want to achieve is an object like this:
```
{
  currentModel: {
    attributeXy: {
      minLength: minLength(12)
    }
  },
  text: {
    required,
    minLength: minLength(5)
  }
}    
```

**Comment by engblh** [comment]
@kosanr1 when you rules from backend what kind of data format are you using: example

{
      serial_number: {
        required,
        minLength: minLength(4),
      },
      device_id: {
        minLength: minLength(10),
      },
    }

**Comment by RipkensLar** [comment]
Found the solution:
You can simply use the merge strategy from data:
`Vue.config.optionMergeStrategies.validations = Vue.config.optionMergeStrategies.data`

Working fiddle:
https://jsfiddle.net/zw6d5bp9/
