### ISSUE TITLE
RequiredIF/unless does not seem to work.

### ISSUE THREAD

**Issue by SeverinGerigk** [monterail/vuelidate#415]
Hello,

im new to all of this but i came pretty far think. All Validations are working. Now i need to Validate stuff only if an specific option is choosen.  So i  found requirdedIF/unless and tryed both. Sadly neither of them are working. What am i doing wrong? 

import Vuelidate from 'vuelidate'
import { required, minLength, email, requiredIf, requiredUnless } from 'vuelidate/lib/validators'

validations: {
      register: {
        companyName1: {
          required
        },
        Number: {
          required,
          minLength: minLength(10)
        },
        street: {
          required
        },
        zipCode: {
          required
        },
        city: {
          required
        },
        countrycode: {
          required,
          mustNotBeDefault
        },
        customerEmail: {
          required,
          email
        },
        iban: {
          required: requiredIf((this.paymentMethod === 'SEPA Direct Debit')),
          isValidIBANNumber
        },
        bic: {
          required: requiredUnless((this.paymentMethod === 'Bank Transfer')),
          isbicvalid
        }
    }
  }

Any hint would be apreachiated.

Thanks !

Severin

**Comment by metalsadman** [comment]
what does isValidBANNumber validates? if it validates for the requiredIf then i suppose you can pass it there, otherwise you may follow their example for validating a requiredIf. something like `required: requiredIf((nestedModel) => nestedModel.paymentMethod === 'SEPA Direct Debit')`.

**Comment by SeverinGerigk** [comment]
@metalsadman thanks again. i just fixed it with two buttons now. isValidBANNumber validates if the given sting is a valid IBAN. this sould only be required if the user chooses the payment option "SEPA" 
anyway i have a work around now. If you have a fix feel free to answer otherwise i would close this case.

**Comment by SeverinGerigk** [comment]
if your interested in the full iban validation here your go: 

function isValidIBANNumber (input) {
  var CODE_LENGTHS = {
    AD: 24,
    AE: 23,
    AT: 20,
    AZ: 28,
    BA: 20,
    BE: 16,
    BG: 22,
    BH: 22,
    BR: 29,
    CH: 21,
    CR: 21,
    CY: 28,
    CZ: 24,
    DE: 22,
    DK: 18,
    DO: 28,
    EE: 20,
    ES: 24,
    FI: 18,
    FO: 18,
    FR: 27,
    GB: 22,
    GI: 23,
    GL: 18,
    GR: 27,
    GT: 28,
    HR: 21,
    HU: 28,
    IE: 22,
    IL: 23,
    IS: 26,
    IT: 27,
    JO: 30,
    KW: 30,
    KZ: 20,
    LB: 28,
    LI: 21,
    LT: 20,
    LU: 20,
    LV: 21,
    MC: 27,
    MD: 24,
    ME: 22,
    MK: 19,
    MR: 27,
    MT: 31,
    MU: 30,
    NL: 18,
    NO: 15,
    PK: 24,
    PL: 28,
    PS: 29,
    PT: 25,
    QA: 29,
    RO: 24,
    RS: 22,
    SA: 24,
    SE: 24,
    SI: 19,
    SK: 24,
    SM: 27,
    TN: 24,
    TR: 26
  }
  const iban = String(input).toUpperCase().replace(/[^A-Z0-9]/g, '') // keep only alphanumeric characters
  const code = iban.match(/^([A-Z]{2})(\d{2})([A-Z\d]+)$/) // match and capture (1) the country code, (2) the check digits, and (3) the rest
  // check syntax and length
  if (!code || iban.length !== CODE_LENGTHS[code[1]]) {
    return false
  }
  // rearrange country code and check digits, and convert chars to ints
  const digits = (code[3] + code[1] + code[2]).replace(/[A-Z]/g, function (letter) {
    return letter.charCodeAt(0) - 55
  })
  // final check
  return mod97(digits)
}

function mod97 (string) {
  let checksum = string.slice(0, 2)
  let fragment
  for (var offset = 2; offset < string.length; offset += 7) {
    fragment = String(checksum) + string.substring(offset, offset + 7)
    checksum = parseInt(fragment, 10) % 97
  }
  return checksum
}

Not from me i copied it ... sadly i can not tell u from whre right now.
