### ISSUE TITLE
Get validation error from child component.

### ISSUE THREAD

**Issue by hasib32** [monterail/vuelidate#43]
I created a Google place autocomplete component. That component only has a location field. I'm using that component in several places in my site. But I'm not sure how can I get the validation error from that component in parent component.

**Comment by Frizi** [comment]
Hi!

The idea was rather to pass the validation object down to child components than to extract it from them.

That way you can have something like

```html
<MyInput :v="$v.value" v-model="value">
```

And then you can use `this.v` as usual inside the component. This keeps the convention of defining the whole validation schema in single place.

If you really don't like that idea, there is still a way though by referecing child components via `$refs`. I woudn't recomend that too hard though, as refs are not reactive by default. You have to assign them to data.

I think that could be possibly simplified by adding direct support for that case into vuelidate, but I'd like to stress out that passing `v` down should remain a preferred solution.

That's a messy but working example in current version (please forgive the inline render):
```html
<template lang="pug">
  div

    .form-group(v-bind:class="{ 'form-group--error': $v.child.$error }")
      label.form__label Child component
      child(ref="child")

    .form-group(v-bind:class="{ 'form-group--error': $v.child.$error }")
    span.form-group__message(v-if="$v.$error") Child is invalid.

    pre
      | $v: {{ $v }}
</template>

<script>
import { required } from 'vuelidate/lib/validators'

const Child = {
  render (h) {
    return h('input', {
      staticClass: 'form__input',
      on: {input: (ev) => {
        this.value = ev.target.value.trim()
        this.$v.value.$touch()
      }},
      props: {
        value: this.value
      }
    })
  },
  data () {
    return {
      value: 'hello'
    }
  },
  validations: {
    value: {
      required
    }
  }
}

export default {
  components: {
    Child
  },
  data () {
    return {
      refs_: {}
    }
  },

  mounted () {
    this.refs_ = this.$refs
  },

  validations: {
    child () {
      return this.refs_.child && this.refs_.child.$v.value
    }
  }
}
</script>
```

Hope it helped and please share your feedback.

**Comment by nerijunior** [comment]
@Frizi the first example worked fine for me! Thanks.

**Comment by gentisaliu** [comment]
In the first example: the validation schema is indeed in one place, but the template which displays the validation errors is inside the child component `MyInput`.

One could use slots, but then what's the point of the child component if it's not reusable.
