### ISSUE TITLE
"Cannot convert undefined or null to object" occurring in single-file nuxt component 

### ISSUE THREAD

**Issue by adrianbw** [monterail/vuelidate#431]
I'm sorry that I don't have a JSFiddle of this, I can't figure out how to replicate the circumstances in my project. The deal is that when I try to have a simple setup like this, it throws the error in the subject line:
```javascript
<template>
  <input v-model="text" type="text" />
</template>

<script>
import { validationMixin, required } from "vuelidate";

export default {
  mixins: [validationMixin],
  data() {
    return {
      text: ""
    };
  },
  validations: {
    text: {
      required
    }
  }
};
</script>
```

I've also tried this:
```javascript
import Vue from "vue";
import Vuelidate from "vuelidate";
Vue.use(Vuelidate);
const { required } = Vuelidate;
```

Regardless, what it looks like is happening is that the template is sending over an undefined object for `validations`, rather than the actual validations. What am I missing?

**Comment by ZaidBarghouthi** [comment]
`import { required } from 'vuelidate/lib/validators'`

**Comment by adrianbw** [comment]
I forgot to say thank you, here! Reading is hard, apparently. Really appreciate the help.
