### ISSUE TITLE
Search not working on Russian language  first letter is uppercase (v 2.0.0-beta.12)

### ISSUE THREAD

**Issue by bigperson** [monterail/vuelidate#46]
Search not working in v. 2.0.0-beta.12 
```HTML
<multiselect
                                    :value="orderStore.tehcenter"
                                    @select="onSelectTehcenter"
                                    :options="orderStore.tehcenters"
                                    :searchable="true"
                                    :close-on-select="true"
                                    :show-labels="false"
                                    :allow-empty="false"
                                    :internal-search="true"
                                    placeholder="Выберите техцентр"
                                    label="name"
                                    track-by="id"
                                    group-values="tehcenters"
                                    group-label="city"
                            >
                            </multiselect>
```
I want to search on `label="name"`, name it is сyrillic string on Russian language and If the first letter is uppercase, It does not work :(
Example:
name - `Москва - ООО Рога и Копыта ул. Ленина 15 А`
Search string - `Москва` - working
Search string - `Москва` - not working
Search string - `МОСКВА` - not working

How to search not case insensitive?

**Comment by Frizi** [comment]
@bigperson I believe this issue belongs to different repository :)

Please fill it again in http://github.com/monterail/multiselect

**Comment by shentao** [comment]
That's cute :D 
https://github.com/monterail/vue-multiselect actually xD
