### ISSUE TITLE
distinguish between validation rule and validator

### ISSUE THREAD

**Issue by Gr33nbl00d** [monterail/vuelidate#48]
**A validation rule** 
is very abstract, like is alphanumeric,isnumber,istext,haslength and so on. They can be usefull on nearly all systems.

**A Validator**
Makes use of these rules combines them for a more specific usecase for example username validation.
It also contains default validation texts for each rule like "Username is required" for the rule Required and so on. Validators are more specific they usually apply to a whole system. If we would create a UserValidator for "Company A" it might only fit to this company as it can contain buisness logic, but it might be used in a lot of different services and also clients of this "Company A".

i know this is somehow possible right now but i would add more support for this pattern as i think it makes sense for a lot of systems. 

**More detailed:**
At the moment we have a list of validation rules which we can define for a specific model variable.
for example i define a username should be required and minlength of 4:

`username: {required, minLength: minLength(4)}`

I would add a level of abstraction and say additionaly to these common validation rules i would like to have a validator which can use these rules:

`username: userNameValidator`

The UsernameValidator can be defined somewhere else. The validator should contain:
One or more Rules and also default error texts for each rule. Which can be used (but dont need to) in the validation markers for example via "$v.username.required.defaultText" to display this text. It is nice that you can define the text in vuelidate for each marker but often you want to show always the same text for the same problem. 

It might also be usefull to get a list of errortext like $v.username.defaultTexts which will return all failing texts

If you need to validate a user in your system it is likely that the way how to validate a username will be equal on the whole system.

You can use this validator if you register a new username, or if you would like to write a private message to some username or if you forgot your password and need to enter username and email and so on.

These validatos can be defined externaly and can also be used on server side. To be secure that the user input arrived on my service i will check the following during register:

I will check this on client:
    username syntax (alphanum,max/min length)
if this was successfull i want to call my service
the service will execute the same checks again 
if all are successfull the service additionaly checks the database if the user already exist
the validation result is then returned to the client and shown to the user.

It might makes sense to allow to combine Validators for example i could create a UsernameSyntaxValidator with rules and errortexts and a UsernameDatabaseValidator which will do a call to the database it would be nice if i could combine these two.

I could than create a basic syntax validator and could derive an servervalidator which will do additionaly a check of the database and for the client i can derive from the syntax validator and do an async check to the service.

One additional thing. it might be also usefull that an i18n method can be defined. In this case the i18n function will be called to lookup the real string. For example i define as text for username required:

"username_required"; instead of "Username is required"

i than define some i18n function

i18n:function(key){
  return textlookup(key);
}
this method will than be called with the validation string if defined. For one language systems where no i18n function is defined the string is simply returned like it is now. But if an i18n function is defined the text is translated to the real string.

What do you think?

**Comment by pczarn** [comment]
Reuse of groups of validators should be possible in a clean way. I think you can already reuse them, because validations are just objects, for example
```
const userNameValidator = { required, minLength: minLength(4) }
```
```
validations: {
  username1: userNameValidator,
  username2: userNameValidator
}
```
---
Perhaps i18n can work as a set of rules that match on the validator path.
```
{
  ['username', 'required']: 'User name is required',
}
```

**Comment by Frizi** [comment]
@Gr33nbl00d What @pczarn just did about predefined set of validations holds true and I consider it official solution. It's all just objects and functions, so do make use of that.

Regarding i18n, I think it almost exclusively belongs to the view layer. What's left for the model is to specify input data. More on that in #3. Thanks for your suggestion though, it kinda made it into the `$params` I just outlined in the other issue :)

**Comment by Gr33nbl00d** [comment]
ok i give it a try on monday :)
