### ISSUE TITLE
Validation inside components

### ISSUE THREAD

**Issue by andrisi** [monterail/vuelidate#49]
Perhaps this is a mistake on my side, but I don't know how to use validation results ($v) inside a component which has some data passed to it through comps. I would define the validation in the root app as it has all the data, but would use the results in the component. The problem is that at the time of the component initialization the $v property is not yet available as it seems, so there is no way to pass it down to the component through a props definition.

**Comment by andrisi** [comment]
Sorry, it was my mistake after all. Keep up the good work!

**Comment by Frizi** [comment]
Glad you resolved it. $v and all it's structure should be immediately accessible, so it's safe to pass it down the tree of components.
