### ISSUE TITLE
How to do onSubmit validation?

### ISSUE THREAD

**Issue by thupi** [monterail/vuelidate#54]
I really like this way of doing validation and would like a simple way to du onSubmit valdiation.

I do not think the optimal UX is to show error messages while the user starts to type. The behavior i am looking for could be achieved by making a flag ad to multiple tenery statements  however i would like the validation plugin to have a way to handle this situation.

**Comment by Flashwit** [comment]
It's pretty simple to do that. Set up your validations like normal and then do a .$touch() on the whole validation object when the submit button is pressed. Then you just check if it's valid before submitting.

**Comment by shentao** [comment]
And by *valid* we mean checking the `$error` property. It is a combined value of `$invalid && $dirty`.
