### ISSUE TITLE
Is it possible to use a variable for validation?

### ISSUE THREAD

**Issue by muchacho-diesel** [monterail/vuelidate#55]
Can I use a variable to validate? See example below:

    data: function () {
        return {
            variable: 10
        }
    },
    validations: {

        form: {
            example: {
                between: between(this.variable, 400)
            }
        }
    },

**Comment by Frizi** [comment]
Yes, it's possible. You just have to enclose it into another function.

```javascript
example: {
    between (value) {
        return between(this.variable, 400)(value)
    }
}
```

**Comment by canyoudev** [comment]
Not working!

**Comment by canyoudev** [comment]
@Frizi what is `value` in your example? Why this is not working?

```js
maxLength () {
        return maxLength(this.countProp)
      }
```

**Comment by joelpro2** [comment]
@ChrisRobston you can do that like this

`
validations () {
    return {
        textfieldValue: {
            required,
            maxLength: maxLength(this.countProp)
       }
    }
}
`
