### ISSUE TITLE
About computed properties 

### ISSUE THREAD

**Issue by onurozkan** [monterail/vuelidate#57]
Hello,

I am currently having problems with computed property validation. 

Versions are listed below.
- "vue": "^2.1.8",
- "vuelidate": "^0.2.0",

I have 2 types of validations, local params (data) & computed properties via components props.

- **First screen, initial view of component. Both same.**
![](http://i.imgur.com/TmnKIB2.png)

- **After filling fields, whole $v object behaves differently.**
![](http://i.imgur.com/6l75qtT.png)

Here is my validation property

```
validations: {
    test: {required}, // data
    user: { // computed and nested
      Name: {
        required
      }
    }
  },
```

And both fields have touch on input

```
<div class="form-group">
  <label class="col-md-3">Data</label>
  <div class="col-md-9">
    <input type="text" class="form-control" v-model="test" @input="$v.test.$touch()">
    <pre>name: {{ $v.test }}</pre>
  </div>
</div>
```

I used vuelidate as a mixin.

```
import { validationMixin } from 'vuelidate'
import { required, minLength, between } from 'vuelidate/lib/validators'

export default {
  mixins: [validationMixin],
  ...
```

Not sure i forgot something to add or its a bug. Any ideas?

Thanks.

**Comment by mplno** [comment]
I think I'm having a similar issue, so will comment here first. I'm trying to make a simple input form component that will validate depending on the type of info it takes, like emails and phone numbers. I'm trying to set my validators based on props, but I think stuff is happening at the wrong point in the digest cycle.

```javascript
import { validationMixin } from 'vuelidate'
import { email } from 'vuelidate/lib/validators'

export default {
  props: ['value', 'type'],
  mixins: [validationMixin],
  validations: {
    value: {
     email: this.type === 'email' ? email : null 
    }
  }
}
```

I'm never able to set `$v.value.email`.

Are these related? Any ideas for a workaround? I'm trying to avoid writing a different component from every type of input.

**Comment by Frizi** [comment]
I'm not able to really reproduce the initial problem. Please provide a fiddle if it still applies and reopen this issue.

@mplno You are missing a closure.
```javascript
  validations: {
    value: {
      email () {
        return this.type === 'email' ? email : null
      }
    }
  }
```

**Comment by cashmisa** [comment]
I am having the same issue as @onurozkan 

I am trying to validate computed properties with getter (from state) setter (mutate state). It doesn't get validated...i tried to reproduce the issue here:  
https://jsfiddle.net/cashmisa/hg802juz/1/

I read on vuelidate page that it 'Validates different data sources: Vuex getters, computed values, etc.' but don't seem to find any example.. only using computed property as parameter to validate other fields... 

Still new to vue and frontend.. If I 'copy' vuex state object into component's data property, and bind with data property, i can validate just fine. But not with two-way computed property.

`computed: {
    ...mapState('application', [
      'application'
    ]),
    name: {
      get () {
        return this.application.name
      },
      set (val) {
       //calling vuex mutation method
        this.UPDATE_APPLICATION_WITH_KV({ key: 'name', value: val })
      }
    },
...
validations: {
    name: {
      required
    }
  }`

Would really appreciate some help and feel free to let me know if there are better ways! Thanks!

**Comment by AshleyCao** [comment]
@cashmisa check Frizi comments on #241. 
I had similar problem. What I did was using [watch](https://vuejs.org/v2/api/#vm-watch). 
```
props: {
        selectItem: {
            required: false,
            type: Object,
        }
    },
data() {
        return {
            confirmPassword:"",
            password:""
        }
    },
 watch: {
        password(value){
            this.selectItemInModal.Password = value;
        }
 validations: {
       password: {
            required: required, 
           minLength: minLength(6)
        },
    },
```
Syntax maybe a little bit different since I use Nuxt
