### ISSUE TITLE
Bower Package

### ISSUE THREAD

**Issue by EpicKris** [monterail/vuelidate#58]
Add as package to [bower.io](https://bower.io).

**Comment by Frizi** [comment]
I haven't used bower like for at least a few years. Is there still any value in using bower? I'd strongly recommend using a bundler, like webpack/browserify/rollup, so you can use the package from npm. I'd like to avoid adding another step to the release process unless it's really useful to do.

**Comment by koronowicz** [comment]
Hey, many projects are still using bower. I think it should be supported. I know it's flawed, but when trying to implement vue.js you shouldn't be bother about package manager.

**Comment by shentao** [comment]
That should be as easy as adding a file pointing to the umd module. Thanks for the suggestion!

**Comment by Frizi** [comment]
I published a bower package. Version 0.3.0 should be available with `dist` inside, which provides minified files.
