### ISSUE TITLE
Dirty flag propagation

### ISSUE THREAD

**Issue by ecmel** [monterail/vuelidate#64]
Using touch on nested field does not propagate to top level dirty flag unless all nested fields are dirty.

In my opinion, setting dirty on a nested field should set dirty for all parents.

It can be tested on https://monterail.github.io/vuelidate/#sub-data-nesting

form$dirty is true if both nestedA.$dirty and nestedB.$dirty are true.

This is true for flat data too. All fields should be dirty in order the top level dirty flag turns dirty.

**Comment by ecmel** [comment]
This may be the correct behavior for validate on save scenario so code may depend on this behavior.

**Comment by Frizi** [comment]
That is indeed intended. $touch propagates to children, not the other way around.

**Comment by Webifi** [comment]
The problem here is that there doesn't seem to be an easy way to check if any child is $dirty or $invalid.  I would expect that $v.$dirty would return true if any children are dirty. This is clearly not the case.

**Comment by Frizi** [comment]
This is probably going to be resolved by #84
