### ISSUE TITLE
email validator

### ISSUE THREAD

**Issue by ecmel** [monterail/vuelidate#65]
email validator should return true for null, undefined and empty values.

**Comment by 38elements** [comment]
If the value is null or undefined and you want to invalidate it,
I think that email validator is supposed to be used with [required validator](https://github.com/monterail/vuelidate/blob/master/src/validators/required.js).

**Comment by ecmel** [comment]
If an e-mail field is not required but if entered should validate as e-mail, it should be necessary to behave like minLength and maxLength validators.

minLength returns true for null, undefined and empty values.

**Comment by shentao** [comment]
Returning true for empty values should be true for everything except for `required` and `sameAs`. If it’s different – it’s a bug.
We do welcome Pull Requests! :)
