### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by j-baconator** [monterail/vuelidate#69]
Hey,

I am also having some difficulty getting this to work, not sure where I am going wrong. Some guidance would be very much appreciated.

app.js 
```
import Vue from 'Vue'
import Vuelidate from 'vuelidate'
import { required, alpha, email } from 'vuelidate/lib/validators'

Vue.use(Vuelidate)

new Vue({
  el: '#form',
  data: {
    name: '',
    email: '',
  },
  validations: {
    name: {
      required,
      alpha,
    },
    email: {
      required,
      email,
    },
  },
})
```

Here is my html
```
<form id="form">

<input type="text" placeholder="Name" v-model="name" name="name">
<span v-if="!$v.name.alpha">Please enter a valid name.</span>

<input type="text" placeholder="Email" v-model="email" name="email">
<span v-if="!$v.email.email">Please enter a valid email.</span>

</form>
```

When I try to output {{ $v }} I get nothing either.

**Comment by shentao** [comment]
I think you might have to change the Vue import to:
`import Vue form 'vue'` (with all lowercase module name)

I created a JSFiddle with it:
https://jsfiddle.net/jv5tLhqh/2/

**Comment by j-baconator** [comment]
Thanks @shentao I changed it to lowercase 'vue' and it still does not recognize the vuelidate validations.

I get the following error on my console:

`[Vue warn]: Error when evaluating expression "!$v.name.alpha": TypeError: Cannot read property 'name' of undefined`


Any ideas? I feel like I am doing everything right.

**Comment by asxcandrew** [comment]
I have the same error

**Comment by shyamchandranmec** [comment]
I have the same error.. Any idea how to resolve this.

**Comment by shyamchandranmec** [comment]
I solved it by adding this to the plugins section in nuxt.config.js..

**Comment by 38elements** [comment]
The following code works.

```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
    </head>
    <body>
        <form id="form">
            <input type="text" name="name" placeholder="Name"  v-model="name">
            <span v-if="!$v.name.alpha">Please enter a valid name.</span>
            <input type="text" name="email" placeholder="Email" v-model="email">
            <span v-if="!$v.email.email">Please enter a valid email.</span>
        </form>
        <script src="https://unpkg.com/vue/dist/vue.js"></script>
        <script src="vuelidate.min.js"></script>
        <script src="validators.min.js"></script>
        <script>
            Vue.use(window.vuelidate.default);
            let vm = new Vue({
                el: '#form',
                data: {
                    name: '',
                    email: ''
                },
                validations: {
                    name: {
                        required: validators.required,
                        alpha: validators.alpha
                    },
                    email: {
                        required: validators.required,
                        email: validators.email
                    }
                }
            });
        </script>
    </body>
</html>
```

**Comment by tomsarduy** [comment]
Same error with a basic example:
###HTML
`<input type="text" v-model="email" v-on:input="$v.email.$touch" v-bind:class="{error: $v.email.$error, valid: $v.email.$dirty && !$v.email.$invalid}"/>`

###JS:
```
import { required, email } from 'vuelidate/lib/validators';

export default {
  name: 'app',
  data() {
    return {
      email: '',
      name: '',
    };
  },
  validations: {
    email: { required, email },
  },
};
```

**Comment by Frizi** [comment]
It works for me: https://jsfiddle.net/h4adqy4k/
If the issue is still present for you, please reopen and provide an example.

**Comment by wdews** [comment]
Having the same issue. Issue occurs when attempting to bootstrap using the Vuelidate mixin -or- the global installation method of using `Vue.use(Vuelidate)`. Can't provide an example since our codebase is private but would be great if you could take a closer look and replicate.

**Comment by Frizi** [comment]
@wdews Please isolate the minimal reproduction from your application, otherwise it's just reading tea leaves.

**Comment by wdews** [comment]
@Frizi Figured it out...it was my simple misunderstanding of how to properly export multiple things at once in ES6 syntax using export... Since my validations object will be reused in multiple places, I abstracted it into its own file with a validate function I wrote to pull in the appropriate message corresponding with failed rules. When exporting, I foolishly used export default { validate, validations } versus the correct export { validate, validations }. I also wasn't properly destructuring when importing said module. import validations from '@/modules/validation' became import { validations } from '@/modules/validation'. Solved my woes!

**Comment by LouiseStroeh** [comment]
@shyamchandranmec Could you please provide an example of how you made it work with nuxt? I am getting the same error as everyone else here:  'Error in render function: "TypeError: Cannot read property 'pcs' of undefined"'

**Comment by shyamchandranmec** [comment]
@LouiseStroeh which version of vuelidate are you using?

**Comment by tinsqt** [comment]
i have the same error

**Comment by theerayut69** [comment]
I have the same error

**Comment by Christilut** [comment]
I solved this with 
```js
plugins: [
  { src: '~/plugins/vuelidate', ssr: true }
]
```
Make sure to restart nuxt after this.

**Comment by deepikakiwitech** [comment]
I have the same error

Error in v-on handler: "TypeError: Cannot read property '$touch' of undefined"

<script>
    import { required, email, minLength, sameAs } from "vuelidate/lib/validators";

    export default {
        name: "app",
        data() {
            return {
                user: {
                    firstName: "",
                    lastName: "",
                    email: "",
                    password: "",
                    confirmPassword: ""
                },
                submitted: false
            };
        },
        validations: {
            user: {
                firstName: { required },
                lastName: { required },
                email: { required, email },
                password: { required, minLength: minLength(6) },
                confirmPassword: { required, sameAsPassword: sameAs('password') }
            }
        },
        methods: {
            handleSubmit(e) {
                this.submitted = true;

                // stop here if form is invalid
                this.$v.$touch();
                if (this.$v.$invalid) {
                    return;
                }

                alert("SUCCESS!! :-)\n\n" + JSON.stringify(this.user));
            }
        }
    };
</script>

**Comment by syamkumarkk** [comment]
> I solved this with
> 
> ```js
> plugins: [
>   { src: '~/plugins/vuelidate', ssr: true }
> ]
> ```
> 
> Make sure to restart nuxt after this.

Thank youuu... For NuxtJs the ssr must be true. I was using false. its resolved after making it true

**Comment by vitalik0790** [comment]
I have the same error "Uncaught (in promise) TypeError: Cannot read property 'super' of undefined". My code in the main.js
```
import { createApp } from 'vue';
import Vuelidate from 'vuelidate';

import App from './App.vue';
import router from './router';
import BaseDialog from './components/BaseDialog.vue'

const app = createApp(App);

app.use(router);
app.use(Vuelidate);

app.component('base-dialog', BaseDialog);

app.mount('#app');
```

**Comment by muhsin-k** [comment]
> I have the same error "Uncaught (in promise) TypeError: Cannot read property 'super' of undefined". My code in the main.js
> 
> ```
> import { createApp } from 'vue';
> import Vuelidate from 'vuelidate';
> 
> import App from './App.vue';
> import router from './router';
> import BaseDialog from './components/BaseDialog.vue'
> 
> const app = createApp(App);
> 
> app.use(router);
> app.use(Vuelidate);
> 
> app.component('base-dialog', BaseDialog);
> 
> app.mount('#app');
> ```
> 
> And when i'm writing `import Vue from 'vue'` there is no Vue in 'vue'

@vitalik0790 Did you able to fix this issue

**Comment by aureliomp** [comment]
it's work to me 
https://vuelidate-next.netlify.app/advanced_usage.html#using-component-mixin

**Comment by mcmiro** [comment]
I had the same error with NUXT 3. The solution was to wrap the whole form or your div with error handling in a client-only tag.

```
<client-only>
  <div v-for="error of v$.email.$errors" :key="error.$uid">
    <div class="text-red-400">{{ error.$message }}</div>
  </div>
</client-only>
```
