### ISSUE TITLE
Validations on collections with dynamic elements

### ISSUE THREAD

**Issue by sesegura** [monterail/vuelidate#73]
What i have is basically a collection of objects. There are inputs with v-model associated to those objects' properties and a button for removing an object from the array. Think of this as a list of contacts.

What the issue refers to specifically is: that when an element is removed from the array (which it's done with `splice`) the validations of the items left, get messed up. It seems like it stops tracking the items and even after retrying with several other ways, it's still the same.

Some of the solutions that i've tried are:
* Using `v-bind:key` in the template
* Using `$trackBy` with a key consisting in a random generated pseudoId for each element in the array
* Instead of using `splice` for removing the element, replacing the whole array
* Using `$reset`
* Combinations of all the options from above

I've noticed that even if i used the `$trackBy` option and  "printed" the `$v` object, the key for each object in the collection still corresponds to the item's index in the array.

I'll put some example code below.
_Forgive me if there's something wrong with it, i'm writing it from memory, but i hope you get the point_

```html
<div v-for="(person, index) in people">
    <input type="text" v-model="person.firstName" />
    <input type="text" v-model="person.email" />
    <span class="error" v-if="$v.people[index].firstName.$invalid">Email is required</span>
    <button v-on:click="remove(index)>Remove</button>
</div>
```

```javascript
{
    validations : {
        people : {
            $each : {
                email :  {
                    required : function(email, person) {
                          return (person.firstName && email) || email;
                    }
                }
            }
        }
    },
    data : {
        people : [{     // initialize as empty for showing the empty inputs 
             firstName : "",
             email : ""
        }]
    },
    methods : {
        add : function() {
            this.people.add({
                 firstName : "",
                 email : ""
            })
        },

        remove : function(index) {
            if (this.people.length === 1 ) { 
                this.people.splice(0, 1, {
                     firstName : "",
                     email : ""
                });
            } else {
                this.people.splice(index, 1);
            }
        }
    }
}
```

**Comment by Frizi** [comment]
This seems like a bug to me, I will need to test it more, but I think I might recognise it already.

It seems like you are referencing the object directly on array, but through the second parameter. It might be related to #51. While it is a bug (which might be fixed already, to be released), you probably can avoid it by simplifying your logic.

```javascript
$each: {
    email :  {
        required : function(email, person) {
            return (person.firstName && email) || email;
        }
    }
}
```

This validator can be simplified to not reference multiple values at once. `(A and B) or B` means simply `B`.

```javascript
$each: {
    email :  { required }
}
```


> I've noticed that even if i used the $trackBy option and "printed" the $v object, the key for each object in the collection still corresponds to the item's index in the array.

That's expected. `$trackBy` influences the validation state tracking, but original keys are still used as indices on validation object.

**Comment by sesegura** [comment]
Hello @Frizi, thank you for the answer and for the validation advice, but unfortunately it's just part of what the issue is. 

The real problem i think it's related to what [you said previously](https://github.com/monterail/vuelidate/issues/37#issuecomment-273082689) about keeping track of changes in arrays and not recomputing the `$each` validator. At the end, the items left in the array aren't being validated.

Can you let me know if this could be fixed or if it's a known issue/limitation?

**Comment by Frizi** [comment]
Please check it against current master. It contains said fix. I'm only waiting for $params feature to be finally finished and merged, then I'll do the release. If there is still a bug, it can also be fixed before that.

**Comment by sesegura** [comment]
Checked with master. It's working now, but it needed a little bit of workaround.
What i did was generating a pseudo id property to each element and using `$trackBy` with that id. I said i tried that before and didn't work, but now it's working good

@Frizi Thanks a lot! You may close this issue if there aren't more questions/suggestions :wink:

**Comment by Frizi** [comment]
@sesegura Could you also try without any $trackBy? Default is to track by the key/array index, it should still work.

**Comment by sesegura** [comment]
Already tried but didn't work either. 
Also tried with `v-bind:key="item.pseudoId` and no `$trackBy` but no results.

**Comment by Frizi** [comment]
Can you post the working example? It's a bug if it doesn't work by default.

**Comment by sesegura** [comment]
This is kind of the setup that is currently working for me:

```html
<!-- I added the key binding for example's sake but it's working even if it's not added -->
<div v-for="(item, index) in items" v-bind:key="item.pseudoId"> 
    <input type="textfield" name="name" v-model="item.name">
    <span v-if="$v.items.$each[index].$error">Error</span>
    <button v-on:click="remove(index)">Remove</button>
</div>
<button v-on:click="add">Add</button>
```

```javascript
{
  validations : {
    items : {
       $each : {
          $trackBy : 'pseudoId',
          name : VuelidateValidations.required
       }
    }
  },
  methods : {
      add : function() {
          this.items.push({
              pseudoId : Math.random(),  // the function i'm using is actually more elaborated than this
              name : ''
          });
      },
      remove : function(index) {
          if (this.items.length === 1) {
              this.items.splice(0, 1, {
                  pseudoId : Math.random(),
                  name : ''
              });
          } else {
              this.items.splice(index, 1);
          }
      }
  }
}
```

**Comment by Frizi** [comment]
```
          name : VuelidateValidations.required
```

This is odd. What you ment is probably
```
name: {
  required: VuelidateValidations.required
}
```

What you did should make the actual object `required`, which is always true. Actually weird it works, I have to test it.

**Comment by sesegura** [comment]
Sorry, i wrote the previous code example from memory, the actual example has that structure with `required` being inside the `name` object.
I'll edit my previous comment for making that fix in the example.

**Comment by Frizi** [comment]
@sesegura Thanks, that makes a lot of sense now 😄

**Comment by jamesjieye** [comment]
I have a similar issue. 

I use an array hold a list of choices of a question. Each choice have an input field with `v-model` bind to the `label` property of the choice in the array. And in the validation, the `label` is required.

I put a placeholder choice with empty label in the array for initial rendering. And then when editing an existing question which has a list of choices, I use `splice(0)` to clean up the placeholder choice and then use `push()` to add the existing choices.

The validation of the first choice always fails, even after I edit the choice label. And it is kind of fixed by printing the `$v` object. 

Here is the code.

```html
<li v-for="(choice, index) in question.choices" :index="index">
  <span class="fa fa-reorder drag-handler"></span>
  <input type="text" class="form-control input-sm label-input" v-model="choice.label">
  <span class="fa fa-plus-circle btn-choice add" @click="addChoice"></span>
  <span class="fa fa-minus-circle btn-choice remove" v-if="index !== 0" @click="removeChoice"></span>
  <p class="field-error" v-if="!$v.question.choices.$each[index].label.required && $v.question.choices.$each[index].label.$dirty">Blank choice is not allowed</p>
</li>
```

```javascript
validations: {
    question: {
      title: {
        required
      },
      type: {
        required
      },
      choices: {
        required,
        $each: {
          label: {
            required
          }
        }
      }
    }
  }
```

```javascript
/* This is the part that I add the placeholder choice */
this.question.choices.push({id: 0, label: '', sortOrder: 1})
```

The hack I use is print out the first choice in the `$v` object.

```html
<div class="hidden">{{ $v.question.choices.$each[0] }}</div>
```

**Comment by Frizi** [comment]
@sesegura @jamesjieye Please check your issues against latest version.

**Comment by chymz** [comment]
Bug fixed for me :)

**Comment by shrpne** [comment]
@Frizi I think it will be great to add `$trackBy` to the collection example in the docs because for now, it's pretty hard to find it.
Actually, I found it in this issue, but not in the docs :)

**Comment by ZatchMichael** [comment]
Sorry folks , how would you validate dynamic select inside datatable 
https://user-images.githubusercontent.com/47603281/52724826-74033080-2f86-11e9-9dd5-ea9db4dbfea2.png

**Comment by ZatchMichael** [comment]
Hi folks, im trying to achieve somthing similar but with a select inside a datatable ,but dont know how ,i want to click on validate button to validate all selects like this below:

![](https://user-images.githubusercontent.com/47603281/52724826-74033080-2f86-11e9-9dd5-ea9db4dbfea2.png)
