### ISSUE TITLE
Set the validations object at runtime

### ISSUE THREAD

**Issue by mbouclas** [monterail/vuelidate#78]
Is there a way to set the validations object of a component at runtime? The reason for this is that i find myself in a situation where i have to render fields coming from another source (like an array of fields) and thus, i cannot setup the validations object as i don't know anything about said fields.

I tried setting the validations object on the created hook where the data is made available but it's not working, the $v object in the template is not reflecting my setup. The fields are rendered in a v-for directive and i cannot know the type, name, required or any other property, as they are set by the user and are passed on from the backend.

Ideally, in some hook (mounted, created..) i can loop the fields like so

```
this.Form.fields.map((field ) => {
                if (field.required) {
                    validations.formData[field.varName] = {required};
                    if (field.type === 'email') {
                        validations.formData[field.varName]['email'] = email;
                    }
                }
            });
```

or something in this direction.

Any ideas?

**Comment by mkoryak** [comment]
i am doing this via another mixin added before vuelidate. The mixin is an object with a `beforeCreate` function inside of which `this.$options.validations` is available and can be modified.

This is my 3rd day coding vue, so its probably wrong, but it works

**Comment by mbouclas** [comment]
@mkoryak It doesn't work for me. Tried the mixins trick, set the `this.$options.validations` in the `beforeCreate` method but the validations are not reflected in the template. $v is not set properly. 

On a side note, instead of a mixin, i tried the plugin approach at some point, but nothing

**Comment by mkoryak** [comment]
Paste the code. It worked for me. 
You have the corresponding models setup too right?

**Comment by mbouclas** [comment]
Ok, this is after many tests so the code is not ideal, but you'll get the idea.

In the component 
```
   const SetupFormValidations = require('../mixins/setupFormValidations');

    export default {
        name : 'MiniForm',
        mixins : [SetupFormValidations],
        props: ['formSettings'],
        data () {
            return {
                Form : {},//Should be filled in the mixin
                formData : {},//Should be filled in the mixin
                locale : Vue.config.lang
            };
        },
  }
```

The mixin

```
import { required, email } from 'vuelidate/lib/validators';

module.exports = {
//Tried to set the data here after not reflecting in the component but no joy
/*    data () {
        return {
            Form :{},
            formData : {}
        }
    },*/
    beforeCreate () {
        this.Form =  (typeof window[this.$options.propsData.formSettings] !== 'undefined') ? window[this.$options.propsData.formSettings] : {}; //just an object holding the form fields
        let validations = {
            formData : {}
        },
            fields = {};

       //Iterate fields and assign them to 2 objects. One will serve as the model and the other will hold the validations
        this.Form.fields.map((field ) => {
            fields[field.varName] = '';//model for each field
            if (typeof field.required !== 'undefined' && field.required) {
                validations.formData[field.varName] = {required};//set the basic validation
                if (field.type === 'email') {//testing if i can assign custom validations, starting with email which already exists in the library. The idea is to auto-assign
                    validations.formData[field.varName]['email'] = email;
                }
            }
        });


        this.formData = fields;//assign to the model, does not reflect on to the component
        this.$options.validations = validations;//assign validations, does not reflect on to the component
    },

};
```

Finally, on the template, if i do
```
{{ $v.formData }}
{{ formdata }}
```

In the above template `$v.formData` and `formData` are both not set. The this.Form and this.formData are not filled in the mixin although it is my understanding that they should have

**Comment by squarenomad** [comment]
Having the same problem. Mixin approach doesn't seem to help either, but I only just started with VueJS. @mkoryak could you share a code snippet?

**Comment by squarenomad** [comment]
Pull request [52](https://github.com/monterail/vuelidate/pull/76) apparently addresses this, hoping it gets merged soon

**Comment by mkoryak** [comment]
I wonder if it has anything to do with your reassigning the validations object and not setting on it directly. Maybe vuelidate hangs on to a ref to it so your reassignment has no effect

**Comment by mbouclas** [comment]
Could be, but if you can't reassign the object, how can you set it dynamically? I tried a lot of stuff, even not assigning a validation object to the component at all, rather than assigning it in the mixin, but no joy

**Comment by mkoryak** [comment]
let validations = this.$options.validations

**Comment by mbouclas** [comment]
where would you have that?

**Comment by mkoryak** [comment]
The place you declare validations now, at the top of beforeCreate

**Comment by mbouclas** [comment]
Ok, this works, provided you have setup the object in the component like so :
```
        validations : {
            formData : {}
        }
```
However it will not set the data object. To do that, the hook in the mixin needs to be `created` or above.

@mkoryak thanks for the help. 

P.S: Having this functionality in a mixin is not that bad. In this case we end up with a reusable way to setup dynamic forms with validation which is cool.
