### ISSUE TITLE
Validator Request: url

### ISSUE THREAD

**Issue by foxted** [monterail/vuelidate#80]
Would love to see a url validator :)

**Comment by 38elements** [comment]
I think using [validator.js](https://github.com/chriso/validator.js) like the code below solves it.

```
let isUrl = function(value) {
  if (typeof value === 'undefined' || value === null || value === '') {
    return true;
  }
  return validator.isUrl(value);
};
```

**Comment by Frizi** [comment]
I added native support to that. Thanks for the idea!
