### ISSUE TITLE
$invalid isn't being triggered

### ISSUE THREAD

**Issue by Fleeck** [monterail/vuelidate#81]
Hi, here's my code below:

```html
<form @submit.prevent="loginUser(loginData)">
  <input placeholder="Email" type="email" v-model.trim="loginData.email">
  <p class="new-user-msg" v-if="$v.loginData.email.required">REQUIRED</p>
</form>
```

```javascript
validations: {
loginData: {
	email: {
		required
	},
	password: {
		required
	}
}
```

The problem is that `$invalid` is not triggered, when the field is empty. I checked Vue events in dev tools - no `@input` event was triggered on change. Any ideas?

**Comment by Frizi** [comment]
Well, I can't see any `@input` bound in your example. Simply add `@input="$v.loginData.$touch"` to the input and it should work.

**Comment by Fleeck** [comment]
`@input="$v.loginData.$touch()"`
I had this code on my input,  changes nothing but $dirty attribute

**Comment by Fleeck** [comment]
@Frizi 
problem still reproducing... 

```javascript
<input placeholder="Email" type="email" v-model="loginData.email" @input="$v.email.$touch">
<pre>$v.email: {{ $v.email }} </pre>
```

```javascript
validations: {
     email: {
	required
     }
}
```

In the example above `$invalid` property is always false. I am using Vue 2.1.10 & vuelidate 0.2.0

**Comment by 38elements** [comment]
I think it is necessary to change `v-model="loginData.email" @input="$v.email.$touch` to `v-model="email" @input="$v.email.$touch()"`.

**Comment by Frizi** [comment]
There is something fishy.

If the `email` and `password` field is inside `loginData` data prop, you should use it consistently both in `validations` and in your template. Please double check if that's the case.

**Comment by Fleeck** [comment]
Tried both ways. Even if I have `<input placeholder="Email" type="email" v-model="email" @input="$v.email.$touch()">` -> `$invalid` is never being changed.

**Comment by 38elements** [comment]
The following code works normally.
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
    </head>
    <body>
        <form id="form">
            <input type="text" v-model="loginData.email">
            <input type="text" v-model="loginData.password">
            {{$v}}
        </form>
        <script src="https://unpkg.com/vue/dist/vue.js"></script>
        <script src="vuelidate.min.js"></script>
        <script src="validators.min.js"></script>
        <script>
            Vue.use(window.vuelidate.default);
            let vm = new Vue({
                el: '#form',
                data: {
                    loginData: {
                        email: '',
                        password: ''
                    }
                },
                validations: {
                    loginData: {
                        email: {
                            required: validators.required,
                        },
                        password: {
                            required: validators.required,
                        }
                    }
                }
            });
        </script>
    </body>
</html>
```

**Comment by Fleeck** [comment]
@38elements Could you please provide a working jsfiddle example? Didn't work for me.

**Comment by 38elements** [comment]
I do not know how to use it.
`vuelidate.min.js` and `validators.min.js` are [here](https://github.com/monterail/vuelidate/tree/master/dist).

**Comment by Fleeck** [comment]
Sorry, stupid me. I was importing `required` from `vuelidate` instead of `vuelidate/lib/validators`.
