### ISSUE TITLE
browser build: putting validators on window is bad

### ISSUE THREAD

**Issue by mkoryak** [monterail/vuelidate#82]
in the browser build, you put validators directly on window. You are asking for a collision. It would be better to put it on vuelidate. For example I do this:

```js
// vuelidate validators live on window, and will probably get overwritten accidentally with
// a name like that. if only we could use a module system...
window.vuelidate._ = window.validators;
```

**Comment by Frizi** [comment]
> You are asking for a collision
This is a single name `validators` being exported from the module. That's a documented behaviour. Possibility of collision is minimal and it will always be non zero anyway If you have collisions, you should probably migrate to real js modules instead, but you can always work them around by reassigning globals before and after loading if necessary.

**Comment by mkoryak** [comment]
thats fair, but pretty much anyone sane who is using the browser build will need to do this.
