### ISSUE TITLE
Delay after user stop typing

### ISSUE THREAD

**Issue by SirRafaMedina** [monterail/vuelidate#85]
Is there a way to add a delay or wait N seconds after user stop typing?

Thanks.

**Comment by Frizi** [comment]
Yes, there definitely is. I think I have it already in the docs, but those are not published yet.
Check out the source: https://github.com/monterail/vuelidate/blob/master/docs/partials/examples/ExampleDelayedTouch.vue

**Comment by Frizi** [comment]
I just published the docs.
https://monterail.github.io/vuelidate/#sub-delayed-validation-errors
