### ISSUE TITLE
How to make dynamic data sets conditional?

### ISSUE THREAD

**Issue by muchacho-diesel** [monterail/vuelidate#87]
Is it possible to conditional validate an object of items? In the example below I have multiple language groups. I want only trigger the validation for the language groups where `is_active:` is `true`. The status `is_active:` can dynamically change based on user input.

```
data () {
  return {
    languages: [{
        lang: "en",
        title: "English",
        is_active: true
      }, {
        lang: "fr",
        title: "Français",
        is_active: false
      ],
    }
  },

  validations: {
    languages: {
      $each: {
        title: { required },
      }
    } 
  }
}
```

**Comment by Frizi** [comment]
This is similar in behaviour to `sameAs`. You just need a bit different logic inside.
```javascript
$each: {
  title (val, obj) {
    return !obj.is_active || required(val)
  }
}
```
