### ISSUE TITLE
regular expression validation 

### ISSUE THREAD

**Issue by aziz19** [monterail/vuelidate#89]
hey, 
any idea how to use regular expression ?

**Comment by pczarn** [comment]
Do you mean a use of regular expressions in custom validation? Take a look at the `numeric` validator, and change the code below to make your own validator
```js
const numeric = value => {
  if (typeof value === 'undefined' || value === null || value === '') {
    return true
  }
  return /^[0-9]*$/.test(value)
}
```

**Comment by aziz19** [comment]
thanks, thats what i meant
