### ISSUE TITLE
'Required' is not working if input has only space

### ISSUE THREAD

**Issue by shyamchandranmec** [monterail/vuelidate#90]
I checked the value of $required. It is set to true and $error is set to false when I enter space in the input field.  But in your examples it works the other way. I am using  "vuelidate": "^0.2.0"

**Comment by Frizi** [comment]
That's all right. Space is a valid input. You have `.trim` modifier in Vue itself if you want to ignore whitespaces. https://vuejs.org/v2/guide/forms.html#trim
