### ISSUE TITLE
Why the validation not working

### ISSUE THREAD

**Issue by towry** [monterail/vuelidate#91]
"vue": "^2.1.10",
"vuelidate": "^0.2.0"

```html
<textarea
	id="motto"
	v-on:input="$v.model.motto.touch()"
	v-model.trim="model.motto"
	placeholder="xxxxxxxxxxxxxx"
	class="mo-input mo-no-padding moto-input"></textarea>
```

```js
data() {
	return {
		isRealLocation: true,
		model: {
			name: null,
			gender: null,
			city_name: null,
			birth: null,
			motto: null,
		},
		preSetDate: null,
	}
},

validations: {
	model: {
		motto: {
			maxLength: maxLength(2)
		}
	},
},
```

It seems `maxLength` never got called. I tried to use a custom validation function, and that function never got called either.

---

It seems the nested validation not working.

**Comment by laubd** [comment]
import { maxLength } from 'vuelidate/lib/validators'

**Comment by Frizi** [comment]
Please provide full and working example. I see no reason why this code shouldn't work as it is, but it's incomplete.

**Comment by towry** [comment]
If I do not use nested validation, it will work, it just don't work for nested validation.

**Comment by johnhalsey** [comment]
I'm also having this same issue using vuelidate 0.4.3 and vue 2.0.1.  The nested objkects do not get validated properly

**Comment by maciz84** [comment]
Any news on this, I have the same issue?
