### ISSUE TITLE
TypeError: o.default is not a function in validators.min.js

### ISSUE THREAD

**Issue by 38elements** [monterail/vuelidate#92]
I installed by npm and used the file under the dist directory in the browser.

The following error occurs in `dist/validators.min.js` at 0.3.0.

```
TypeError: o.default is not a function  validators.min.js
```

**Comment by Frizi** [comment]
Thanks for this request. I'm able to reproduce it and I'll fix it shortly.

**Comment by 38elements** [comment]
@Frizi 
`dist/validators.min.js` normally works at `0.3.1`.
Thanks a lot.

**Comment by Frizi** [comment]
I was just going to post that :) Happy coding!
