### ISSUE TITLE
$v.$touch() does not cascade properly to nested array elements

### ISSUE THREAD

**Issue by felix-d** [monterail/vuelidate#95]
Thanks for this fantastic pragmatic library, love it.

I'm trying to make all the fields of my form dirty when pressing a button, but it seems `$v.$touch` does not cascade to nested array elements.

See [this JS Fiddle](https://jsfiddle.net/z42kg1jx/3/) to see what I mean. There are 2 fields here, text and a nested comment. Both are required, but when clicking the button, only `text` gets dirty.

It also seems to be the case for other functions such as `$reset`.

Am I missing something or is this a bug?

**Comment by amirrustam** [comment]
I'm noticing something similar after 0.2.0 to 0.3.0 update. `$touch` does not seem to be recursively setting the `$dirty` flag of validation groups either. Seem to be a regression.

**Comment by felix-d** [comment]
Glad to know I'm not crazy :) 

I'm trying to dig in the code to see what might happen but validators mapping looks somewhat complex. I don't see any test case covering this scenario either :(

**Comment by amirrustam** [comment]
.....Or you could downgrade to 0.2.0 😜

I'm short on time to push a fix, though I think I did find the test case for it: https://github.com/monterail/vuelidate/blob/master/test/unit/specs/validation.spec.js#L285

**Comment by Frizi** [comment]
Hi, thanks for the fiddle! I'm taking a look at this.

**Comment by felix-d** [comment]
> though I think I did find the test case for it:

@amirrustam this test case does not cover array elements hehe

Thanks @Frizi !!

**Comment by Frizi** [comment]
I already have a test case for it and I'm working on a fix. Seems like this combined with other bugs deserves a full rewrite :D but don't worry, I'm not going to change public API.

**Comment by Frizi** [comment]
Fixed in v0.4.0

**Comment by amirrustam** [comment]
Thanks for the fix @Frizi. Will test it out today.
