### ISSUE TITLE
how to add conditional validations

### ISSUE THREAD

**Issue by shyamchandranmec** [monterail/vuelidate#97]
I want to add validation to a property only if another expression is true.. I tried the following

    validations () {
        if (active) {
            return {
                name: {
                    required
                }
            };
        } else {
            return {
                name: {
                    required
                },
                description: {
                    required
                }
            };
        }
    }

But this doesn't work. How to achieve this

**Comment by Frizi** [comment]
This should work. Do you mean `this.active`?

**Comment by shyamchandranmec** [comment]
@Frizi yeah. 'active' is this.active or some expression in the computed or data properties. 
But this was not working.

**Comment by Frizi** [comment]
Please provide a full example, ideally based on this fiddle: https://jsfiddle.net/Frizi/b5v4faqf/

**Comment by Frizi** [comment]
I created an example and it appears to work as intended. https://jsfiddle.net/6tbr4u08/

Please reopen if you think it's not solved yet.

**Comment by shyamchandranmec** [comment]
@Frizi  I might have done some mistake. Will try it out once again. Thanks for the example

**Comment by luispuentesvega** [comment]
Hi. I have an issue when I am using requiredIF in an object

**Comment by bernarddoci** [comment]
Have you tried requiredIf validator.

```
      required: requiredIf(function (nestedModel) {
        return !this.isOptional && nestedModel.someFlag
      })
```

**Comment by SuKSW** [comment]
This worked for me.
```
validations: { 
       message: {
            required: (function () {
                if(this.isRequired) {
                    return this.message.length > 7; //short messages are not considered valid
                } else {
                    return true; 
                } 
            })
        },
 },
```

**Comment by ricky11** [comment]
does not work if required : requiredIf , is combined with email.
requiredIf does not cover email, hence email will sitll be required if field is not empty.
how would you tackle this?

**Comment by collin-thomas** [comment]
Tagging on to what @ricky11 said.  `required: requiredIf` does not work when combined with `yes`

```JavaScript
confirmChange: {
  required: requiredIf('myGetter'),
  yes: v => v
}
```

**Comment by Sreesanth46** [comment]
I want email validation only if a prop value is true. Already tried this, not working.

`    validations() {
        return {
            modelValue: {
                requiredIf: requiredIf(this.required),
                email: requiredIf(true),
            },
        };
    },`
