### ISSUE TITLE
Validation with dynamic values in an array

### ISSUE THREAD

**Issue by xereda** [monterail/vuelidate#98]
Validation with dynamic values in an array

I need to validate two elements of an array. They refer to the geoLocalization information that goes to MongoDB, in the following format:

Form: {
    GeoLocation: {
       Coordinates: [
          '',
          ''
       ]
    }
}

But some $properties of vuelidate are not updated to the "geoLocation.coordinates[x]" property.

See the example in jsfiddle: https://jsfiddle.net/xereda/b5v4faqf/13/

Thank you for your feedback,

**Comment by pczarn** [comment]
It starts working with explicit calls to `$touch`
```
    v-on:input="$v.field.array[0].$touch()"
```

**Comment by xereda** [comment]
Yeah, I think I did it. Watch:

![captura de tela 2017-03-15 as 17 01 44](https://cloud.githubusercontent.com/assets/14337850/23968346/1d758f40-09a1-11e7-9c7e-1fe6473a3912.png)

**Comment by xereda** [comment]
Ok, I got it. There was no need to enter the function call definition completely:

![captura de tela 2017-03-15 as 17 04 30](https://cloud.githubusercontent.com/assets/14337850/23968438/7a2a30f6-09a1-11e7-8749-35d257984cc7.png)

**Comment by xereda** [comment]
But now we come to another problem. I can not get the two errors. Analyze the simulation I did:

**Comment by xereda** [comment]
Will it be released at bulma@0.3.3?

**Comment by Frizi** [comment]
@xereda It will be released probably at `vuelidate@0.4.0`, but you got it almost right.

**Comment by xereda** [comment]
Thank you. Congratulations again for the great work!

**Comment by Frizi** [comment]
Fixed in v0.4.0
