### ISSUE TITLE
$v is not defined in single file component

### ISSUE THREAD

**Issue by shiningshisa** [monterail/vuelidate#99]
I'm trying to use the vuelidate plugin with my vue-router-enabled web app. I keep getting the  following error:

`[Vue-warn]: Property or method "$v" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option`

This is my bootstrap file for reference:

`import Vue from 'vue'
import Resource from 'vue-resource'
import App from "./components/App.vue"
import router from "./router/appRouter.js"
import store from "./store/appStore.js"

Vue.use(Resource);
Vue.use(Vuelidate);

const app = new Vue({
  el: '#app',
	router,
	store,
  render: (h) => h(App)
})
`

I'm using the plugin with the following code in component file:

```
<template>
<div>
    <div :class="'input-group ' + {'form-group-error': $v.email.$error }"> 
    <p class="label"> Email </p>
    <input type="text" id="email" v-model="models.email" @input="$v.email.$touch">
    </div>
</div>
</template>

<script>
    const { required, minLength, alpha, email, numeric } = require("vuelidate/lib/validators");
    export default 
    {
        data(){...},
        methods:{...},
        etc
    }
<script>
```

I can't figure out how to reference $v in my code to allow the vue instance to access it. Sorry in advance if I'm missing something blindingly obvious but I've stuck on this for a while

Thanks

**Comment by 38elements** [comment]
I think it is necessary to add the following code.

```
import Vuelidate from 'vuelidate'
```

**Comment by shiningshisa** [comment]
@38elements just tried this, still throwing the same error
Thanks

**Comment by daewooLeeNy** [comment]
in my case, need to property 'validations'
const app = new Vue({
el: '#app',
router,
store,
render: (h) => h(App),
validations: {
 ... 
}
})

**Comment by Frizi** [comment]
You need to add `validations` key to your component to make Vuelidate bootstrap itself.

**Comment by cj** [comment]
I'm having the same issue too.  I have the property `validations` in my component.  I'm doing `Vue.use(vuelidate)`.

**Comment by Jack85** [comment]
trick with validation key works for static validation, but how to bootstrap dynamic validations?

**Comment by Frizi** [comment]
@Jack85 the same way. Simply use `validations` as a function.

**Comment by Jack85** [comment]
I tried that. Ended with that error v not found.

**Comment by wdews** [comment]
Having the same issue. Using Vue's single-file component within their Webpack build from Vue CLI. I've tried everything: `import Vuelidate from 'vuelidate'` and `Vue.use(Vuelidate)`, tried bootstrapping via the component mixin, combining those solutions...nothing is working.

**Comment by Frizi** [comment]
@wdews can you provide a way to reproduce that?

**Comment by wdews** [comment]
@Frizi Figured it out...it was my simple misunderstanding of how to properly export multiple things at once in ES6 syntax using `export`... Since my `validations` object will be reused in multiple places, I abstracted it into its own file with a `validate` function I wrote to pull in the appropriate message corresponding with failed rules. When exporting, I foolishly used `export default { validate, validations }` versus the correct `export { validate, validations }`. I also wasn't properly destructuring when importing said module. `import validations from '@/modules/validation'` became `import { validations } from '@/modules/validation'`. Solved my woes!

**Comment by BenoitRanque** [comment]
@Frizi  Had the same issue, solved by adding `validations: {}` to root vue instance.

Is this Ideal? The actual validation happens in single file components, but setting `validation` object there had no efect

**Comment by samayo** [comment]
@Frizi Please reopen this. I installed this lib thinking it was going help me build the my app faster, but I Just spent 3 hours trying to make it work before giving up. I think this error is a bug that needs a fix

**Comment by Frizi** [comment]
@samayo What's the problem here? There are plenty examples in the docs, copying them should get you started in no time. Why would you need to use `$v` when no validation is defined?

**Comment by GanchoDanailov** [comment]
Same error here :/

**Comment by samayo** [comment]
@GanchoDanailov couldn't fix it, and decided to go with https://github.com/baianat/vee-validate you won't regret it

**Comment by Frizi** [comment]
@samayo  @GanchoDanailov 

You have to define validation in odrer to be able to use it. That means you need this code in your component:
```javascript
validations: {
 // my validations definition
}
```

Please check this fiddle as a working example: https://jsfiddle.net/Frizi/b5v4faqf/

If you still experience any problems, please explain it and I'll try my best to fix it and make it more obvious to the library user by throwing some helpful errors.

**Comment by BenoitRanque** [comment]
You also need to instantiate vuelidate in main.js. Even if you have no validations there.

```
new Vue({
   validations: {}
)}
```

something like that

**Comment by Anu2biZ** [comment]
Hey guys, had the same error... Using Nuxt. 
It was so interesting, I have 2 plugins - Axios and Vuelidate. Axios works good, i Wrote in /plugins/vuelidate.js next:
`import Vue from 'vue'
import Vuelidate from 'vuelidate'

Vue.use(Vuelidate)
`

But that doesn't work. I surfed 100500 sites, but... IT IS OMMMGGG

I just wrote theese 3 lines into my component.. 

`import { required, sameAs, minLength, email } from 'vuelidate/lib/validators'

import axios from '~/plugins/axios'

import Vue from 'vue'
import Vuelidate from 'vuelidate'
Vue.use(Vuelidate)

export default {
  data () {
    return {
      login: '123',
      email: '',
      password: '',
      password2: '',
      isActive: 'testetst'
    }
  },
  validations: {
    login: {
      required,
      minLength: minLength(6)
    },
    email: {
      required,
      email
    },
    password: {
      required,
      minLength: minLength(6)
    },
    password2: {
      required,
      sameAsPassword: sameAs('password')
    }`


SO IT'S WORKKKK...............

May be it will help anyone)

**Comment by Firman95** [comment]
I still have this issue with vuelidate@0.6.1 and vuelidate@0.5.0
this is my main.js.
```
import Vuelidate from 'vuelidate';
import { required} from 'vuelidate/lib/validators'
Vue.use(Vuelidate);
new Vue({
   validations: {
      someField:{
        required
      }
    }
)}
```
and this is myComponent.vue
```
export default {
   mounted(){
       console.log(this.$v);
    }
}
```
@Frizi Can u please re-open this issue?

**Comment by Rjgoolsby** [comment]
To expand on @Anu2biZ. I've found the easiest way to fix this is to either include 
```
import Vuelidate from 'vuelidate'
Vue.use(Vuelidate)
```

in your main.js  
OR
```
import Vue from 'vue'
import Vuelidate from 'vuelidate'
Vue.use(Vuelidate)
```
in your component. I'm not sure which is the best but either works. I couldn't find this anywhere in the documentation and I wonder if this is something isolated to our setup (I'm using a modified vue js webpack starter). 

I got here by Googling so maybe this will help someone down the road.

**Comment by leevigraham** [comment]
My `app.js` compiled with webkit:

```import Vue from 'vue'
import Vuelidate from 'vuelidate'

Vue.use(Vuelidate)

import App from './App'
import { sync } from 'vuex-router-sync'
import store from './store/index'
import router from './router'

Vue.config.productionTip = false
Vue.config.devtools = true

sync(store, router)

/* eslint-disable no-new */
new Vue({
  el: '#app',
  store,
  router,
  components: {App},
  template: '<App/>',
})```

Working fine.

**Comment by duythang** [comment]
@Anu2biZ : I met same issue with you. It fixed by using only  your way. I dont know why when putting vuelidate in plugins of Nuxt, it does not work.

**Comment by javiercbk** [comment]
I made a stupid mistake

```js
import { email } from 'vuelidate/lib/validators';
export default {
  data() {
    email: '',
  },
  validators: {
    email,
  }
}
```

See anything wrong? `validators` is wrong, `validations` is the proper property name.

If you don't have the `validations` property you'll see the "`$v` not defined" error

**Comment by Rrrom** [comment]
Have some problem when try to use vuelidate plugin in single file component

app.js

import Vue from 'vue';
    import Vuelidate from 'vuelidate';

    Vue.use(Vuelidate)

    const T = new Vue({
      router: router,
      template: '<div id="app"><heading></heading><transition :css="false" mode="out-in" @enter="enter" @leave="leave"><router-view></router-view></transition></div>',
      data: {
        currentRoute: window.location.href,
      },
      created(){
        this.$watch('$v', () => {
           console.log('$v changed')
        })
      },
      validations: {}
    }).$mount('#app');

.vue file

<template>
      <form id="registration" class="form form_bl " @submit="handleSubmit" action="">
      <input type="email"  v-model="email" name="email" class="inp m30_b" placeholder="E-mail">
      <button class="btn">Send</button>
    </template>

    import { validationsMixin } from 'vuelidate';
    import { required, minLength } from 'vuelidate/lib/validators';
    export default {
      data () {
        return {
          email: ''
        }
      },
      validations: {
        email: {
          required,
        }
      },
      methods: {
        handleSubmit: function(e) {
          e.preventDefault();
          console.log($v.email);
        }
      }
    }
and I've just got $v is not defined, I try everything

reorder components
include Vuelidate inside .vue file

but nothing help

**Comment by fadedbee** [comment]
I have the same problem.  I am using a (Webpack) project structure generated by vue-cli v3.

I have tried putting
<pre>
  import Vue from 'vue'
  import Vuelidate from 'vuelidate'
  import required from 'vuelidate/lib/validators'
  Vue.use(Vuelidate);
</pre>
in main.js and App.vue.

The only things which makes $v appear is putting the imports and validators in main.js, but then $v just stays empty, perhaps because "data" is defined in the App.vue.

I've spent four hours with this problem, so I'm going to try https://baianat.github.io/vee-validate/ for a while.

**Comment by thedamon** [comment]
I'm using the mixin because I only have validations in certain parts of my app. Nowhere in the docs does it state that I have to add a validations object to my main Vue instance (even in frizi's comments here)... but that would explain why `this.$v` is always undefined

**Comment by roasted-toast** [comment]
My mistake was to put the `validations`key inside the `data()` method.
Hope this will help someone out.

**Comment by Linkmetal** [comment]
I've imported vuelidate from CDN and had this issue, I've fixed it with:

```
const { required, minValue } = window.validators;
var validationMixin = window.vuelidate.validationMixin;
.
.
.
 // Vue instance
new Vue({
      mixins: [validationMixin],
      validations: {...}, // OUTSIDE OF DATA
      .
      .
      .
```

Note: In my project I couldn't use any local dependencies, so I had to import it from CDN.

**Comment by RomainMazB** [comment]
> My mistake was to put the `validations`key inside the `data()` method.
> Hope this will help someone out.

Thank you for your comment, man! I was making the same mistake! No need of validations: {} in main.js.

**Comment by sommy1994** [comment]
I am having the same error, I have followed all the possible methods mentioned above and I am still having the error. 
`export default {
    data() {
        return {
            userData: {
                email: '',
                password: ''
            }
        }
    },
    validations: {
        userData : {
            email: { required, email },
            password: { required }
        }
    },
    methods: {
        changeState() {
            eventBus.$emit('show', true);   
        },
        submit: (userData) => {
            this.$v.$touch();

            if (!this.$v.$invalid()) {
                //this.signIn();
            } else 
                toastr.warning("please fill in the fields appropriately")
        },
        // ...mapActions([
        //     'signIn'
        // ])
    }
}`

Please help

**Comment by dobromir-hristov** [comment]
@sommy1994 invalid is a property not a method

**Comment by sommy1994** [comment]
@dobromir-hristov , corrected it and still having the same error

**Comment by dobromir-hristov** [comment]
Your submit method is a fat arrow function, which does not have the same `this` context as the component.

**Comment by sommy1994** [comment]
Changed it and it is working. Thanks

**Comment by literakl** [comment]
I had to add this. before $v

**Comment by buttererror** [comment]
This error accidentally ran into it, but I figured out what my problem was, I did everything as the docs says, installed the package by npm, import and use the package in the project root js file, the only mistake was put "validations" inside the vue component data 
`data() {
  return {
    validations: {}
  }
}` 
but it should be instead outside
`data() {
  return {
  }
}
validations: {}`

**Comment by LarryJung** [comment]
I tried thousands ways. Just only two ways do work.

1. declare these three line in component
```javascript
...
<script>
import Vue from 'vue'
import Vuelidate from 'vuelidate'

Vue.use(Vuelidate)

export defaut {...}
```
or
2. use mixin in component
```javascript
...
<script>
import { validationMixin } from 'vuelidate'

export default {
  mixins: [validationMixin],
  ...
}
```
no need to put the validations in this
```javascript
new Vue({
    el: '#app',
    router,
    store,
    render: h => h(App),
    validations: {} // no need
});
```

**Comment by heyjordn** [comment]
Thanks so much @LarryJung , after hours of searching solution #2 worked with Nuxt.js for me.

**Comment by alvaro-canepa** [comment]
With TS decorators is needed to add `hooks`.
```ts
// main.ts
import Component from "vue-class-component";
Component.registerHooks(["validations"]);

import Vue from "vue";
import App from "./App.vue";
...
```

```ts
// component.vue
import { Vue, Component } from "vue-property-decorator";

export default class DemoComponent extends Vue {

  validations() {
    return {
      ....
    };
  }
}
```

**Comment by reathh** [comment]
@alvaro-canepa I would never figure this out if it weren't you. Thank you!

**Comment by the91end** [comment]
Struggled for hours with this, and then I realized I am using require
`const Vuelidate = require('vuelidate')`

should be
`const { Vuelidate } = require('vuelidate')`

Hope this help someone

**Comment by shahabgohar** [comment]
Encountered the same issue but solved it by using this
https://markus.oberlehner.net/blog/vue-form-validation-with-vuelidate/

**Comment by lcsoliveira** [comment]
@the91end thanks, man! I had the same problem.

**Comment by uris173** [comment]
thank you so much, thank you

**Comment by Sazzad-Saju** [comment]
inside export default{} need to include validations{} where the validation rules are defined. In my case, I got the same error for mistakenly wrote validation instead of validations!!

**Comment by tcrite1** [comment]
I'm having this same issue but with the vue 3 version using the options api
